import type { BlogArticleSeed } from '../shared'

const ARTICLE: BlogArticleSeed = {
  slug: 'industrial-hose-is-not-hydraulic-hose',
  title: 'Industrial hose is not hydraulic hose: selecting on the medium, not the pressure',
  excerpt:
    'Hydraulic hose is chosen on pressure. Industrial hose is chosen on what is going through it, at what temperature, and whether it has to suck as well as blow.',
  categorySlug: 'industrial-hose',
  authorSlug: 'anjali-krishnan',
  seoTitle: 'Industrial hose vs hydraulic hose — how selection differs',
  seoDescription:
    'Industrial hose is selected on medium, temperature and suction duty rather than pressure alone. The five questions that decide the specification.',
  focusKeyword: 'industrial hose selection',
  publishedAt: '2026-08-17T11:00:00.000Z',
  bodyBlocks: [
    {
      type: 'key_takeaways',
      items: [
        'Hydraulic hose is specified pressure-first. Industrial hose is specified medium-first, and getting that order wrong is how the wrong hose gets fitted.',
        'The liner is the part that meets the product. It decides chemical compatibility, temperature range and whether the hose is fit for food or potable use.',
        'Suction duty is a separate question from pressure. A delivery hose collapses under vacuum unless it is built to resist it.',
        'On flammable transfer, electrical continuity is a safety feature, not a specification detail — static has to have somewhere to go.',
        'Composite hose and rubber hose solve different problems. Composite is lighter and more chemically versatile; rubber is more robust to rough handling.',
      ],
    },
    {
      type: 'lead',
      html: 'The habit that causes most wrong orders is treating industrial hose like hydraulic hose with a different cover. On a hydraulic circuit the pressure is the hard constraint and everything else follows. On a transfer hose the <em>medium</em> is the hard constraint, and a hose that is nominally strong enough can still be entirely unsuitable.',
    },

    { type: 'section_head', number: '/01', title: 'Five questions, in this order.', anchor: 'five-questions' },
    {
      type: 'decision_tree',
      heading: 'What decides the specification',
      intro: 'Answer them in order. Each one narrows the field before the next matters.',
      branches: [
        { condition: 'What is going through it?', outcome: 'This chooses the liner, and therefore most of the hose.', detail: 'Chemical compatibility is a property of the liner material, not of the hose as a whole. Two hoses that look identical can have completely different tolerances.' },
        { condition: 'At what temperature — of the medium AND the surroundings?', outcome: 'Both matter, and Gulf ambient is part of the answer.', detail: 'A hose rated for a medium temperature can still be working outside its range if it sits in direct sun on a yard at midday.' },
        { condition: 'Does it have to suck as well as deliver?', outcome: 'If yes, it needs suction reinforcement — usually a helix.', detail: 'A delivery-only hose flattens under vacuum. This is the single most common mis-order in the category.', sku: 'IH-IH-A210' },
        { condition: 'Is the medium flammable, or the atmosphere hazardous?', outcome: 'Electrical continuity becomes a requirement.', detail: 'Static generated by flow has to be conducted away. Continuity is checked, not assumed, and it is checked periodically rather than once.' },
        { condition: 'Is it food, beverage or potable water?', outcome: 'The liner must be a compliant grade, and traceably so.', detail: 'This is a documentation requirement as much as a material one — an auditor will ask for the certificate, not the hose.', sku: 'IH-IH-SANF' },
      ],
    },

    { type: 'section_head', number: '/02', title: 'Suction is not a pressure rating.', anchor: 'suction' },
    {
      type: 'direct_answer',
      question: 'Can a delivery hose be used for suction?',
      answer:
        'No. A delivery hose is built to resist pressure from the inside; under vacuum it has nothing holding the wall out and it collapses. Suction and delivery hose carries a reinforcing helix for exactly this reason, which is why it is heavier, stiffer and more expensive for the same bore.',
    },
    {
      type: 'paragraph',
      html: 'This catches people because the failure is not immediate. A delivery hose pressed into suction service may work while the pump is primed and flatten the moment it is not, which reads as a pump problem rather than a hose problem.',
    },

    { type: 'section_head', number: '/03', title: 'Composite or rubber.', anchor: 'composite-or-rubber' },
    {
      type: 'comparison_table',
      caption: 'Two constructions, different strengths',
      columns: ['Property', 'Composite hose', 'Rubber hose'],
      rows: [
        { cells: ['Construction', 'Multiple unbonded film and fabric layers between wire helices', 'Bonded rubber liner, reinforcement and cover'] },
        { cells: ['Weight for a given bore', 'Lighter', 'Heavier'] },
        { cells: ['Chemical versatility', 'Broad — the film layers can be selected for the duty', 'Set by the liner compound'] },
        { cells: ['Failure behaviour', 'Tends to weep before it fails outright', 'Can fail more abruptly'], highlight: true },
        { cells: ['Handling robustness', 'Less tolerant of crushing and dragging', 'More tolerant of rough handling'] },
        { cells: ['Typical use', 'Chemical and oil transfer, tanker and dockside', 'General industrial, water, air, abrasive service'] },
      ],
    },
    {
      type: 'callout',
      tone: 'note',
      title: 'The weep-before-failure behaviour is a feature.',
      body: 'On transfer duty, a hose that shows you it is failing before it lets go is worth a great deal — which is much of why composite is standard in the applications where a sudden release would be serious.',
    },

    { type: 'product_embed', heading: 'Across the main service types', skus: ['IH-IH-A190', 'IH-IH-A210', 'IH-IH-A125', 'IH-IH-A906PG'] },
    {
      type: 'faq_block',
      heading: 'Common questions',
      items: [
        { question: 'Can I use a hydraulic hose for compressed air?', answer: 'It will hold the pressure, but that is not the question. Air hose is built for the duty — including how it behaves if it fails — and hydraulic hose is heavier, stiffer and more expensive for no benefit here.' },
        { question: 'How do I check chemical compatibility?', answer: 'Against a compatibility chart for the specific liner material, at the concentration and temperature you are actually running. Compatibility is not binary and it degrades with temperature, so a chart entry that assumes ambient may not hold on a hot line.' },
        { question: 'What does electrical continuity actually mean here?', answer: 'That there is a conductive path along the assembly so static generated by flow can be conducted to earth rather than accumulating. It has to be intact through the couplings as well as the hose, and it is verified periodically.' },
        { question: 'Does Gulf ambient temperature really change the selection?', answer: 'Yes. A hose in direct sun on a yard sits well above shade temperature, and cover ageing accelerates with it. Specify against what the hose experiences, not against the shaded air temperature.' },
      ],
    },
    { type: 'category_link', slug: 'industrial-hoses', label: 'Industrial hose by service', blurb: 'Air, water, oil and chemical, food grade and composite — in stock in Dubai.' },
    { type: 'as_of_stamp', verifiedOn: '2026-08-17', note: 'Selection principles only. Chemical compatibility must be checked against the liner material at your concentration and temperature.' },
    { type: 'cta_block', heading: 'Tell us the medium and the duty.', body: 'Medium, concentration, temperature, pressure and whether it has to suck. That is enough for our engineers to specify the hose and the couplings.', quoteLabel: 'Specify a hose' },
  ],
}

export default ARTICLE
