/**
 * Metallic Hoses — Batch 2 (High-Pressure + Specialty Cores) — 2026-05-08
 *
 * 20 products split between:
 *  - High-Pressure (9): metallic-high-pressure-hoses category — fully
 *    compressed annular and helical designs, plus closed-pitch omega
 *  - Specialty Cores / Fire Protection (11): metallic-fire-protection-hoses
 *    category — Lock Section, Armor-Flex, Smooth-Flex, Fire Jacket / Fire Tape
 *
 * Brand split: Thorburn Flex 16, Senior Flexonics 2, Hose Master 1, Witzenmann 1.
 */
import type {
  FaqEntry,
  ImportBatch,
  ProductImportPayload,
} from '../import/types'

function escape(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

type Input = {
  sku: string
  title: string
  brandSlug: string
  countryOfOrigin: string
  categorySlug: 'metallic-high-pressure-hoses' | 'metallic-fire-protection-hoses'
  subType: string
  hoseFamily: 'High-Pressure Metallic' | 'Specialty Metallic Core' | 'Fire Protection'
  constructionType: 'Annular Corrugated' | 'Helical Corrugated' | 'Smooth-Bore'
  oemPartCode: string
  braidConfiguration: 'Unbraided' | 'Single Braid' | 'Double Braid' | 'Triple Braid' | 'N/A'
  coreMaterial: 'Type 304 SS' | 'Type 316L SS' | 'Type 321 SS' | 'Other'
  braidMaterial: 'Type 304 SS' | 'Type 316L SS' | 'Type 316 SS' | 'Inconel' | 'N/A (Unbraided)'
  endFittingMaterial: string
  nominalIdRange: string
  bendRadiusStaticMm: number
  bendRadiusDynamicMm: number
  liveLengthForVibrationMm: number
  weightKgPerM: number
  maxWorkingPressureBar: number
  minBurstPressureBar: number
  safetyFactor: number
  tempMinC: number
  tempMaxC: number
  iso10380Class: 'PSL 1' | 'PSL 2' | 'PSL 3' | 'N/A'
  pedModule: string
  asmeCompliance: string
  naceMr0175: boolean
  cgaUlChlorineCerts: string
  oneLiner: string
  applications: string[]
  leadTimeDays: number
}

function buildHtml(g: Input): string {
  const apps = g.applications.map((a) => `<li>${escape(a)}</li>`).join('')
  const tempRange = `${g.tempMinC}°C to +${g.tempMaxC}°C`
  const naceLine = g.naceMr0175 ? '<li>NACE MR0175 / ISO 15156 (sour-service compliant)</li>' : ''
  const cgaLine = g.cgaUlChlorineCerts && g.cgaUlChlorineCerts !== 'N/A' && g.cgaUlChlorineCerts !== ''
    ? `<li>${escape(g.cgaUlChlorineCerts)}</li>` : ''
  const isFireProtection = g.hoseFamily === 'Fire Protection'
  const isHP = g.hoseFamily === 'High-Pressure Metallic'

  const introParagraph = isHP
    ? `${escape(g.subType)} for service that exceeds the rating envelope of standard SS Annular hoses. Working pressure to ${g.maxWorkingPressureBar} bar.`
    : isFireProtection
      ? `${escape(g.subType)} — fire-survivability protection layer for metallic and process hoses. Maintains structural integrity in fire exposure events per applicable insulation regulations.`
      : `${escape(g.subType)} — specialty metallic core for service requiring mechanical protection (vibration, abrasion) beyond standard corrugated hose capability.`

  return `<p>The <strong>${escape(g.title)}</strong> is a ${escape(g.hoseFamily.toLowerCase())} product. ${introParagraph}</p>
<h3>Construction</h3>
<ul>
<li>Type: ${escape(g.hoseFamily)} — ${escape(g.subType)}</li>
<li>Construction: ${escape(g.constructionType)}</li>
<li>Core / wrap material: ${escape(g.coreMaterial)}</li>
${g.braidConfiguration !== 'N/A' ? `<li>Braid: ${escape(g.braidConfiguration)} — ${escape(g.braidMaterial)}</li>` : ''}
<li>End fitting material: ${escape(g.endFittingMaterial)}</li>
<li>Nominal ID range: ${escape(g.nominalIdRange)}</li>
${g.bendRadiusStaticMm > 0 ? `<li>Bend radius (static / dynamic): ${g.bendRadiusStaticMm} / ${g.bendRadiusDynamicMm} mm minimum</li>` : ''}
${g.weightKgPerM > 0 ? `<li>Weight: ~${g.weightKgPerM} kg/m</li>` : ''}
</ul>
<h3>Performance</h3>
<p>${isHP ? `Working pressure ${g.maxWorkingPressureBar} bar (smallest bore, ${g.braidConfiguration.toLowerCase()} configuration). Burst pressure ${g.minBurstPressureBar} bar. Safety factor ${g.safetyFactor}:1 per ISO 10380.` : isFireProtection ? `Designed to maintain dimensional and pressure-containment integrity through fire-exposure events. Compatible with metallic and process hoses up to the maximum specified bore.` : `Mechanical protection rating: physical impact, abrasion, vibration absorption beyond standard corrugated hose capability.`} Operating temperature ${escape(tempRange)} continuous. ${isHP ? 'All assemblies hydrotested at 1.5× working pressure with witness-test certificate available.' : 'Each assembly inspected at OEM facility against the applicable specification.'}</p>
<h3>Applications</h3>
<ul>
${apps}
</ul>
<h3>Compliance</h3>
<ul>
${g.iso10380Class !== 'N/A' ? `<li>ISO 10380:2012 ${escape(g.iso10380Class)}</li>` : ''}
${g.pedModule !== 'None' ? `<li>Pressure Equipment Directive 2014/68/EU ${escape(g.pedModule)}</li>` : ''}
${g.asmeCompliance ? `<li>${escape(g.asmeCompliance)}</li>` : ''}
${naceLine}
${cgaLine}
<li>EN 10204 3.1 / 3.2 mill test reports on request</li>
</ul>
<h3>How to order</h3>
<p>Confirm (a) line working pressure (or for fire-protection: the host hose specification), (b) operating temperature range, (c) bore size and overall length, (d) end fitting style, (e) braid count where applicable, (f) any required certifications. Indus quotes ex-OEM with mill test reports and pressure-test certificates.</p>
<h3>Companion products</h3>
<p>${isHP ? 'Pair with matched-pressure flanged or threaded fittings, plus thermal insulation jackets for elevated-temperature service.' : isFireProtection ? 'Apply over standard metallic or industrial hoses to upgrade fire-survivability. Compatible with most ANSI flange and Weco union end-fitted assemblies.' : 'Apply over standard metallic hoses to upgrade impact / vibration / abrasion protection. Lock-Section provides interlocking mechanical protection; Armor-Flex adds ball-joint articulation; Smooth-Flex provides a non-corrugated alternative.'} Indus also supplies matched ANSI flanges, gaskets, and stud bolts.</p>`
}

function buildFaqs(g: Input): FaqEntry[] {
  const isHP = g.hoseFamily === 'High-Pressure Metallic'
  const isFireProtection = g.hoseFamily === 'Fire Protection'

  return [
    {
      q: isHP ? 'What is the working pressure rating?' : isFireProtection ? 'What fire rating does this provide?' : 'What protection does this core provide?',
      a: isHP
        ? `${g.maxWorkingPressureBar} bar working pressure (smallest bore). Burst pressure ${g.minBurstPressureBar} bar minimum, safety factor ${g.safetyFactor}:1 per ISO 10380. Hydrotested at 1.5× working pressure.`
        : isFireProtection
          ? `Designed to maintain hose integrity during fire-exposure events per applicable insulation regulations. Specific fire-rating duration depends on the host hose construction and the surrounding installation. Indus supplies fire-test certificates per OEM testing protocol.`
          : `Mechanical protection — physical impact, vibration, abrasion. ${g.subType.toLowerCase().includes('lock') ? 'Lock-Section provides interlocking ring protection that does not separate under axial load.' : g.subType.toLowerCase().includes('armor') ? 'Armor-Flex ball-joint protection allows articulation while providing impact / abrasion resistance.' : 'Smooth-Flex provides a non-corrugated alternative for service where corrugated profiles are unsuitable.'}`,
    },
    {
      q: 'What sizes are available?',
      a: `${g.nominalIdRange}. ${isHP ? 'Smaller bores carry higher pressure; refer to the OEM datasheet for per-size pressure curves.' : 'Designed to fit over the standard hose bore range — confirm host hose OD on the RFQ.'}`,
    },
    {
      q: 'What is the operating temperature range?',
      a: `${g.tempMinC}°C to +${g.tempMaxC}°C continuous. ${isFireProtection ? 'During fire exposure, the wrap temperature can briefly exceed the continuous limit per the applicable fire-test specification.' : ''}`,
    },
    {
      q: 'What materials are used in construction?',
      a: `Core / wrap: ${g.coreMaterial}. ${g.braidConfiguration !== 'N/A' ? `Braid: ${g.braidConfiguration} of ${g.braidMaterial}.` : ''} End fittings: ${g.endFittingMaterial}.`,
    },
    {
      q: isHP ? 'Why fully-compressed corrugation?' : 'Why this specialty design?',
      a: isHP
        ? 'Fully-compressed corrugation reduces convolution amplitude to maximize pressure containment per unit hose length. This delivers HP capability that standard (uncompressed) corrugation cannot achieve. Trade-off: lower bend flexibility and higher torsional stiffness — best for static or slow-flexure installations.'
        : g.subType.toLowerCase().includes('lock')
          ? 'Lock-Section uses interlocking metal rings rather than continuous helical corrugation. Each ring locks against its neighbor, preventing separation under axial load. Used where the hose must resist pull-through during pressure or impact events.'
          : g.subType.toLowerCase().includes('armor')
            ? 'Ball-joint Armor-Flex consists of articulated ball-joint links that pivot at each segment. Provides impact / abrasion resistance with full articulation around the host hose.'
            : g.subType.toLowerCase().includes('smooth')
              ? 'Smooth-Flex is a smooth-bore alternative to corrugated metallic hose — uses a continuous tube with no convolutions. Lower turbulence, easier to clean, but less flexible than corrugated.'
              : 'Fry-Sil silica-based fabric maintains structural integrity through fire-exposure events. Used as outer wrap on metallic and industrial hoses where fire-survivability regulations apply.',
    },
    {
      q: 'Is this suitable for sour-service (H₂S) wells?',
      a: g.naceMr0175
        ? `Yes — fully NACE MR0175 / ISO 15156 compliant. ${g.coreMaterial} core meets NACE hardness limits.`
        : 'No — this is standard service. For sour-service, specify the NACE-compliant variant on the RFQ.',
    },
    {
      q: 'What standards and certifications are supplied?',
      a: `${g.iso10380Class !== 'N/A' ? `ISO 10380:2012 ${g.iso10380Class}.` : ''} ${g.pedModule !== 'None' ? `PED 2014/68/EU ${g.pedModule}.` : ''} ${g.asmeCompliance}. ${g.naceMr0175 ? 'NACE MR0175 / ISO 15156.' : ''} EN 10204 3.1 / 3.2 mill test reports.`,
    },
    {
      q: 'What is the lead time?',
      a: `Typical lead time ${g.leadTimeDays} working days ex-works OEM. ${isHP && g.maxWorkingPressureBar >= 400 ? 'Ultra-HP (>400 bar) variants are typically build-to-order — confirm OEM build slot at quote stage.' : 'Common configurations are short-lead from OEM stock or scheduled production.'}`,
    },
  ]
}

function makeProduct(g: Input): ProductImportPayload {
  return {
    sku: g.sku,
    title: g.title,
    brandSlug: g.brandSlug,
    categorySlug: g.categorySlug,
    specTemplateSlug: 'metallic-hose-spec',
    status: 'active',
    unitOfMeasure: 'metre',
    listPriceCurrency: 'AED',
    stockQty: 0,
    leadTimeDays: g.leadTimeDays,
    countryOfOrigin: g.countryOfOrigin,
    descriptionShort: g.oneLiner.slice(0, 500),
    descriptionLong: buildHtml(g),
    specs: {
      hose_family: g.hoseFamily,
      construction_type: g.constructionType,
      oem_part_code: g.oemPartCode,
      braid_configuration: g.braidConfiguration,
      core_material: g.coreMaterial,
      braid_material: g.braidMaterial,
      end_fitting_material: g.endFittingMaterial,
      nominal_id_range: g.nominalIdRange,
      bend_radius_static_mm: g.bendRadiusStaticMm,
      bend_radius_dynamic_mm: g.bendRadiusDynamicMm,
      live_length_for_vibration_mm: g.liveLengthForVibrationMm,
      weight_kg_per_m: g.weightKgPerM,
      max_working_pressure_bar: g.maxWorkingPressureBar,
      min_burst_pressure_bar: g.minBurstPressureBar,
      safety_factor: g.safetyFactor,
      temp_min_c: g.tempMinC,
      temp_max_c: g.tempMaxC,
      iso_10380_class: g.iso10380Class,
      ped_module: g.pedModule,
      asme_compliance: g.asmeCompliance,
      nace_mr0175: g.naceMr0175,
      cga_ul_chlorine_certs: g.cgaUlChlorineCerts,
    },
    faqs: buildFaqs(g),
    seoTitle: `${g.title} | Indus Hydraulics`.slice(0, 200),
    seoDescription: g.oneLiner.slice(0, 500),
    focusKeyword: `${g.subType.toLowerCase()} metallic hose`.slice(0, 120),
  }
}

const PRODUCTS: Input[] = [
  // ── HP Cores (9) ────────────────────────────────────────────────────────
  {
    sku: 'IH-MH-THORBURN-S98Z-321',
    title: 'Thorburn S98Z — Ultra HP Fully Compressed Annular, Type 321 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Ultra HP fully compressed annular (Type 321)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'S98Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 321 SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard; high-pressure-rated welded fittings',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 600,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.73,
    maxWorkingPressureBar: 414,
    minBurstPressureBar: 1656,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.1, B31.3, Section VIII Div 1',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn S98Z Type 321 ultra-HP fully-compressed annular hose with double SS304 braid. Working pressure to 414 bar (6,000 psi). DN 6 to DN 100. Ultra-HP cryogenic loading and high-pressure steam.',
    applications: ['Cryogenic truck loading / unloading (HP)', 'Ultra-HP steam transfer', 'High-pressure power-pack connectors', 'HP frac iron specialty service'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-THORBURN-S98Z-316L',
    title: 'Thorburn S98Z — Ultra HP Fully Compressed Annular, Type 316L SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Ultra HP fully compressed annular (Type 316L)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'S98Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 316L SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard; HP welded fittings',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 600,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.73,
    maxWorkingPressureBar: 414,
    minBurstPressureBar: 1656,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.1, B31.3, Section VIII Div 1',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn S98Z Type 316L ultra-HP fully-compressed annular hose. Same 414 bar rating as the 321 variant — chloride-resistant chemistry. DN 6 to DN 100.',
    applications: ['HP chloride-rich process plant', 'Sour-gas HP processing', 'HP marine systems', 'Sea-water HP injection'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-THORBURN-S99Z-321-NUCLEAR',
    title: 'Thorburn S99Z — HP Fully Compressed Annular, Type 321 SS, Nuclear CRN-Rated',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'HP fully compressed annular nuclear-grade (Type 321)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'S99Z',
    braidConfiguration: 'Triple Braid',
    coreMaterial: 'Type 321 SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: 'Nuclear-grade SA240 T-321 SS — CRN-monogrammed',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 110,
    bendRadiusDynamicMm: 650,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.95,
    maxWorkingPressureBar: 414,
    minBurstPressureBar: 1656,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME Section III Class 1 NPT, ASME B31.1, B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA N299.1, CSA N285.0, CRN-monogrammed',
    oneLiner: 'Thorburn S99Z Type 321 nuclear CRN-rated HP fully compressed annular hose. Triple SS304 braid. 414 bar rating. ASME Section III Class 1 NPT. For nuclear power plant applications.',
    applications: ['Nuclear power plant primary loops', 'CRN-monogrammed nuclear systems', 'Nuclear-grade HP process', 'ASME Section III Class 1 service'],
    leadTimeDays: 112,
  },
  {
    sku: 'IH-MH-THORBURN-S99Z-316L-NUCLEAR',
    title: 'Thorburn S99Z — HP Fully Compressed Annular, Type 316L SS, Nuclear CRN-Rated',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'HP fully compressed annular nuclear-grade (Type 316L)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'S99Z',
    braidConfiguration: 'Triple Braid',
    coreMaterial: 'Type 316L SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: 'Nuclear-grade SA240 T-316L SS — CRN-monogrammed',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 110,
    bendRadiusDynamicMm: 650,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.95,
    maxWorkingPressureBar: 414,
    minBurstPressureBar: 1656,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME Section III Class 1 NPT, ASME B31.1, B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA N299.1, CSA N285.0, CRN-monogrammed',
    oneLiner: 'Thorburn S99Z Type 316L nuclear CRN-rated HP fully compressed annular hose. L-grade chemistry for chloride-rich nuclear-coolant environments.',
    applications: ['Nuclear secondary loops (chloride-rich)', 'CRN-monogrammed coolant systems', 'Sour-gas nuclear-rated process', 'Marine-nuclear adjacent service'],
    leadTimeDays: 112,
  },
  {
    sku: 'IH-MH-THORBURN-S50HD-321',
    title: 'Thorburn S50HD — Ultra HP Compressed Helical, Type 321 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Ultra HP compressed helical (Type 321 with 321 braid)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Helical Corrugated',
    oemPartCode: 'S50HD',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 321 SS',
    braidMaterial: 'Type 316 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 25 (1") to DN 150 (6")',
    bendRadiusStaticMm: 200,
    bendRadiusDynamicMm: 800,
    liveLengthForVibrationMm: 300,
    weightKgPerM: 1.2,
    maxWorkingPressureBar: 350,
    minBurstPressureBar: 1400,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.1, B31.3, Section VIII Div 1',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn S50HD Type 321 ultra-HP compressed helical hose with double Type 316 SS matched braid. Closed-pitch helical for HP service requiring vibration absorption.',
    applications: ['HP vibration-absorbing connectors', 'HP rotating equipment', 'HP cycling service', 'HP marine systems'],
    leadTimeDays: 84,
  },
  {
    sku: 'IH-MH-THORBURN-S50HD-316L',
    title: 'Thorburn S50HD — Ultra HP Compressed Helical, Type 316L SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Ultra HP compressed helical (Type 316L)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Helical Corrugated',
    oemPartCode: 'S50HD',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 316L SS',
    braidMaterial: 'Type 316 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 25 (1") to DN 150 (6")',
    bendRadiusStaticMm: 200,
    bendRadiusDynamicMm: 800,
    liveLengthForVibrationMm: 300,
    weightKgPerM: 1.2,
    maxWorkingPressureBar: 350,
    minBurstPressureBar: 1400,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.1, B31.3, Section VIII Div 1',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn S50HD Type 316L ultra-HP compressed helical hose. Chloride-resistant L-grade for HP corrosive vibration-absorbing service.',
    applications: ['HP corrosive cycling service', 'Sour-gas HP rotating equipment', 'HP chloride-rich vibration absorption', 'Marine HP rotating systems'],
    leadTimeDays: 84,
  },
  {
    sku: 'IH-MH-THORBURN-S69-321',
    title: 'Thorburn S69 — Closed-Pitch Omega Annular, Type 321 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Closed-pitch Omega annular (Type 321)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'S69',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Type 321 SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 80,
    bendRadiusDynamicMm: 305,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.5,
    maxWorkingPressureBar: 230,
    minBurstPressureBar: 920,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.1, B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn S69 Type 321 closed-pitch Omega-shaped annular hose. Higher pressure rating than standard annular at the same bore. DN 6 to DN 100, 230 bar working.',
    applications: ['HP service in tight envelopes', 'High-cycle HP rotating equipment', 'HP steam at limited bend radius', 'HP frac iron specialty service'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-HOSE-MASTER-STRESSTITE',
    title: 'Hose Master Stresstite HP Annular Hose',
    brandSlug: 'hose-master',
    countryOfOrigin: 'USA',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Stresstite HP annular (Hose Master)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'STRESSTITE',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 321 SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 6 (1/4") to DN 100 (4")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 600,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.75,
    maxWorkingPressureBar: 380,
    minBurstPressureBar: 1520,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'ASME B31.3, Section VIII Div 1',
    naceMr0175: true,
    cgaUlChlorineCerts: '',
    oneLiner: 'Hose Master Stresstite HP fully-compressed annular hose. US-market HP alternative — same fully-compressed corrugation methodology, North American supply chain.',
    applications: ['North American HP cryogenic loading', 'US HP steam transfer', 'US HP power generation', 'US HP frac iron specialty'],
    leadTimeDays: 56,
  },
  {
    sku: 'IH-MH-SENIOR-FLEX-PATHWAY-HP',
    title: 'Senior Flexonics Pathway HP Annular Hose',
    brandSlug: 'senior-flexonics',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'metallic-high-pressure-hoses',
    subType: 'Pathway HP annular (Senior Flexonics)',
    hoseFamily: 'High-Pressure Metallic',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'PATHWAY-HP',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 316L SS',
    braidMaterial: 'Type 316L SS',
    endFittingMaterial: '316L SS standard; matched-alloy fittings on request',
    nominalIdRange: 'DN 10 (3/8") to DN 100 (4")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 550,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.78,
    maxWorkingPressureBar: 350,
    minBurstPressureBar: 1400,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 650,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'EN 13480, ASME B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: 'TÜV / CE marking',
    oneLiner: 'Senior Flexonics Pathway HP annular hose with matched 316L SS double braid. European-engineered HP alternative with PSL 3 monogrammed certification.',
    applications: ['European HP chemical / petrochem', 'EU HP power generation', 'EU HP refinery service', 'EU HP marine systems'],
    leadTimeDays: 70,
  },
  // ── Specialty Cores / Fire Protection (11) ─────────────────────────────
  {
    sku: 'IH-MH-THORBURN-LS-304SS',
    title: 'Thorburn LS Series — Lock Section, 304 Stainless Steel',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Interlocking Lock-Section core (304 SS)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'TFS4',
    braidConfiguration: 'N/A',
    coreMaterial: 'Type 304 SS',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 25 (1") to DN 200 (8")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 0,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 1.5,
    maxWorkingPressureBar: 35,
    minBurstPressureBar: 140,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: 'ASME B31.3 (where pressure-rated)',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn LS Series interlocking Lock-Section core in 304 SS. Mechanically-locked rings prevent axial separation under pressure or impact. For service where pull-through resistance is critical.',
    applications: ['Bulk-material handling (vacuum / suction)', 'Vibration-absorbing connectors with pull-through risk', 'Industrial dust collection lines', 'High-impact mechanical service'],
    leadTimeDays: 35,
  },
  {
    sku: 'IH-MH-THORBURN-LS-CS',
    title: 'Thorburn LS Series — Lock Section, Carbon Steel',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Interlocking Lock-Section core (Carbon Steel)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'LS-CS',
    braidConfiguration: 'N/A',
    coreMaterial: 'Other',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Carbon steel A105N',
    nominalIdRange: 'DN 25 (1") to DN 200 (8")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 0,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 1.4,
    maxWorkingPressureBar: 25,
    minBurstPressureBar: 100,
    safetyFactor: 4,
    tempMinC: -50,
    tempMaxC: 400,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: 'ASME B31.3 (where pressure-rated)',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn LS Series Lock-Section core in carbon steel. Cost-effective interlocking core for non-corrosive bulk-handling service.',
    applications: ['Cost-managed bulk handling', 'Industrial dust collection (non-corrosive)', 'Vibration-absorbing CS connectors', 'Low-temperature mechanical service'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-MH-THORBURN-AF-304SS',
    title: 'Thorburn AF Series — Ball-Joint Armor-Flex Hose Guard, 304 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Ball-joint Armor-Flex outer hose guard (304 SS)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'AFS4',
    braidConfiguration: 'N/A',
    coreMaterial: 'Type 304 SS',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: '304 SS welded ball-joint segments',
    nominalIdRange: 'Fits DN 25 (1") to DN 200 (8") host hoses',
    bendRadiusStaticMm: 200,
    bendRadiusDynamicMm: 400,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 2.5,
    maxWorkingPressureBar: 0,
    minBurstPressureBar: 0,
    safetyFactor: 0,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: '',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn AF Series ball-joint Armor-Flex hose guard in 304 SS. Articulated outer protection for metallic and process hoses against impact, abrasion, and physical wear.',
    applications: ['Outer protection for impact / abrasion', 'Articulated robot / equipment connectors', 'High-traffic industrial walkways', 'Marine / offshore deck hoses'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-MH-THORBURN-AF-CS',
    title: 'Thorburn AF Series — Ball-Joint Armor-Flex Hose Guard, Carbon Steel',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Ball-joint Armor-Flex outer hose guard (Carbon Steel)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'AF',
    braidConfiguration: 'N/A',
    coreMaterial: 'Other',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Carbon steel welded ball-joint segments',
    nominalIdRange: 'Fits DN 25 (1") to DN 200 (8") host hoses',
    bendRadiusStaticMm: 200,
    bendRadiusDynamicMm: 400,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 2.4,
    maxWorkingPressureBar: 0,
    minBurstPressureBar: 0,
    safetyFactor: 0,
    tempMinC: -50,
    tempMaxC: 400,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: '',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn AF Series ball-joint Armor-Flex hose guard in carbon steel. Cost-effective articulated protection for non-corrosive industrial service.',
    applications: ['Cost-managed industrial protection', 'Non-corrosive impact / abrasion service', 'Indoor industrial walkways', 'CS-compatible mechanical environments'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-MH-THORBURN-SFM-S4',
    title: 'Thorburn SFM Series — Smooth-Flex, Type 304 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Smooth-Flex non-corrugated alternative (304 SS)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Smooth-Bore',
    oemPartCode: 'SFM-S4',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Type 304 SS',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard; female camlock / NPT / sanitary',
    nominalIdRange: 'DN 50 (2") to DN 100 (4")',
    bendRadiusStaticMm: 250,
    bendRadiusDynamicMm: 500,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 1.6,
    maxWorkingPressureBar: 25,
    minBurstPressureBar: 100,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'N/A',
    pedModule: 'Module A',
    asmeCompliance: 'ASME B31.3',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn SFM Series Smooth-Flex hose in 304 SS — smooth-bore alternative to corrugated metallic. Lower turbulence, easier to clean, but less flexible than corrugated.',
    applications: ['Sanitary process lines (food / pharma)', 'Slurry transfer (smooth-bore reduces turbulence)', 'Steam-cleanable utility lines', 'High-purity process'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-MH-THORBURN-SFM-S6',
    title: 'Thorburn SFM Series — Smooth-Flex, Type 316 SS',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Smooth-Flex non-corrugated alternative (316 SS)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Smooth-Bore',
    oemPartCode: 'SFM-S6',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Type 304 SS',
    braidMaterial: 'Type 316 SS',
    endFittingMaterial: '316L SS standard; sanitary tri-clamp / female camlock',
    nominalIdRange: 'DN 50 (2") to DN 100 (4")',
    bendRadiusStaticMm: 250,
    bendRadiusDynamicMm: 500,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 1.6,
    maxWorkingPressureBar: 25,
    minBurstPressureBar: 100,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'N/A',
    pedModule: 'Module A',
    asmeCompliance: 'ASME B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn SFM Series Smooth-Flex hose in 316 SS — chloride-resistant smooth-bore for sanitary and food / pharma service.',
    applications: ['Pharmaceutical sanitary process', 'Food-grade transfer (FDA-compliant trim)', 'Marine smooth-bore service', 'Chloride-rich high-purity process'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-MH-THORBURN-SFM-HDG',
    title: 'Thorburn SFM Series — Smooth-Flex, Hot-Dip Galvanized Carbon Steel',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Smooth-Flex non-corrugated (Hot-Dip Galvanized CS)',
    hoseFamily: 'Specialty Metallic Core',
    constructionType: 'Smooth-Bore',
    oemPartCode: 'SFM-HDG',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Other',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: 'Hot-dip galvanized carbon steel; CS or SS fittings',
    nominalIdRange: 'DN 50 (2") to DN 100 (4")',
    bendRadiusStaticMm: 250,
    bendRadiusDynamicMm: 500,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 1.5,
    maxWorkingPressureBar: 20,
    minBurstPressureBar: 80,
    safetyFactor: 4,
    tempMinC: -50,
    tempMaxC: 400,
    iso10380Class: 'N/A',
    pedModule: 'Module A',
    asmeCompliance: 'ASME B31.3',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn SFM Series Smooth-Flex in hot-dip galvanized carbon steel. Cost-effective smooth-bore for utility / non-corrosive industrial service.',
    applications: ['Cost-managed utility transfer', 'Industrial water service', 'Non-corrosive bulk transfer', 'Outdoor utility lines (galvanized for corrosion resistance)'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-MH-THORBURN-FJ72-FIRE-JACKET',
    title: 'Thorburn FJ72 Fry-Sil Fire Jacket',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Silica-fabric fire-survivability jacket',
    hoseFamily: 'Fire Protection',
    constructionType: 'Smooth-Bore',
    oemPartCode: 'FJ72',
    braidConfiguration: 'N/A',
    coreMaterial: 'Other',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Stitched / Velcro closure; no end fittings',
    nominalIdRange: 'Fits DN 25 (1") to DN 200 (8") host hoses',
    bendRadiusStaticMm: 0,
    bendRadiusDynamicMm: 0,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 0.4,
    maxWorkingPressureBar: 0,
    minBurstPressureBar: 0,
    safetyFactor: 0,
    tempMinC: -50,
    tempMaxC: 1093,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: '',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn FJ72 Fry-Sil silica-fabric fire-survivability jacket. Wraps around metallic and industrial hoses to maintain integrity through fire-exposure events. Continuous service to +1093°C.',
    applications: ['Fire-rated process plant lines', 'Hydrocarbon transfer with fire-safety regulation', 'Insulated and fire-rated jacketed assemblies', 'Power-generation high-temp piping'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-MH-THORBURN-FJ73-FIRE-TAPE',
    title: 'Thorburn FJ73 Fry-Sil Fire Tape',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Silica-fabric fire-survivability tape',
    hoseFamily: 'Fire Protection',
    constructionType: 'Smooth-Bore',
    oemPartCode: 'FJ73',
    braidConfiguration: 'N/A',
    coreMaterial: 'Other',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Spiral-wound application; no end fittings',
    nominalIdRange: 'Fits any host hose / pipe ≤ DN 200 (8")',
    bendRadiusStaticMm: 0,
    bendRadiusDynamicMm: 0,
    liveLengthForVibrationMm: 0,
    weightKgPerM: 0.2,
    maxWorkingPressureBar: 0,
    minBurstPressureBar: 0,
    safetyFactor: 0,
    tempMinC: -50,
    tempMaxC: 1093,
    iso10380Class: 'N/A',
    pedModule: 'None',
    asmeCompliance: '',
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn FJ73 Fry-Sil silica-fabric fire tape. Spiral-wound around hoses or piping for retrofit fire-survivability. Continuous service to +1093°C.',
    applications: ['Retrofit fire protection on existing hoses', 'Field-applied fire-rating upgrades', 'Insulation patching at fitting joints', 'Custom-shaped fire-protection wraps'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-MH-SENIOR-FLEX-BARTLETT-FIRESAFE',
    title: 'Senior Flexonics Bartlett Fire-Safe Hose Assembly',
    brandSlug: 'senior-flexonics',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'metallic-fire-protection-hoses',
    subType: 'Bartlett fire-safe certified metallic hose (Senior Flexonics)',
    hoseFamily: 'Fire Protection',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'BARTLETT-FIRESAFE',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Type 316L SS',
    braidMaterial: 'Type 316L SS',
    endFittingMaterial: '316L SS standard with fire-test-certified flange seals',
    nominalIdRange: 'DN 13 (1/2") to DN 100 (4")',
    bendRadiusStaticMm: 100,
    bendRadiusDynamicMm: 500,
    liveLengthForVibrationMm: 200,
    weightKgPerM: 0.85,
    maxWorkingPressureBar: 200,
    minBurstPressureBar: 800,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 815,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'EN 13480, ASME B31.3',
    naceMr0175: true,
    cgaUlChlorineCerts: 'API 6FA fire-test certified',
    oneLiner: 'Senior Flexonics Bartlett fire-safe certified metallic hose assembly. API 6FA fire-test certified for hydrocarbon installations requiring fire-survivability rating.',
    applications: ['Fire-safe rated hydrocarbon transfer', 'API 6FA-required oil & gas plant', 'Refinery fire-survivability lines', 'EU fire-rated petrochemical service'],
    leadTimeDays: 84,
  },
]

const batch: ImportBatch = {
  meta: {
    id: '2026-05-08-metallic-hoses-2-hp-specialty-cores',
    description:
      'Metallic Hoses Batch 2 — 20 products: 9 HP cores (S98Z, S99Z nuclear, S50HD, S69, plus Hose Master Stresstite and Senior Flexonics Pathway HP) + 11 specialty cores / fire protection (Lock Section, Armor-Flex, Smooth-Flex, Fire Jacket, Fire Tape, Senior Flexonics Bartlett Fire-Safe).',
  },
  brands: [],
  categories: [],
  specTemplates: [],
  products: PRODUCTS.map(makeProduct),
}

export default batch
