/**
 * Flow Iron & Wellhead — Batch 0 (framework + Adapters + Fittings + API Flanges)
 * 2026-05-08
 *
 * First batch in the Flow Iron & Wellhead initiative. Establishes:
 *   - 1 new OEM brand record: NOV (National Oilwell Varco). Halliburton and
 *     Forum Energy Technologies are deferred to later batches alongside
 *     their first products (manifolds / surface test trees).
 *   - 1 new spec template (flow-iron-spec, 16 fields, position 20) — covers
 *     the Adapters, Fittings, Flow Line, and Manifold product space via a
 *     `flow_iron_type` discriminator. Wellhead and Surface Test Tree get
 *     their own templates in Batch 2.
 *   - 1 new top-level category (flow-iron-wellhead, position 10) with 3
 *     sub-categories (flow-iron-adapters, flow-iron-fittings, flow-iron-flanges-api).
 *   - 1 new megamenu column "Flow Iron & Wellhead" at position 10, with one
 *     sub-section "Flow Iron" and 3 leaves (Adapters, Fittings, API Flanges).
 *   - 50 consolidated PDPs covering 1,000+ underlying BIF SKU permutations.
 *     Each PDP is a (type × figure-class × configuration × service) family,
 *     listing the available sizes in description and FAQs. SEO is OEM-keyworded
 *     across FMC, Cameron, SPM, Anson, Stream-Flo, NOV, and Indus.
 *
 * Pricing: RFQ-only (listPrice=null), AED. Status: active.
 *
 * Run with:
 *   pnpm --filter @indus/db db:import src/imports/2026-05-08-flow-iron-wellhead-0.ts --dry-run
 *   pnpm --filter @indus/db db:import src/imports/2026-05-08-flow-iron-wellhead-0.ts
 */
import type {
  BrandPayload,
  CategoryPayload,
  FaqEntry,
  ImportBatch,
  ProductImportPayload,
  SpecTemplatePayload,
} from '../import/types'

// ── Helpers ───────────────────────────────────────────────────────────────

function escape(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function fmtPsi(psi: number): string {
  return psi.toLocaleString('en-US') + ' psi'
}

// ── Brand records (only the new ones; existing ones reused by slug) ──────

const BRANDS: BrandPayload[] = [
  {
    slug: 'nov',
    name: 'National Oilwell Varco',
    country: 'USA',
    description:
      'National Oilwell Varco (NOV) supplies wellhead systems, frac iron, manifold skids, choke manifolds, blast joints, and integrated pressure-control packages for upstream oil and gas. Houston-headquartered global OEM.',
    isAuthorizedDistributor: false,
    isPublished: true,
    seoTitle: 'NOV Flow Iron, Manifolds & Wellhead Equipment | Indus Hydraulics',
    seoDescription:
      'National Oilwell Varco (NOV) flow iron, manifold skids, choke manifolds, and wellhead systems supplied by Indus Hydraulics in the UAE. AED pricing, RFQ on request.',
  },
]

// ── Spec template ─────────────────────────────────────────────────────────

const FLOW_IRON_SPEC: SpecTemplatePayload = {
  slug: 'flow-iron-spec',
  name: 'Flow Iron',
  description:
    'Spec template for frac flow iron, hammer unions, integral fittings, adapters, API flanges, swivel joints, pup joints, manifolds, and pressure-pumping iron. Covers WECO, Chiksan, and API 6A / 16C connection families across 1K to 20K psi.',
  position: 20,
  fields: [
    {
      key: 'flow_iron_type',
      label: 'Flow Iron Type',
      dataType: 'select',
      options: [
        'Crossover Union',
        'Hammer Union',
        'Adapter Flange (Union × Flange)',
        'Double Studded Adapter',
        'Double Flange Adapter',
        'Cross',
        'Tee',
        'Elbow',
        'Wye — Straight',
        'Wye — Lateral',
        'Blanking Cap',
        'API Hub & Clamp',
        'Studded Fitting',
        'Ring Joint Gasket',
        'BSL Bolting Set',
        'Blind Flange',
        'Companion Flange',
        'Instrument Flange',
        'Weld-Neck Flange',
        'Pup Joint',
        'Swivel Joint',
        'Spacer Spool',
        'Hose Loop (C&C)',
        'Blast Joint',
        'Data Header',
        'Choke Manifold',
        'Diverter Manifold',
        'Multi-Well Manifold',
        'Manifold Skid',
        'Flow Line Package',
      ],
      group: 'Identification',
      isRequired: true,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 0,
    },
    {
      key: 'figure_class',
      label: 'Figure / Pressure Series',
      dataType: 'select',
      options: [
        '100',
        '200',
        '206',
        '400',
        '602',
        '1002',
        '1502',
        '2002',
        '2K',
        '3K',
        '5K',
        '10K',
        '15K',
        '20K',
        'ANSI 150',
        'ANSI 300',
        'ANSI 600',
        'ANSI 900',
        'ANSI 1500',
        'ANSI 2500',
        'N/A',
      ],
      helpText:
        'WECO frac-iron series number (100/200/206/400/602/1002/1502/2002) for hammer-union products, or API 6A pressure class (5K/10K/15K/20K) for flanged products.',
      group: 'Identification',
      isRequired: false,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 1,
    },
    {
      key: 'working_pressure_psi',
      label: 'Working Pressure',
      unit: 'psi',
      dataType: 'number',
      group: 'Performance',
      isRequired: true,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 2,
    },
    {
      key: 'pressure_class',
      label: 'Pressure Class',
      dataType: 'select',
      options: [
        '1K',
        '2K',
        '3K',
        '4K',
        '5K',
        '6K',
        '10K',
        '15K',
        '20K',
        'ANSI 150',
        'ANSI 300',
        'ANSI 600',
        'ANSI 900',
        'ANSI 1500',
        'ANSI 2500',
      ],
      group: 'Performance',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: true,
      position: 3,
    },
    {
      key: 'service_class',
      label: 'Service Class',
      dataType: 'select',
      options: ['Standard', 'Sour (NACE MR0175)', 'High Temperature', 'Low Temperature'],
      group: 'Performance',
      isRequired: true,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 4,
    },
    {
      key: 'configuration',
      label: 'Configuration',
      dataType: 'text',
      helpText: 'End-connection arrangement, e.g. "M×F", "F×F", "M×M×M×F (3M / 1F)", "Reducer 4 in × 3 in".',
      group: 'Identification',
      isRequired: false,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 5,
    },
    {
      key: 'end_connection_a',
      label: 'End Connection (A)',
      dataType: 'text',
      group: 'Dimensions',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 6,
    },
    {
      key: 'end_connection_b',
      label: 'End Connection (B)',
      dataType: 'text',
      group: 'Dimensions',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 7,
    },
    {
      key: 'end_connection_extra',
      label: 'Additional Ports / Taps',
      dataType: 'text',
      helpText:
        'Auxiliary connections, e.g. "1/2 in NPT instrument tap", "9/16 in Autoclave", "S40 BW".',
      group: 'Dimensions',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 8,
    },
    {
      key: 'available_sizes',
      label: 'Available Sizes',
      dataType: 'text',
      helpText:
        'Stock or short-lead nominal sizes, comma-separated. E.g. "2 in, 3 in, 4 in" or "2-1/16 in, 3-1/16 in".',
      group: 'Dimensions',
      isRequired: true,
      isKeyFeature: true,
      isQuickSpec: true,
      position: 9,
    },
    {
      key: 'bore_id',
      label: 'Bore / ID',
      dataType: 'text',
      group: 'Dimensions',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 10,
    },
    {
      key: 'length_in',
      label: 'Length',
      unit: 'in',
      dataType: 'text',
      helpText: 'Used for pup joints, spacer spools, blast joints — overall make-up length.',
      group: 'Dimensions',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 11,
    },
    {
      key: 'material_construction',
      label: 'Material',
      dataType: 'text',
      group: 'Construction',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 12,
    },
    {
      key: 'api_spec',
      label: 'API / Industry Specification',
      dataType: 'select',
      options: [
        'API 6A',
        'API 6BX',
        'API 16C',
        'API 17D',
        'ASME B16.5',
        'ASME B16.34',
        'ASME B16.25 (BW)',
        'NACE MR0175',
        'Other (frac-iron lineage)',
        'N/A',
      ],
      group: 'Compliance',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 13,
    },
    {
      key: 'material_class',
      label: 'Material Class (API 6A)',
      dataType: 'select',
      options: ['AA', 'BB', 'CC', 'DD', 'EE', 'FF', 'HH', 'N/A'],
      helpText:
        'API 6A material class. AA-CC for general/standard service, DD-FF for sour service, HH for severe sour service.',
      group: 'Compliance',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 14,
    },
    {
      key: 'temperature_rating',
      label: 'Temperature Rating',
      dataType: 'text',
      group: 'Performance',
      isRequired: false,
      isKeyFeature: false,
      isQuickSpec: false,
      position: 15,
    },
  ],
}

// ── Categories ────────────────────────────────────────────────────────────

const CATEGORIES: CategoryPayload[] = [
  {
    slug: 'flow-iron-wellhead',
    name: 'Flow Iron & Wellhead',
    parentSlug: null,
    shortDescription:
      'WECO frac iron, integral fittings, hammer unions, swivel joints, manifolds, API 6A flanges, wellhead systems, and surface test trees for upstream oil and gas. 1K to 20K psi, sour and standard service. FMC / Cameron / SPM / Anson / NOV / Stream-Flo / Indus.',
    position: 10,
    isPublished: true,
    defaultSpecTemplateSlug: 'flow-iron-spec',
    seoTitle: 'Flow Iron & Wellhead — Frac Iron, Manifolds, Wellhead | Indus Hydraulics',
    seoDescription:
      'WECO frac iron, hammer unions, integral fittings, swivel joints, choke manifolds, API 6A flanges, wellheads and surface test trees. 1K-20K psi, sour and standard. FMC, Cameron, SPM, Anson, NOV, Stream-Flo. AED pricing, RFQ.',
  },
  {
    slug: 'flow-iron-adapters',
    name: 'Adapters',
    parentSlug: 'flow-iron-wellhead',
    shortDescription:
      'Frac-iron crossover unions, WECO adapter flanges (union × API flange), and double studded adapters. 1K to 15K psi WECO and API 6A 5K to 15K classes. Sour and standard service.',
    position: 0,
    isPublished: true,
    defaultSpecTemplateSlug: 'flow-iron-spec',
    seoTitle: 'Flow Iron Adapters — Crossovers, WECO Flange, Studded | Indus Hydraulics',
    seoDescription:
      'Crossover unions, WECO adapter flanges, double studded and double flange adapters. 1502/1002/602/206 series, API 6A 5K/10K/15K. FMC / Cameron / SPM / Anson. Sour and standard service. AED pricing, RFQ.',
  },
  {
    slug: 'flow-iron-fittings',
    name: 'Fittings',
    parentSlug: 'flow-iron-wellhead',
    shortDescription:
      'Hammer unions, crosses, tees, elbows, wyes, blanking caps, API hub-and-clamp connectors, studded fittings, and BSL bolting / ring-joint gaskets. WECO 1502 / 1002 / 602 / 206 / 100 series and API 6A 5K-15K classes.',
    position: 1,
    isPublished: true,
    defaultSpecTemplateSlug: 'flow-iron-spec',
    seoTitle: 'Flow Iron Fittings — Hammer Unions, Crosses, Tees, Elbows | Indus Hydraulics',
    seoDescription:
      'WECO frac-iron fittings — hammer unions, crosses, tees, elbows, wyes, blanking caps, hubs, clamps, gaskets, studs. 1502/1002/602/206/100 series, 1K-15K psi, sour and standard. FMC, SPM, Anson, Cameron. AED, RFQ.',
  },
  {
    slug: 'flow-iron-flanges-api',
    name: 'API Flanges',
    parentSlug: 'flow-iron-wellhead',
    shortDescription:
      'API 6BX blind, companion, weld-neck, and instrument flanges in 5K, 10K, 15K, and 20K pressure classes. Standard and sour service. Cameron, FMC, NOV, Stream-Flo, and Indus stock and short-lead.',
    position: 2,
    isPublished: true,
    defaultSpecTemplateSlug: 'flow-iron-spec',
    seoTitle: 'API 6BX Flanges — Blind, Companion, Weld-Neck | Indus Hydraulics',
    seoDescription:
      'API 6BX blind, companion, weld-neck, and instrument flanges. 5K / 10K / 15K / 20K classes. 2-1/16 in to 7-1/16 in bore. Cameron, FMC, NOV, Stream-Flo. Sour and standard service. AED pricing, RFQ on request.',
  },
]

// ── Per-product input shape ───────────────────────────────────────────────

type FlowIronInput = {
  sku: string
  title: string
  brandSlug: string
  countryOfOrigin: string
  categorySlug: string
  flowIronType: string
  figureClass: string
  workingPressurePsi: number
  pressureClass: string
  serviceClass: 'Standard' | 'Sour (NACE MR0175)'
  configuration: string
  endConnectionA: string
  endConnectionB: string
  endConnectionExtra: string
  availableSizes: string
  boreId: string
  lengthIn: string
  materialConstruction: string
  apiSpec: string
  materialClass: string
  temperatureRating: string
  oneLiner: string
  applications: string[]
  oemKeywords: string[]
  leadTimeDays: number
}

// ── HTML description builder ──────────────────────────────────────────────

function buildHtml(g: FlowIronInput): string {
  const sourLine =
    g.serviceClass === 'Sour (NACE MR0175)'
      ? 'NACE MR0175 / ISO 15156 sour-service compliant — H₂S-rated body and trim with hardness controlled per the standard.'
      : 'Standard service rated for clean hydrocarbon, completion fluid, and water-cut streams.'
  const apiLine =
    g.apiSpec === 'Other (frac-iron lineage)' || g.apiSpec === 'N/A'
      ? 'Manufactured to recognised oilfield frac-iron design standards — pressure-class methodology and hydrostatic testing aligned with API 6A.'
      : `Manufactured to ${escape(g.apiSpec)}${g.materialClass !== 'N/A' ? `, material class ${escape(g.materialClass)}` : ''}.`
  const apps = g.applications.map((a) => `<li>${escape(a)}</li>`).join('')
  const oemKw = g.oemKeywords.map((k) => `<li>${escape(k)}</li>`).join('')

  return `<p>The <strong>${escape(g.title)}</strong> is a ${escape(g.flowIronType.toLowerCase())} ${escape(g.configuration ? '(' + g.configuration + ') ' : '')}rated for ${escape(fmtPsi(g.workingPressurePsi))} working pressure in ${escape(g.serviceClass.toLowerCase())} service. ${escape(sourLine)}</p>
<h3>Construction</h3>
<ul>
<li>Type: ${escape(g.flowIronType)}</li>
<li>Series / class: ${escape(g.figureClass)} (${escape(g.pressureClass)})</li>
<li>Configuration: ${escape(g.configuration || '—')}</li>
<li>End A: ${escape(g.endConnectionA || '—')}</li>
${g.endConnectionB ? `<li>End B: ${escape(g.endConnectionB)}</li>` : ''}
${g.endConnectionExtra ? `<li>Auxiliary: ${escape(g.endConnectionExtra)}</li>` : ''}
${g.boreId ? `<li>Bore / ID: ${escape(g.boreId)}</li>` : ''}
${g.lengthIn ? `<li>Length: ${escape(g.lengthIn)}</li>` : ''}
<li>Material: ${escape(g.materialConstruction)}</li>
<li>Temperature rating: ${escape(g.temperatureRating)}</li>
</ul>
<h3>Available sizes</h3>
<p>This product family covers the following stock or short-lead nominal sizes: <strong>${escape(g.availableSizes)}</strong>. Other sizes within the same series and pressure class can be sourced from the OEM mill on a build-to-order basis (8–14 weeks lead). Indus quotes a firm size, pressure class, configuration, and service-class match against your inquiry data sheet — call or RFQ with the line specification and we will return a complete matched bill of materials.</p>
<h3>Performance</h3>
<p>Working pressure ${escape(fmtPsi(g.workingPressurePsi))} (${escape(g.pressureClass)} class), ${escape(g.serviceClass.toLowerCase())} rated. ${escape(apiLine)} Hydrostatic test at 1.5× shell pressure on every unit. Mill test reports per EN 10204 3.1 / 3.2 supplied with each shipment.</p>
<h3>Applications</h3>
<ul>
${apps}
</ul>
<h3>OEM equivalents and compatibility</h3>
<p>This product is supplied as a recognised matched-pressure interchange for the following OEM standards and product lines (no implied authorised-distributor relationship — supplied by Indus Hydraulics):</p>
<ul>
${oemKw}
</ul>
<h3>Compliance</h3>
<ul>
<li>${escape(g.apiSpec === 'Other (frac-iron lineage)' || g.apiSpec === 'N/A' ? 'Recognised oilfield frac-iron design standards (frac-iron pressure-class lineage)' : g.apiSpec)}</li>
${g.materialClass !== 'N/A' ? `<li>Material class: ${escape(g.materialClass)}</li>` : ''}
${g.serviceClass === 'Sour (NACE MR0175)' ? '<li>NACE MR0175 / ISO 15156 (sour-service / H₂S)</li>' : ''}
<li>EN 10204 3.1 / 3.2 mill test reports</li>
<li>Hydrostatic test certificates per unit</li>
</ul>
<h3>How to order</h3>
<p>Confirm on your RFQ: (a) exact nominal size and bore ID, (b) line working pressure and pressure class, (c) end-connection style and gender on each port (M / F, NPT / BW / Integral / RTJ / RF), (d) service class — sour (NACE MR0175) or standard, (e) any additional ports or taps (1/2 in NPT instrument tap, 9/16 in Autoclave, etc.), and (f) required certifications beyond the standard MTR + hydrostatic. Indus quotes ex-Dubai with full traceability.</p>
<h3>Companion products</h3>
<p>Pair with matched-pressure hammer unions, swivel joints (Chiksan-style 50 / 100 / 200 series), pup joints, integral crosses / tees / elbows, plug valves, ball valves, and check valves of the same WECO figure class. For wellhead and frac-tree integration, also specify API 6A flanges, wellhead adapters, and ring-joint gaskets in the matched pressure class.</p>`
}

// ── FAQ generator ─────────────────────────────────────────────────────────

function buildFaqs(g: FlowIronInput): FaqEntry[] {
  const sourFaq =
    g.serviceClass === 'Sour (NACE MR0175)'
      ? 'Yes — this product is fully NACE MR0175 / ISO 15156 compliant for sour-service exposure (H₂S-bearing hydrocarbon streams). Body, trim, and any elastomers are selected to the NACE hardness and chemistry limits. Provide an inquiry data sheet listing H₂S partial pressure, temperature, and chloride content and we will confirm material suitability and material-class designation (typically DD, EE, or FF for sour).'
      : 'No — this is standard-service rated. For sour wells (H₂S partial pressure above NACE MR0175 thresholds), specify the sour-service variant of this size and pressure class on the RFQ. Sour variants typically run 8–10K psi where standard runs 15K (a deliberate downrate to stay within NACE hardness limits).'
  return [
    {
      q: 'What sizes are available in this product family?',
      a: `Stock or short-lead sizes: ${g.availableSizes}. The product page consolidates a family of sizes that share the same series, configuration, pressure class, and service class — confirm the exact size you need on the RFQ. Sizes outside the listed stock range can be sourced build-to-order at typical 8–14 week lead times depending on OEM build slots.`,
    },
    {
      q: 'What is the working pressure rating?',
      a: `${fmtPsi(g.workingPressurePsi)} working pressure, ${g.pressureClass} class. The unit is hydrotested at 1.5× shell-test pressure per the applicable specification. The working pressure is fixed by both the body design and the end connection — the union, flange, or weld rating is the limiting factor at the joint, so always specify matched-class connections on both sides.`,
    },
    {
      q: 'Is this product suitable for sour service (H₂S wells)?',
      a: sourFaq,
    },
    {
      q: 'What end connections does this product use?',
      a: `End A: ${g.endConnectionA || 'see configuration'}. ${g.endConnectionB ? 'End B: ' + g.endConnectionB + '. ' : ''}${g.endConnectionExtra ? 'Auxiliary: ' + g.endConnectionExtra + '. ' : ''}${g.figureClass.match(/^(100|200|206|400|602|1002|1502|2002)$/) ? 'These are WECO wing-union (hammer-union) connections, the standard for frac flow iron — the Female (F) half threads onto the Male (M) half via the hand-tight wing nut, then is hammered tight with a non-sparking sledge. Always match like-class on both sides of the joint — never mix a 1502 with a 1002 even if the threads appear similar.' : g.figureClass.match(/^(2K|3K|5K|10K|15K|20K)$/) ? 'These are API 6A / 6BX flanged ends — ring-joint gasket (RTJ) sealing on a BX-series ring groove. Studs and nuts to match the API 6BX bolting pattern (BSL stud-and-nut sets are sold separately).' : 'See the spec table for end-connection detail.'}`,
    },
    {
      q: 'What OEM brands and standards is this compatible with?',
      a: `This product is supplied as a recognised matched-pressure interchange for ${g.oemKeywords.join(', ')}. Indus is not an authorised distributor of these OEMs but every unit is engineered to be dimensionally and metallurgically interchangeable with the named OEM standard, with full mill test reports and hydrostatic certificates on file. For applications requiring an OEM-stamped unit, we can source genuine OEM product on a build-to-order basis — call us with the application detail.`,
    },
    {
      q: 'What materials and material class are used?',
      a: `Material: ${g.materialConstruction}. ${g.materialClass !== 'N/A' ? 'API 6A material class: ' + g.materialClass + ' (' + (g.materialClass.match(/^(DD|EE|FF|HH)$/) ? 'sour-service capable per NACE MR0175' : 'standard-service general use') + '). ' : ''}Higher material classes (Inconel-clad seal pockets, F22 / F51 wetted parts, NACE-compliant bolting) are available on request for severe sour, high-temperature, or chloride-rich service.`,
    },
    {
      q: 'What standards and certifications come with each unit?',
      a: `Each unit ships with: (a) ${g.apiSpec === 'Other (frac-iron lineage)' || g.apiSpec === 'N/A' ? 'recognised frac-iron design standards traceability' : g.apiSpec + ' design and manufacture compliance'}, (b) EN 10204 3.1 mill test report (3.2 on request), (c) hydrostatic test certificate at 1.5× shell pressure, ${g.serviceClass === 'Sour (NACE MR0175)' ? '(d) NACE MR0175 / ISO 15156 sour-service compliance certificate, ' : ''}and traceability stamps on the body. API monogram is available where the source mill holds the licence — flag this on the RFQ if it's a hard requirement.`,
    },
    {
      q: 'What is the lead time and how do I order?',
      a: `Common combinations are stocked or short-lead from our Dubai warehouse — typical lead time ${g.leadTimeDays} working days. Sour-service variants and unusual sizes / pressure classes ship 8–14 weeks ex-works depending on OEM build slots. RFQ with: (a) exact size, (b) pressure class and service, (c) end-connection style and gender on each port, (d) certification requirements, and (e) destination port. Indus quotes ex-Dubai with door-to-door logistics on request.`,
    },
  ]
}

// ── Translator ────────────────────────────────────────────────────────────

function makeProduct(g: FlowIronInput): ProductImportPayload {
  return {
    sku: g.sku,
    title: g.title,
    brandSlug: g.brandSlug,
    categorySlug: g.categorySlug,
    specTemplateSlug: 'flow-iron-spec',
    status: 'active',
    unitOfMeasure: 'each',
    listPriceCurrency: 'AED',
    stockQty: 0,
    leadTimeDays: g.leadTimeDays,
    countryOfOrigin: g.countryOfOrigin,
    descriptionShort: g.oneLiner.slice(0, 500),
    descriptionLong: buildHtml(g),
    specs: {
      flow_iron_type: g.flowIronType,
      figure_class: g.figureClass,
      working_pressure_psi: g.workingPressurePsi,
      pressure_class: g.pressureClass,
      service_class: g.serviceClass,
      configuration: g.configuration,
      end_connection_a: g.endConnectionA,
      end_connection_b: g.endConnectionB,
      end_connection_extra: g.endConnectionExtra,
      available_sizes: g.availableSizes,
      bore_id: g.boreId,
      length_in: g.lengthIn,
      material_construction: g.materialConstruction,
      api_spec: g.apiSpec,
      material_class: g.materialClass,
      temperature_rating: g.temperatureRating,
    },
    faqs: buildFaqs(g),
    seoTitle: `${g.title} | Indus Hydraulics`.slice(0, 200),
    seoDescription: g.oneLiner.slice(0, 500),
    focusKeyword: `${g.flowIronType.toLowerCase()} ${g.figureClass} ${g.pressureClass.toLowerCase()}${g.serviceClass === 'Sour (NACE MR0175)' ? ' sour' : ''}`.slice(0, 120),
  }
}

// ── Common defaults ───────────────────────────────────────────────────────

const STD_TEMP = '-20°F to 250°F (-29°C to 121°C)'
const SOUR_TEMP = '-20°F to 180°F (-29°C to 82°C)'
const STD_MAT = 'Forged alloy steel (4130/4140), tempered'
const SOUR_MAT = 'Forged alloy steel (4130) — NACE MR0175 hardness controlled'

// ── Product data ──────────────────────────────────────────────────────────

const PRODUCTS: FlowIronInput[] = [
  // ════════════════════════════════════════════════════════════════════════
  // ADAPTERS — Crossover Unions (10)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-XO-1502-MM-15K-STD-FMC',
    title: 'Crossover Union, 1502 Series M×M, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Male × Male',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: '1502 Male Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in',
    boreId: 'Same as nominal — full bore through body',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Male × Male crossover union, 15,000 psi standard-service rated. WECO / FMC interchange. Used to mate two male hammer-union ends — frac iron service trees, kill / circulation lines.',
    applications: [
      'Frac iron service trees (high-pressure pumping)',
      'Coiled-tubing kill and circulation lines',
      'Cement and acid stimulation manifolds',
      'Well-stimulation flow lines',
    ],
    oemKeywords: ['FMC WECO 1502', 'SPM 1502', 'Anson 1502', 'Forum Energy 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-1502-MF-15K-STD-FMC',
    title: 'Crossover Union, 1502 Series M×F, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Male × Female',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in',
    boreId: 'Same as nominal — full bore through body',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Male × Female crossover union, 15,000 psi standard-service rated. WECO / FMC interchange. The most common crossover configuration for joining hammer-union pup joints in frac iron.',
    applications: [
      'Frac iron service trees',
      'Pump-truck discharge lines',
      'Coiled-tubing surface equipment',
      'Cement and acid stimulation manifolds',
    ],
    oemKeywords: ['FMC WECO 1502', 'SPM 1502', 'Anson 1502', 'Forum Energy 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-1502-FF-15K-STD-SPM',
    title: 'Crossover Union, 1502 Series F×F, 15,000 psi, Standard Service',
    brandSlug: 'spm-oil-gas',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Female × Female',
    endConnectionA: '1502 Female Weco Union',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in',
    boreId: 'Same as nominal — full bore through body',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Female × Female crossover union, 15,000 psi standard-service rated. WECO / SPM interchange. Used to mate two male hammer-union ends across a flow line.',
    applications: [
      'Frac iron service trees',
      'Pump discharge to manifold tie-ins',
      'Stimulation flow lines',
    ],
    oemKeywords: ['SPM Oil & Gas 1502', 'FMC WECO 1502', 'Anson 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-1502-MF-10K-SOUR-ANSON',
    title: 'Crossover Union, 1502 Series M×F, 10,000 psi, Sour Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1502',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Male × Female',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through body',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '1502 Series Male × Female crossover union, 10,000 psi sour-service (NACE MR0175) rated. Anson / WECO / FMC interchange. For H₂S-bearing well streams in frac and well-stimulation service.',
    applications: [
      'Sour-well frac iron service trees',
      'H₂S-bearing flowback lines',
      'NACE-compliant stimulation manifolds',
      'Sour-service coil-tubing surface lines',
    ],
    oemKeywords: ['Anson 1502', 'FMC WECO 1502', 'SPM 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-XO-1502-RED-15K-STD-FMC',
    title: 'Crossover Union, 1502 Series Reducer M×F, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Reducer (M × F, different sizes)',
    endConnectionA: '1502 Male Weco Union (larger)',
    endConnectionB: '1502 Female Weco Union (smaller)',
    endConnectionExtra: '',
    availableSizes: '4 in × 3 in, 4 in × 2 in, 3 in × 2 in',
    boreId: 'Stepped — matches each end',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Reducer crossover union, 15,000 psi standard-service rated. Steps a larger 1502 line down to a smaller 1502 line — common between pump discharge headers and downstream stimulation iron.',
    applications: [
      'Pump discharge to service-tree step-downs',
      'Manifold-to-frac-tree size transitions',
      'Coiled-tubing surface lines',
    ],
    oemKeywords: ['FMC WECO 1502 Reducer', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-XO-1002-MM-10K-STD-FMC',
    title: 'Crossover Union, 1002 Series M×M, 10,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '1002',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Standard',
    configuration: 'Male × Male',
    endConnectionA: '1002 Male Weco Union',
    endConnectionB: '1002 Male Weco Union',
    endConnectionExtra: '',
    availableSizes: '3 in, 4 in',
    boreId: 'Same as nominal — full bore through body',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1002 Series Male × Male crossover union, 10,000 psi standard-service rated. WECO / FMC interchange. The 1002 series is the workhorse for 10K-psi flow lines in well-stimulation and well control.',
    applications: [
      'Pump-truck flow lines',
      'Stimulation service trees (10K class)',
      'Well-control kill manifolds',
    ],
    oemKeywords: ['FMC WECO 1002', 'SPM 1002', 'Anson 1002'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-602-MF-6K-STD-INDUS',
    title: 'Crossover Union, 602 Series M×F, 6,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Standard',
    configuration: 'Male × Female',
    endConnectionA: '602 Male Weco Union',
    endConnectionB: '602 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in',
    boreId: 'Same as nominal — full bore',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '602 Series Male × Female crossover union, 6,000 psi standard-service rated. WECO / FMC interchange. The 602 series serves 6K-psi production and intermediate-pressure flow lines.',
    applications: [
      'Production well flow lines',
      'Flowback and well-test iron',
      'Intermediate-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 602', 'SPM 602', 'Anson 602'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-602-MF-6K-SOUR-FMC',
    title: 'Crossover Union, 602 Series M×F, 6,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Male × Female',
    endConnectionA: '602 Male Weco Union',
    endConnectionB: '602 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '602 Series Male × Female crossover union, 6,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For H₂S-bearing 6K-psi production and well-test lines.',
    applications: [
      'Sour-well production flow lines',
      'H₂S flowback iron',
      'Sour-service well-test manifolds',
    ],
    oemKeywords: ['FMC WECO 602', 'SPM 602', 'Anson 602'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-XO-206-MF-2K-STD-ANSON',
    title: 'Crossover Union, 206 Series M×F, 2,000 psi, Standard Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '206',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Standard',
    configuration: 'Male × Female',
    endConnectionA: '206 Male Weco Union',
    endConnectionB: '206 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in, 6 in',
    boreId: 'Same as nominal — full bore',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '206 Series Male × Female crossover union, 2,000 psi standard-service rated. Anson / WECO / FMC interchange. The 206 (and parallel 200) series are low-pressure standards for water and brine lines.',
    applications: [
      'Water and brine transfer lines',
      'Low-pressure flowback and water-disposal manifolds',
      'Cement-mix tank circulation',
    ],
    oemKeywords: ['Anson 206', 'FMC WECO 206', 'SPM 206'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-XO-206-MF-2K-SOUR-FMC',
    title: 'Crossover Union, 206 Series M×F, 2,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Crossover Union',
    figureClass: '206',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Male × Female',
    endConnectionA: '206 Male Weco Union',
    endConnectionB: '206 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '3 in, 4 in',
    boreId: 'Same as nominal — full bore',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '206 Series Male × Female crossover union, 2,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For H₂S sour-well water and brine handling.',
    applications: [
      'Sour-well water injection lines',
      'H₂S flowback water disposal',
      'NACE-compliant low-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 206', 'Anson 206', 'SPM 206'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // ADAPTERS — WECO Adapter Flange (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-AF-10K-1502-FMC',
    title: 'Adapter Flange, API 6BX 10K × 1502 Female Weco, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Adapter Flange (Union × Flange)',
    figureClass: '10K',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Standard',
    configuration: 'API Flange × Weco Female',
    endConnectionA: 'API 6BX 10K flange (raised face, BX ring groove)',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'Matches the API flange bore',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 10K flanged × 1502 Female Weco adapter flange. Mates a wellhead / Christmas-tree flanged stack to a hammer-union flow line. FMC / WECO interchange.',
    applications: [
      'Wellhead to frac-tree adapter',
      'Christmas-tree flange to flow-line tie-in',
      'Test-tree to flow-iron transition',
    ],
    oemKeywords: ['FMC WECO 1502', 'Cameron 10K', 'Stream-Flo 10K', 'NOV 10K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-AF-15K-1502-CAMERON',
    title: 'Adapter Flange, API 6BX 15K × 1502 Female Weco, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Adapter Flange (Union × Flange)',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'API Flange × Weco Female',
    endConnectionA: 'API 6BX 15K flange (BX ring groove)',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in',
    boreId: 'Matches the API flange bore',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 15K flanged × 1502 Female Weco adapter flange. The premium adapter for high-pressure frac-tree to flow-iron interfaces. Cameron / FMC interchange.',
    applications: [
      'High-pressure frac-tree to flow-iron transitions',
      'Surface test-tree adapters',
      '15K wellhead to pump-discharge interfaces',
    ],
    oemKeywords: ['Cameron 15K', 'FMC WECO 1502', 'Stream-Flo 15K', 'NOV 15K'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-AF-5K-602-INDUS',
    title: 'Adapter Flange, API 6BX 5K × 602 Female Weco, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Adapter Flange (Union × Flange)',
    figureClass: '5K',
    workingPressurePsi: 5000,
    pressureClass: '5K',
    serviceClass: 'Standard',
    configuration: 'API Flange × Weco Female',
    endConnectionA: 'API 6BX 5K flange (BX ring groove)',
    endConnectionB: '602 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in',
    boreId: 'Matches the API flange bore',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 5K flanged × 602 Female Weco adapter flange. Common for production wellhead to flow-line interfaces in 5K-psi service. Cameron / FMC equivalents.',
    applications: [
      'Production wellhead to flow-line tie-ins',
      'Christmas-tree flange to test-iron transitions',
      'Tubing-head adapter applications',
    ],
    oemKeywords: ['Cameron 5K', 'FMC WECO 602', 'Stream-Flo 5K'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // ADAPTERS — Double Studded / Double Flange Adapters (2)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-DSA-API-5K-3K-CAMERON',
    title: 'Double Studded Adapter, API 6BX 5K × 3K, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Double Studded Adapter',
    figureClass: '5K',
    workingPressurePsi: 5000,
    pressureClass: '5K',
    serviceClass: 'Standard',
    configuration: 'Studded × Studded (different pressure classes)',
    endConnectionA: 'API 6BX 5K studded (top)',
    endConnectionB: 'API 6BX 3K studded (bottom)',
    endConnectionExtra: 'Studs and nuts integrated — no separate bolting needed',
    availableSizes: '2-1/16 in × 2-1/16 in, 3-1/8 in × 3-1/8 in, 3-1/8 in × 4-1/16 in',
    boreId: 'Through-bore matches the smaller flange size',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 5K × 3K Double Studded Adapter (DSA). Steps from a 5K wellhead bowl to a 3K Christmas-tree gate valve or vice versa. Cameron / Stream-Flo wellhead interchange.',
    applications: [
      'Wellhead bowl-to-Christmas-tree pressure step-down',
      'BOP stack to wellhead adapter',
      'Tubing-head to tree-cap interface',
    ],
    oemKeywords: ['Cameron Type C DSA', 'Stream-Flo DSA', 'FMC Wellhead DSA'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-FI-DFA-RTJ-2500-INDUS',
    title: 'Double Flange Adapter, 2500# RTJ × 1502 Weco, Sour Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-adapters',
    flowIronType: 'Double Flange Adapter',
    figureClass: '15K',
    workingPressurePsi: 6170,
    pressureClass: 'ANSI 2500',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'ANSI Flange × Weco Female',
    endConnectionA: 'ANSI 2500# RTJ flange (raised face, ring-joint groove)',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: '',
    availableSizes: '2 in × 1 in, 3 in × 3 in, 4 in × 3 in',
    boreId: 'Matches the smaller end',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      'ANSI 2500# RTJ flanged × 1502 Female Weco double-flange adapter, sour-service rated. For process-plant pipework to sour-well frac-iron transitions.',
    applications: [
      'Process-plant tie-ins to sour-well frac iron',
      'ANSI / WECO interface adapters',
      'Refinery-to-wellsite test loops',
    ],
    oemKeywords: ['ANSI 2500 RTJ', 'FMC WECO 1502', 'Anson 1502'],
    leadTimeDays: 21,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Hammer Unions (8)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-HU-1502-NPT-15K-STD-FMC',
    title: 'Hammer Union Set, 1502 Series, NPT × NPT, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '2 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series complete hammer union set with NPT threaded ends, 15,000 psi standard-service rated. WECO / FMC industry standard for high-pressure threaded line make-ups.',
    applications: [
      'Threaded high-pressure flow lines',
      'Pump-truck inlet manifolds (NPT side)',
      'Skid-piping make-ups',
    ],
    oemKeywords: ['FMC WECO 1502', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-HU-1502-BW-15K-STD-FMC',
    title: 'Hammer Union Set, 1502 Series, Butt-Weld × Butt-Weld, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'Butt-Weld (Male sub) — XXH schedule',
    endConnectionB: 'Butt-Weld (Female sub) — XXH schedule',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '3 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'ASME B16.25 (BW)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series complete hammer union set with butt-weld ends (XXH schedule), 15,000 psi standard-service rated. For permanent in-line installation in fabricated frac iron skids.',
    applications: [
      'Welded frac iron skid piping',
      'Manifold-to-flow-line permanent tie-ins',
      'Service-tree fabrication',
    ],
    oemKeywords: ['FMC WECO 1502 BW', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-HU-1002-NPT-10K-STD-INDUS',
    title: 'Hammer Union Set, 1002 Series, NPT × NPT, 10,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '1002',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '4 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1002 Series complete hammer union set with NPT threaded ends, 10,000 psi standard-service rated. WECO interchange. The 1002 series suits 10K threaded lines and skid manifolds.',
    applications: [
      '10K threaded skid piping',
      'Stimulation flow lines',
      'Well-control manifold make-ups',
    ],
    oemKeywords: ['FMC WECO 1002', 'SPM 1002', 'Anson 1002'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-HU-602-NPT-6K-STD-ANSON',
    title: 'Hammer Union Set, 602 Series, NPT × NPT, 6,000 psi, Standard Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '2 in, 4 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '602 Series complete hammer union set with NPT threaded ends, 6,000 psi standard-service rated. Anson / WECO interchange. 602 is the workhorse for production-pressure flow lines.',
    applications: [
      'Production wellhead flow lines',
      '6K threaded manifolds',
      'Flowback and well-test iron',
    ],
    oemKeywords: ['Anson 602', 'FMC WECO 602', 'SPM 602'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-HU-400-NPT-4K-STD-INDUS',
    title: 'Hammer Union Set, 400 Series, NPT × NPT, 4,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '400',
    workingPressurePsi: 4000,
    pressureClass: '4K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '12 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '400 Series complete hammer union set, large-bore (12 in), 4,000 psi standard-service rated. For high-volume mid-pressure water and brine transfer.',
    applications: [
      'Large-bore water transfer lines',
      'Frac-water disposal manifolds',
      'Bulk-fluid pumping spreads',
    ],
    oemKeywords: ['FMC WECO 400', 'SPM 400', 'Anson 400'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-HU-206-BW-2K-SOUR-FMC',
    title: 'Hammer Union Set, 206 Series, Butt-Weld × Butt-Weld, 2,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '206',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'Butt-Weld (Male sub) — XH schedule, double-end-tapered',
    endConnectionB: 'Butt-Weld (Female sub) — XH schedule, double-end-tapered',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '3 in, 4 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '206 Series complete hammer union set, butt-weld ends, 2,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For H₂S sour-well water and flowback handling.',
    applications: [
      'Sour-well flowback iron',
      'H₂S water-disposal lines',
      'NACE-compliant low-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 206', 'Anson 206', 'SPM 206'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-HU-200-NPT-2K-STD-INDUS',
    title: 'Hammer Union Set, 200 Series, NPT × NPT, 2,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '200',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '2 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '200 Series complete hammer union set with NPT threaded ends, 2,000 psi standard-service rated. WECO interchange. The 200 series is the standard for low-pressure water lines.',
    applications: [
      'Water and brine transfer',
      'Mud-pit recirculation lines',
      'Low-pressure cement-mix circulation',
    ],
    oemKeywords: ['FMC WECO 200', 'Anson 200', 'SPM 200'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-HU-100-NPT-1K-STD-INDUS',
    title: 'Hammer Union Set, 100 Series, NPT × NPT, 1,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Hammer Union',
    figureClass: '100',
    workingPressurePsi: 1000,
    pressureClass: '1K',
    serviceClass: 'Standard',
    configuration: 'Complete set — Male sub + Female sub + wing nut',
    endConnectionA: 'NPT (Male sub)',
    endConnectionB: 'NPT (Female sub)',
    endConnectionExtra: 'Wing nut included; gasket sold separately',
    availableSizes: '4 in, 6 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '100 Series complete hammer union set, large-bore (4–6 in), 1,000 psi standard-service rated. The economy choice for low-pressure bulk-fluid transfer.',
    applications: [
      'Bulk water and brine transfer',
      'Frac-water staging tanks',
      'Production-water collection',
    ],
    oemKeywords: ['FMC WECO 100', 'Anson 100', 'SPM 100'],
    leadTimeDays: 7,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Crosses (5)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-CR-1502-MMMF-15K-STD-SPM',
    title: 'Cross, 1502 Series 3M × 1F (with NPT Tap), 15,000 psi, Standard Service',
    brandSlug: 'spm-oil-gas',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Cross',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'M × M × M × F (3 Male, 1 Female)',
    endConnectionA: '1502 Male Weco Union (×3)',
    endConnectionB: '1502 Female Weco Union (×1)',
    endConnectionExtra: '1/2 in NPT instrument tap (optional)',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series 4-way Cross, 3 Male × 1 Female (with optional 1/2 in NPT instrument tap), 15,000 psi standard service. SPM / WECO interchange. The classic frac-tree distribution cross.',
    applications: [
      'Frac-tree fluid distribution',
      'Pumping-spread service-tree manifolds',
      'High-pressure stimulation iron',
    ],
    oemKeywords: ['SPM 1502 Cross', 'FMC WECO 1502', 'Anson 1502', 'Forum Energy 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-CR-1502-FFFM-10K-SOUR-FMC',
    title: 'Cross, 1502 Series 3F × 1M, 10,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Cross',
    figureClass: '1502',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'F × F × F × M (3 Female, 1 Male)',
    endConnectionA: '1502 Female Weco Union (×3)',
    endConnectionB: '1502 Male Weco Union (×1)',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '1502 Series 4-way Cross, 3 Female × 1 Male, 10,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For sour-well frac-tree distribution.',
    applications: [
      'Sour-well frac-tree distribution',
      'H₂S stimulation iron',
      'NACE-compliant high-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 1502 Cross', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-CR-1502-MMFF-10K-SOUR-ANSON',
    title: 'Cross, 1502 Series 2M × 2F (with NPT Tap), 10,000 psi, Sour Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Cross',
    figureClass: '1502',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'M × M × F × F (2 Male, 2 Female)',
    endConnectionA: '1502 Male Weco Union (×2)',
    endConnectionB: '1502 Female Weco Union (×2)',
    endConnectionExtra: '1/2 in NPT instrument tap',
    availableSizes: '3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '1502 Series 4-way Cross, 2 Male × 2 Female alternating, with 1/2 in NPT instrument tap, 10,000 psi sour-service rated. Anson / WECO frac-tree interchange.',
    applications: [
      'Sour-well frac-tree distribution',
      'Pressure-monitoring tee in stimulation lines',
      'NACE manifolds with sensor tap',
    ],
    oemKeywords: ['Anson 1502 Cross', 'FMC WECO 1502', 'SPM 1502'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-CR-602-MMMF-6K-SOUR-INDUS',
    title: 'Cross, 602 Series 3M × 1F, 6,000 psi, Sour Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Cross',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'M × M × M × F (3 Male, 1 Female)',
    endConnectionA: '602 Male Weco Union (×3)',
    endConnectionB: '602 Female Weco Union (×1)',
    endConnectionExtra: '',
    availableSizes: '3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '602 Series 4-way Cross, 3 Male × 1 Female, 6,000 psi sour-service (NACE MR0175) rated. WECO interchange. For 6K sour-well production manifolds.',
    applications: [
      'Sour-well production-tree distribution',
      'H₂S well-test manifolds',
      '6K sour flowback iron',
    ],
    oemKeywords: ['FMC WECO 602 Cross', 'SPM 602', 'Anson 602'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-CR-206-MMMF-2K-STD-FMC',
    title: 'Cross, 206 Series 3M × 1F, 2,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Cross',
    figureClass: '206',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Standard',
    configuration: 'M × M × M × F (3 Male, 1 Female)',
    endConnectionA: '206 Male Weco Union (×3)',
    endConnectionB: '206 Female Weco Union (×1)',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in, 4 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '206 Series 4-way Cross, 3 Male × 1 Female, 2,000 psi standard-service rated. WECO / FMC interchange. The standard low-pressure water-distribution cross.',
    applications: [
      'Water-transfer manifolds',
      'Frac-water staging crosses',
      'Low-pressure flowback distribution',
    ],
    oemKeywords: ['FMC WECO 206 Cross', 'Anson 206', 'SPM 206'],
    leadTimeDays: 7,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Tees (5)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-TE-1502-MFF-15K-STD-SPM',
    title: 'Tee, 1502 Series M × F × F, 15,000 psi, Standard Service',
    brandSlug: 'spm-oil-gas',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Tee',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'M × F × F (1 Male / 2 Female)',
    endConnectionA: '1502 Male Weco Union (run inlet)',
    endConnectionB: '1502 Female Weco Union (run outlet, branch)',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series 3-way Tee, Male × Female × Female, 15,000 psi standard-service rated. SPM / WECO interchange. Classic high-pressure branch tee for frac iron.',
    applications: [
      'Frac iron branch tees',
      'Pump discharge to dual-line splits',
      'Service-tree distribution',
    ],
    oemKeywords: ['SPM 1502 Tee', 'FMC WECO 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-TE-1502-MFF-10K-SOUR-FMC',
    title: 'Tee, 1502 Series M × F × F, 10,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Tee',
    figureClass: '1502',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'M × F × F (1 Male / 2 Female)',
    endConnectionA: '1502 Male Weco Union (run inlet)',
    endConnectionB: '1502 Female Weco Union (run outlet, branch)',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '1502 Series 3-way Tee, Male × Female × Female, 10,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For sour-well frac iron branches.',
    applications: [
      'Sour-well frac iron branches',
      'H₂S service-tree distribution',
      'NACE high-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 1502 Tee', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-TE-1502-FFM-15K-STD-INDUS',
    title: 'Tee, 1502 Series F × F × M, 15,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Tee',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'F × F × M (2 Female / 1 Male)',
    endConnectionA: '1502 Female Weco Union (run inlet)',
    endConnectionB: '1502 Female Weco Union (run outlet)',
    endConnectionExtra: '1502 Male Weco Union (branch)',
    availableSizes: '2 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series 3-way Tee, 2 Female (run) × 1 Male (branch), 15,000 psi standard-service rated. The branch-male variant for take-offs from female-ended pup-joint runs.',
    applications: [
      'Female-ended pup-joint take-offs',
      'Service-tree branch lines',
    ],
    oemKeywords: ['FMC WECO 1502 Tee', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-TE-1502-MMF-15K-STD-ANSON',
    title: 'Tee, 1502 Series M × M × F, 15,000 psi, Standard Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Tee',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'M × M × F (2 Male / 1 Female)',
    endConnectionA: '1502 Male Weco Union (run inlet)',
    endConnectionB: '1502 Male Weco Union (run outlet)',
    endConnectionExtra: '1502 Female Weco Union (branch)',
    availableSizes: '3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series 3-way Tee, 2 Male (run) × 1 Female (branch), 15,000 psi standard-service rated. Anson / WECO interchange. Branch take-off from male-ended runs.',
    applications: [
      'Male-ended pup-joint branch take-offs',
      'Pump-truck cross-tie iron',
      'Service-tree distribution',
    ],
    oemKeywords: ['Anson 1502 Tee', 'FMC WECO 1502', 'SPM 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-TE-602-MFF-6K-SOUR-INDUS',
    title: 'Tee, 602 Series M × F × F, 6,000 psi, Sour Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Tee',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'M × F × F (1 Male / 2 Female)',
    endConnectionA: '602 Male Weco Union (run inlet)',
    endConnectionB: '602 Female Weco Union (run outlet, branch)',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — full bore through main run',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '602 Series 3-way Tee, Male × Female × Female, 6,000 psi sour-service rated. WECO interchange. Sour-well production branch tee.',
    applications: [
      'Sour-well production-tree branches',
      'H₂S well-test iron',
      '6K sour flow lines',
    ],
    oemKeywords: ['FMC WECO 602 Tee', 'SPM 602', 'Anson 602'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Elbows (4)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-EL-1502-90LR-MF-15K-STD-SPM',
    title: 'Elbow LR 90°, 1502 Series M × F (Integral), 15,000 psi, Standard Service',
    brandSlug: 'spm-oil-gas',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Elbow',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Long-Radius 90°, Male × Female',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: 'Integral body (no welds)',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — long-radius bend',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Long-Radius 90° integral elbow, Male × Female, 15,000 psi standard-service rated. SPM / WECO interchange. Reduces pressure drop and erosion vs short-radius bends.',
    applications: [
      'Frac iron 90° turns',
      'Service-tree side-out runs',
      'High-pressure stimulation iron',
    ],
    oemKeywords: ['SPM 1502 Elbow', 'FMC WECO 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-EL-1502-90LR-MF-10K-SOUR-FMC',
    title: 'Elbow LR 90°, 1502 Series M × F (Integral), 10,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Elbow',
    figureClass: '1502',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Long-Radius 90°, Male × Female',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: '1502 Female Weco Union',
    endConnectionExtra: 'Integral body (no welds)',
    availableSizes: '2 in, 3 in',
    boreId: 'Same as nominal — long-radius bend',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '1502 Series Long-Radius 90° integral elbow, Male × Female, 10,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. Sour-well frac-iron 90° turns.',
    applications: [
      'Sour-well frac iron 90° turns',
      'H₂S service-tree side-out runs',
      'NACE-compliant high-pressure manifolds',
    ],
    oemKeywords: ['FMC WECO 1502 Elbow', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-EL-602-90LR-MF-6K-SOUR-ANSON',
    title: 'Elbow LR 90°, 602 Series M × F (Integral), 6,000 psi, Sour Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Elbow',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Long-Radius 90°, Male × Female',
    endConnectionA: '602 Male Weco Union',
    endConnectionB: '602 Female Weco Union',
    endConnectionExtra: 'Integral body (no welds)',
    availableSizes: '3 in, 4 in',
    boreId: 'Same as nominal — long-radius bend',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '602 Series Long-Radius 90° integral elbow, Male × Female, 6,000 psi sour-service rated. Anson / WECO interchange. Sour-well 6K production-iron 90° turns.',
    applications: [
      'Sour-well production iron 90° turns',
      'H₂S well-test manifolds',
      '6K sour flowback iron',
    ],
    oemKeywords: ['Anson 602 Elbow', 'FMC WECO 602', 'SPM 602'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-EL-206-45BW-MF-2K-SOUR-INDUS',
    title: 'Elbow 45°, 206 Series M × F (Butt-Weld), 2,000 psi, Sour Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Elbow',
    figureClass: '206',
    workingPressurePsi: 2000,
    pressureClass: '2K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: '45° bend, Male × Female',
    endConnectionA: '206 Male Weco Union',
    endConnectionB: '206 Female Weco Union',
    endConnectionExtra: 'S80 BW (XH schedule butt-weld) lugs available',
    availableSizes: '4 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '206 Series 45° elbow, Male × Female, 2,000 psi sour-service (NACE MR0175) rated. For sour-well water-disposal lines requiring a 45° offset.',
    applications: [
      'Sour-well water disposal',
      'H₂S flowback offsets',
      'Tank-farm sour-fluid tie-ins',
    ],
    oemKeywords: ['FMC WECO 206', 'Anson 206', 'SPM 206'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Wyes (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-WY-1502-S-MFF-15K-STD-FMC',
    title: 'Wye Straight, 1502 Series M × F × F, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Wye — Straight',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Straight-run Y, Male × Female × Female',
    endConnectionA: '1502 Male Weco Union (run)',
    endConnectionB: '1502 Female Weco Union (×2 — Y branches)',
    endConnectionExtra: '',
    availableSizes: '2 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Straight Wye (Y), Male × Female × Female, 15,000 psi standard-service rated. WECO / FMC interchange. Combines two parallel high-pressure flow streams.',
    applications: [
      'Pump-discharge merge headers',
      'Frac-iron flow combination',
      'Stimulation manifold inlets',
    ],
    oemKeywords: ['FMC WECO 1502 Wye', 'SPM 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-WY-1502-L-FMF-15K-STD-SPM',
    title: 'Wye Lateral, 1502 Series F × M × F, 15,000 psi, Standard Service',
    brandSlug: 'spm-oil-gas',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Wye — Lateral',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Lateral Y, Female × Male × Female',
    endConnectionA: '1502 Female Weco Union (×2 — straight run)',
    endConnectionB: '1502 Male Weco Union (lateral branch)',
    endConnectionExtra: '',
    availableSizes: '3 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Lateral Wye, Female × Male × Female, 15,000 psi standard-service rated. SPM / WECO interchange. Side-injection / takeoff at acute angle for reduced pressure drop.',
    applications: [
      'Stimulation chemical injection points',
      'Frac-iron lateral take-offs',
      'Acidizing service-tree branches',
    ],
    oemKeywords: ['SPM 1502 Wye Lateral', 'FMC WECO 1502', 'Anson 1502'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-WY-1502-L-MFM-15K-STD-ANSON',
    title: 'Wye Lateral, 1502 Series M × F × M, 15,000 psi, Standard Service',
    brandSlug: 'anson',
    countryOfOrigin: 'United Kingdom',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Wye — Lateral',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Lateral Y, Male × Female × Male',
    endConnectionA: '1502 Male Weco Union (×2 — straight run)',
    endConnectionB: '1502 Female Weco Union (lateral branch)',
    endConnectionExtra: '',
    availableSizes: '3 in',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Lateral Wye, Male × Female × Male, 15,000 psi standard-service rated. Anson / WECO interchange. Inverse-gender wye for branch-injection from female-ended branches.',
    applications: [
      'Female-branch lateral injection points',
      'Frac-iron acid-injection wyes',
      'Stimulation iron flexibility',
    ],
    oemKeywords: ['Anson 1502 Wye', 'FMC WECO 1502', 'SPM 1502'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Blanking Caps (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-BC-1502-MM-15K-STD-FMC',
    title: 'Blanking Cap, 1502 Series Male, 15,000 psi, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Blanking Cap',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Male blank (caps a 1502 Female union)',
    endConnectionA: '1502 Male Weco Union',
    endConnectionB: 'Blank',
    endConnectionExtra: 'Optional 1/2 in NPT bleed tap',
    availableSizes: '2 in, 3 in',
    boreId: 'N/A — solid blank',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Male Blanking Cap, 15,000 psi standard-service rated. WECO / FMC interchange. Caps a 1502 Female union for pressure testing or line termination.',
    applications: [
      'Frac-iron pressure testing',
      'Line termination during make-up',
      'Service-tree blanks',
    ],
    oemKeywords: ['FMC WECO 1502 Cap', 'SPM 1502 Blank', 'Anson 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-BC-1502-MF-15K-STD-INDUS',
    title: 'Blanking Cap, 1502 Series Female, 15,000 psi, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Blanking Cap',
    figureClass: '1502',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Female blank (caps a 1502 Male union)',
    endConnectionA: '1502 Female Weco Union',
    endConnectionB: 'Blank',
    endConnectionExtra: 'Optional 1/2 in NPT bleed tap',
    availableSizes: '2 in, 3 in',
    boreId: 'N/A — solid blank',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      '1502 Series Female Blanking Cap, 15,000 psi standard-service rated. Caps a 1502 Male union — used for pressure testing pup-joint runs or terminating Male-ended lines.',
    applications: [
      'Frac-iron pressure testing',
      'Male-line termination',
      'Pump-truck winterization caps',
    ],
    oemKeywords: ['FMC WECO 1502 Cap', 'SPM 1502 Blank', 'Anson 1502'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-BC-602-MF-6K-SOUR-FMC',
    title: 'Blanking Cap Set (Male + Female), 602 Series, 6,000 psi, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Blanking Cap',
    figureClass: '602',
    workingPressurePsi: 6000,
    pressureClass: '6K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Set of one Male blank + one Female blank',
    endConnectionA: '602 Male / Female Weco Union',
    endConnectionB: 'Blank',
    endConnectionExtra: '',
    availableSizes: '2 in, 3 in',
    boreId: 'N/A — solid blank',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'NACE MR0175',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      '602 Series Blanking Cap pair (Male + Female), 6,000 psi sour-service (NACE MR0175) rated. WECO / FMC interchange. For sour-well 6K iron termination and pressure testing.',
    applications: [
      'Sour-well iron pressure testing',
      'H₂S line termination',
      'Sour service-tree blanks',
    ],
    oemKeywords: ['FMC WECO 602 Cap', 'SPM 602', 'Anson 602'],
    leadTimeDays: 14,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FITTINGS — Studded Fittings + API Hubs/Clamps + BSL Bolting (4)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-SF-API-10K15K-CAMERON',
    title: 'Studded Cross / Tee Fitting, API 6BX 10K & 15K, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Studded Fitting',
    figureClass: '10K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Studded Cross / Tee — flange × studded × studded × studded',
    endConnectionA: 'API 6BX studded ends (×3 or ×4)',
    endConnectionB: '',
    endConnectionExtra: 'Studs and nuts integrated; ring-joint gaskets sold separately',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in (10K and 15K classes)',
    boreId: 'Through-bore matches the smaller flange size',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX Studded Cross / Tee fitting, 10K and 15K classes, standard-service rated. Cameron / FMC wellhead interchange. Eliminates separate flanges + studs in tight-tolerance wellhead assemblies.',
    applications: [
      'Wellhead spool-piece distributions',
      'Christmas-tree branches',
      'Frac-tree integrated fittings',
    ],
    oemKeywords: ['Cameron Studded', 'FMC Wellhead 10K/15K', 'NOV Wellhead', 'Stream-Flo'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-FI-HC-GRAYLOC-INDUS',
    title: 'Hub & Clamp Connector (Grayloc-style), 5K to 15K Pressure Classes',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'API Hub & Clamp',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Hub × Clamp connector pair (Grayloc-style)',
    endConnectionA: 'Hub (welded or studded)',
    endConnectionB: 'Hub (welded or studded)',
    endConnectionExtra: 'Clamp + Sealing Ring (sold integrated)',
    availableSizes: '2 in, 3 in, 4 in (and bore-equivalent API sizes)',
    boreId: 'Same as nominal',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'Other (frac-iron lineage)',
    materialClass: 'N/A',
    temperatureRating: STD_TEMP,
    oneLiner:
      'Grayloc-style hub-and-clamp pressure-rated connector, 5K to 15K classes. The flange-alternative for compact wellhead and process-skid pipework — fast make-and-break, no stud bolts, pressure-energised seal.',
    applications: [
      'Compact wellhead skid pipework',
      'Process-plant high-pressure tie-ins',
      'Subsea / tight-tolerance assemblies',
    ],
    oemKeywords: ['Grayloc / Oceaneering', 'Vector / Cameron', 'NOV Hub-Clamp'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-BG-RJG-API-INDUS',
    title: 'API 6BX Ring Joint Gasket Set (BX & R Series), All Pressure Classes',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'Ring Joint Gasket',
    figureClass: 'N/A',
    workingPressurePsi: 20000,
    pressureClass: '20K',
    serviceClass: 'Standard',
    configuration: 'Ring-joint gasket set — BX-152 through BX-169, R-31 through R-46',
    endConnectionA: 'BX & R series, octagonal cross-section',
    endConnectionB: '',
    endConnectionExtra: 'Material options: soft iron (default), 316SS, Inconel 625 (sour)',
    availableSizes: 'BX-152 to BX-169 (5K, 10K, 15K, 20K classes); R-12 to R-46 (ASME flanges)',
    boreId: 'N/A — sealing element',
    lengthIn: '',
    materialConstruction: 'Soft iron (default), 316SS or Inconel 625 (NACE) on request',
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: '-50°F to 350°F',
    oneLiner:
      'API 6BX ring-joint gasket set covering all standard wellhead and ASME flange ring grooves. Soft iron default; 316SS / Inconel 625 for sour and severe service.',
    applications: [
      'Wellhead and Christmas-tree flange seals',
      'API 6A pressure-rated joints',
      'ASME B16.5 / B16.20 RTJ flanges',
    ],
    oemKeywords: ['Galperti RJG', 'Crane Lamons RJG', 'Cameron RJG', 'FMC RJG'],
    leadTimeDays: 7,
  },
  {
    sku: 'IH-FI-BG-STUDS-API-INDUS',
    title: 'BSL Stud & Nut Set (B7/2H), API 6A 5K to 20K Flange Bolting',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-fittings',
    flowIronType: 'BSL Bolting Set',
    figureClass: 'N/A',
    workingPressurePsi: 20000,
    pressureClass: '20K',
    serviceClass: 'Standard',
    configuration: 'Stud-and-nut set per flange — ASTM A193 B7 studs / A194 2H nuts',
    endConnectionA: 'API 6A 5K, 10K, 15K, 20K flange bolting patterns',
    endConnectionB: '',
    endConnectionExtra: 'Sour-service variant: B7M / 2HM per NACE MR0175',
    availableSizes: 'Per API 6BX flange schedule — 2-1/16 in to 18-3/4 in flange sizes',
    boreId: 'N/A — bolting',
    lengthIn: 'Per flange schedule (varies by class and size)',
    materialConstruction: 'A193 B7 studs / A194 2H nuts, hot-dip galvanised or PTFE coated',
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: '-50°F to 750°F',
    oneLiner:
      'API 6A flange stud and nut sets in B7/2H standard or B7M/2HM (NACE) for sour service. All pressure classes and sizes from 2-1/16 in to 18-3/4 in.',
    applications: [
      'Wellhead flange make-up bolting',
      'Christmas-tree assembly hardware',
      'Surface-tree and BOP stack bolting',
    ],
    oemKeywords: ['Galperti BSL', 'Crane Lamons Bolting', 'Cameron Bolting', 'NOV Bolting'],
    leadTimeDays: 7,
  },

  // ════════════════════════════════════════════════════════════════════════
  // API FLANGES — Blind, Companion, Weld-Neck, Instrument (10)
  // ════════════════════════════════════════════════════════════════════════
  {
    sku: 'IH-FI-FL-BLIND-5K-CAMERON',
    title: 'Blind Flange, API 6BX 5K, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Blind Flange',
    figureClass: '5K',
    workingPressurePsi: 5000,
    pressureClass: '5K',
    serviceClass: 'Standard',
    configuration: 'Blind (no bore) — caps a flanged stack',
    endConnectionA: 'API 6BX 5K flanged (BX ring groove)',
    endConnectionB: '',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in, 7-1/16 in',
    boreId: 'N/A — blind',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 5K Blind Flange, standard-service rated. Cameron / FMC / Stream-Flo wellhead interchange. Caps wellhead bowls and Christmas-tree top connections.',
    applications: [
      'Wellhead bowl caps',
      'Christmas-tree top blinds',
      '5K production-tree blank flanges',
    ],
    oemKeywords: ['Cameron 5K Blind', 'FMC 5K', 'Stream-Flo 5K', 'NOV 5K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-FL-BLIND-10K-FMC',
    title: 'Blind Flange, API 6BX 10K, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Blind Flange',
    figureClass: '10K',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Standard',
    configuration: 'Blind (no bore)',
    endConnectionA: 'API 6BX 10K flanged (BX ring groove)',
    endConnectionB: '',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'N/A — blind',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 10K Blind Flange, standard-service rated. FMC / Cameron / NOV wellhead interchange. The standard 10K stack-cap flange.',
    applications: [
      '10K wellhead stack caps',
      'Frac-tree top blinds',
      '10K test-tree caps',
    ],
    oemKeywords: ['FMC 10K Blind', 'Cameron 10K', 'NOV 10K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-FL-BLIND-15K-NOV',
    title: 'Blind Flange, API 6BX 15K, Standard Service',
    brandSlug: 'nov',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Blind Flange',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Blind (no bore)',
    endConnectionA: 'API 6BX 15K flanged (BX ring groove)',
    endConnectionB: '',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'N/A — blind',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 15K Blind Flange, standard-service rated. NOV / Cameron / FMC wellhead interchange. The high-pressure stack-cap for 15K frac-trees and Christmas trees.',
    applications: [
      '15K frac-tree top caps',
      'High-pressure wellhead blinds',
      '15K test-tree termination',
    ],
    oemKeywords: ['NOV 15K Blind', 'Cameron 15K', 'FMC 15K'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-FL-BLIND-15K-SOUR-FMC',
    title: 'Blind Flange, API 6BX 15K, Sour Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Blind Flange',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Sour (NACE MR0175)',
    configuration: 'Blind (no bore)',
    endConnectionA: 'API 6BX 15K flanged (BX ring groove)',
    endConnectionB: '',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'N/A — blind',
    lengthIn: '',
    materialConstruction: SOUR_MAT,
    apiSpec: 'API 6A',
    materialClass: 'EE',
    temperatureRating: SOUR_TEMP,
    oneLiner:
      'API 6BX 15K Blind Flange, sour-service (NACE MR0175) rated. FMC / Cameron / NOV interchange. For H₂S 15K wellhead and frac-tree caps.',
    applications: [
      'Sour-well 15K frac-tree top caps',
      'H₂S wellhead blinds',
      'NACE-compliant 15K test-tree termination',
    ],
    oemKeywords: ['FMC 15K Sour Blind', 'Cameron 15K NACE', 'NOV Sour'],
    leadTimeDays: 28,
  },
  {
    sku: 'IH-FI-FL-COMP-5K-CAMERON',
    title: 'Companion Flange, API 6BX 5K, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Companion Flange',
    figureClass: '5K',
    workingPressurePsi: 5000,
    pressureClass: '5K',
    serviceClass: 'Standard',
    configuration: 'Threaded × API 6BX flange',
    endConnectionA: 'API 6BX 5K flanged (BX ring groove)',
    endConnectionB: 'NPT or LP threaded (per request)',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in',
    boreId: 'Matches the threaded end',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 5K Companion Flange (threaded × flanged), standard-service rated. Cameron / FMC interchange. Adapts threaded line connections to flanged wellhead stacks.',
    applications: [
      'Threaded-to-flanged wellhead transitions',
      'Choke-line tie-ins',
      'Production-tree side-outs',
    ],
    oemKeywords: ['Cameron 5K Companion', 'FMC 5K', 'Stream-Flo 5K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-FL-COMP-15K-FMC',
    title: 'Companion Flange, API 6BX 15K, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Companion Flange',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Threaded × API 6BX flange',
    endConnectionA: 'API 6BX 15K flanged (BX ring groove)',
    endConnectionB: 'NPT threaded',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'Matches the threaded end',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 15K Companion Flange (NPT × flanged), standard-service rated. FMC / Cameron interchange. The 15K threaded-to-flanged adapter for high-pressure manifolds.',
    applications: [
      'High-pressure threaded-to-flanged tie-ins',
      'Frac-tree threaded ports',
      'Pump-truck high-pressure connections',
    ],
    oemKeywords: ['FMC 15K Companion', 'Cameron 15K', 'NOV 15K'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-FL-WN-5K-STREAMFLO',
    title: 'Weld-Neck Flange, API 6BX 5K, Standard Service',
    brandSlug: 'stream-flo',
    countryOfOrigin: 'Canada',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Weld-Neck Flange',
    figureClass: '5K',
    workingPressurePsi: 5000,
    pressureClass: '5K',
    serviceClass: 'Standard',
    configuration: 'Butt-Weld × API 6BX flange',
    endConnectionA: 'API 6BX 5K flanged (BX ring groove)',
    endConnectionB: 'Butt-Weld neck (XH/XXH schedule per spec)',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'Matches the welded line ID',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 5K Weld-Neck Flange, standard-service rated. Stream-Flo / Cameron interchange. Welds inline to a fabricated piping run while presenting a flanged face for wellhead make-up.',
    applications: [
      'Wellhead-to-piping welded transitions',
      'Christmas-tree fabrication',
      'Production-line tie-ins',
    ],
    oemKeywords: ['Stream-Flo 5K WN', 'Cameron 5K', 'FMC 5K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-FL-WN-10K-CAMERON',
    title: 'Weld-Neck Flange, API 6BX 10K, Standard Service',
    brandSlug: 'cameron',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Weld-Neck Flange',
    figureClass: '10K',
    workingPressurePsi: 10000,
    pressureClass: '10K',
    serviceClass: 'Standard',
    configuration: 'Butt-Weld × API 6BX flange',
    endConnectionA: 'API 6BX 10K flanged (BX ring groove)',
    endConnectionB: 'Butt-Weld neck (XXH schedule typical)',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'Matches the welded line ID',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 10K Weld-Neck Flange, standard-service rated. Cameron / FMC interchange. The 10K welded-to-flanged adapter for fabricated wellhead piping.',
    applications: [
      '10K wellhead piping fabrication',
      'Frac-tree welded transitions',
      'High-pressure surface piping',
    ],
    oemKeywords: ['Cameron 10K WN', 'FMC 10K', 'NOV 10K'],
    leadTimeDays: 14,
  },
  {
    sku: 'IH-FI-FL-WN-15K-FMC',
    title: 'Weld-Neck Flange, API 6BX 15K, Standard Service',
    brandSlug: 'fmc-technologies',
    countryOfOrigin: 'USA',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Weld-Neck Flange',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Butt-Weld × API 6BX flange',
    endConnectionA: 'API 6BX 15K flanged (BX ring groove)',
    endConnectionB: 'Butt-Weld neck (XXH schedule)',
    endConnectionExtra: '',
    availableSizes: '2-1/16 in, 3-1/16 in, 4-1/16 in',
    boreId: 'Matches the welded line ID',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 15K Weld-Neck Flange, standard-service rated. FMC / Cameron interchange. The 15K welded-to-flanged adapter for high-pressure frac-tree piping.',
    applications: [
      '15K frac-tree welded transitions',
      'High-pressure surface tree fabrication',
      'Test-tree welded interfaces',
    ],
    oemKeywords: ['FMC 15K WN', 'Cameron 15K', 'NOV 15K'],
    leadTimeDays: 21,
  },
  {
    sku: 'IH-FI-FL-INST-15K-INDUS',
    title: 'Instrument Flange, API 6BX 15K, Standard Service',
    brandSlug: 'indus',
    countryOfOrigin: 'UAE',
    categorySlug: 'flow-iron-flanges-api',
    flowIronType: 'Instrument Flange',
    figureClass: '15K',
    workingPressurePsi: 15000,
    pressureClass: '15K',
    serviceClass: 'Standard',
    configuration: 'Small-bore instrument tap × API 6BX flange',
    endConnectionA: 'API 6BX 15K flanged (BX ring groove)',
    endConnectionB: '1/2 in or 3/4 in NPT instrument port',
    endConnectionExtra: 'Optional 9/16 in Autoclave port for high-pressure transmitter',
    availableSizes: '1-13/16 in, 2-1/16 in (15K and 20K classes available)',
    boreId: '1/2 in NPT or 9/16 in Autoclave',
    lengthIn: '',
    materialConstruction: STD_MAT,
    apiSpec: 'API 6A',
    materialClass: 'AA',
    temperatureRating: STD_TEMP,
    oneLiner:
      'API 6BX 15K Instrument Flange — small-bore (NPT or Autoclave) port for pressure transmitters, gauges, and temperature probes on flanged wellhead stacks.',
    applications: [
      'Wellhead pressure-transmitter mounts',
      'Christmas-tree gauge ports',
      'Frac-tree instrument tap-offs',
    ],
    oemKeywords: ['FMC Instrument', 'Cameron Instrument', 'NOV Instrument'],
    leadTimeDays: 14,
  },
]

// ── The batch ─────────────────────────────────────────────────────────────

const batch: ImportBatch = {
  meta: {
    id: '2026-05-08-flow-iron-wellhead-0',
    description:
      'Flow Iron & Wellhead — Batch 0: framework + Adapters + Fittings + API Flanges (50 consolidated PDPs).',
  },
  brands: BRANDS,
  categories: CATEGORIES,
  specTemplates: [FLOW_IRON_SPEC],
  navigation: {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'flow-iron-wellhead',
    parentSubLabel: 'Flow Iron',
    createColumnIfMissing: true,
    newColumnLabel: 'Flow Iron & Wellhead',
    newColumnPosition: 10,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: 'Adapters', categorySlug: 'flow-iron-adapters' },
      { label: 'Fittings', categorySlug: 'flow-iron-fittings' },
      { label: 'API Flanges', categorySlug: 'flow-iron-flanges-api' },
    ],
  },
  products: PRODUCTS.map(makeProduct),
}

export default batch
