/**
 * Metallic Hoses — Batch 1 (Exotic Alloys: Hastelloy / Inconel / Monel / Bronze) — 2026-05-08
 *
 * 20 products in `metallic-exotic-alloy-hoses` covering the four exotic-alloy
 * families. Reuses the metallic-hose-spec template (22 fields) and category
 * structure established in Batch 0 (PR #93).
 *
 * Brand split: Thorburn Flex 17, Hose Master 2, Witzenmann 1.
 */
import type {
  CategoryPayload,
  FaqEntry,
  ImportBatch,
  ProductImportPayload,
} from '../import/types'

function escape(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

const FITTING_MATERIAL_PREMIUM = '316L SS standard; matched-alloy fittings (Hastelloy, Inconel, Monel) available for severe service'

type Input = {
  sku: string
  title: string
  brandSlug: string
  countryOfOrigin: string
  subType: string
  hoseFamily: 'Exotic Alloy Corrugated'
  constructionType: 'Annular Corrugated'
  oemPartCode: string
  braidConfiguration: 'Unbraided' | 'Single Braid' | 'Double Braid'
  coreMaterial: 'Hastelloy C276' | 'Inconel 625' | 'Monel 400' | 'Bronze'
  braidMaterial: 'Type 304 SS' | 'Inconel' | 'Monel' | 'Bronze' | 'N/A (Unbraided)'
  endFittingMaterial: string
  nominalIdRange: string
  bendRadiusStaticMm: number
  bendRadiusDynamicMm: number
  liveLengthForVibrationMm: number
  weightKgPerM: number
  maxWorkingPressureBar: number
  minBurstPressureBar: number
  safetyFactor: number
  tempMinC: number
  tempMaxC: number
  iso10380Class: 'PSL 1' | 'PSL 2' | 'PSL 3' | 'N/A'
  pedModule: string
  asmeCompliance: string
  naceMr0175: boolean
  cgaUlChlorineCerts: string
  oneLiner: string
  applications: string[]
  leadTimeDays: number
}

function buildHtml(g: Input): string {
  const apps = g.applications.map((a) => `<li>${escape(a)}</li>`).join('')
  const tempRange = `${g.tempMinC}°C to +${g.tempMaxC}°C`
  const naceLine = g.naceMr0175 ? '<li>NACE MR0175 / ISO 15156 (sour-service compliant)</li>' : ''
  const cgaLine = g.cgaUlChlorineCerts && g.cgaUlChlorineCerts !== 'N/A' && g.cgaUlChlorineCerts !== 'Available on request'
    ? `<li>${escape(g.cgaUlChlorineCerts)}</li>` : ''

  return `<p>The <strong>${escape(g.title)}</strong> is a ${escape(g.coreMaterial)} annular corrugated metallic hose. ${escape(g.subType)}. Working pressure to ${g.maxWorkingPressureBar} bar at the smallest bore; operating temperature ${escape(tempRange)}.</p>
<p>${escape(g.coreMaterial)} delivers the corrosion / temperature envelope that no stainless grade can match: ${g.coreMaterial === 'Hastelloy C276' ? 'severe sour gas, oxidising acids (sulphuric, phosphoric, hot chloride), FGD scrubber service, and chlorine-bleach pulp & paper plants.' : g.coreMaterial === 'Inconel 625' ? 'sustained high-temperature service to +815°C, sour-gas combustion exhaust, marine chloride exposure, and nuclear-rated installations.' : g.coreMaterial === 'Monel 400' ? 'dry-chlorine transfer per Chlorine Institute Pamphlet 6, sea-water and brackish-water service, alkaline streams, and sulphuric acid up to mid-concentration.' : 'galvanic-compatible installations on copper / brass / bronze pipework, decorative service, instrument-line connectors, and copper-plumbed water utility.'}</p>
<h3>Construction</h3>
<ul>
<li>Type: Exotic Alloy Annular — ${escape(g.subType)}</li>
<li>Core material: ${escape(g.coreMaterial)}</li>
<li>Braid: ${escape(g.braidConfiguration)} — ${escape(g.braidMaterial)}</li>
<li>End fitting material: ${escape(g.endFittingMaterial)}</li>
<li>Nominal ID range: ${escape(g.nominalIdRange)}</li>
${g.bendRadiusStaticMm > 0 ? `<li>Bend radius (static / dynamic): ${g.bendRadiusStaticMm} / ${g.bendRadiusDynamicMm} mm minimum</li>` : ''}
${g.weightKgPerM > 0 ? `<li>Weight: ~${g.weightKgPerM} kg/m (size-dependent)</li>` : ''}
</ul>
<h3>Performance</h3>
<p>Working pressure ${g.maxWorkingPressureBar} bar (smallest bore, ${g.braidConfiguration.toLowerCase()} configuration) — derates with increasing diameter and temperature per the OEM datasheet. Burst pressure ${g.minBurstPressureBar} bar minimum, safety factor ${g.safetyFactor}:1 per ISO 10380. Operating temperature ${escape(tempRange)} continuous; intermittent excursions evaluated on request. All assemblies hydrotested at 1.5× working pressure with witness-test certificate available.</p>
<h3>Applications</h3>
<ul>
${apps}
</ul>
<h3>Compliance</h3>
<ul>
<li>ISO 10380:2012 ${escape(g.iso10380Class)} (Corrugated Metal Hoses and Hose Assemblies)</li>
${g.pedModule !== 'None' ? `<li>Pressure Equipment Directive 2014/68/EU ${escape(g.pedModule)}</li>` : ''}
${g.asmeCompliance ? `<li>${escape(g.asmeCompliance)}</li>` : ''}
${naceLine}
${cgaLine}
<li>EN 10204 3.1 / 3.2 mill test reports on request</li>
</ul>
<h3>How to order</h3>
<p>Confirm (a) line working pressure and process medium (specify chemistry, temperature, and any concentration limits — exotic-alloy selection depends critically on the corrosion envelope), (b) operating temperature range, (c) bore size and overall length, (d) end fitting style and matching alloy preference (matched-alloy fittings are recommended for severe service; SS fittings reduce cost where corrosion permits), (e) braid count (drives pressure rating), (f) any required certifications. Indus quotes ex-OEM with mill test reports, alloy-specific certifications, and pre-shipment hydrotest certificates.</p>
<h3>Companion products</h3>
<p>For severe sour service, ask about the matched ${escape(g.coreMaterial)} expansion-joint variant. For high-vibration installations, add a Lock-Section or Armor-Flex external hose guard. For fire-rated runs, the Fry-Sil Fire Jacket / Fire Tape can be added without compromising the alloy core. Indus also supplies matched-alloy ANSI flanges, gaskets (RTJ for high-pressure RF), and stud bolts.</p>`
}

function buildFaqs(g: Input): FaqEntry[] {
  return [
    {
      q: 'What is this exotic-alloy hose used for?',
      a: `${g.oneLiner} ${g.coreMaterial} is selected when a stainless grade can't meet the corrosion / temperature envelope — typical applications include ${g.applications.slice(0, 3).join('; ')}.`,
    },
    {
      q: 'Why ' + g.coreMaterial + ' over stainless steel?',
      a: g.coreMaterial === 'Hastelloy C276'
        ? 'Hastelloy C276 (UNS N10276) is a nickel-molybdenum-chromium-tungsten alloy with exceptional resistance to oxidising and reducing acid environments — including hot chloride, sulphuric, phosphoric, and chlorine-bleach service. It significantly outperforms 316L SS in sour H₂S service and pitting / crevice corrosion in chloride brines.'
        : g.coreMaterial === 'Inconel 625'
          ? 'Inconel 625 (UNS N06625) is a nickel-chromium-molybdenum-niobium alloy with the broadest high-temperature corrosion envelope of any common metallic hose alloy — sustained service to +815°C without significant scaling, plus excellent sour-gas and marine-chloride resistance.'
          : g.coreMaterial === 'Monel 400'
            ? 'Monel 400 (UNS N04400) is a nickel-copper alloy uniquely suited for dry chlorine and chlorinated brines — qualified per Chlorine Institute Pamphlet 6 / Chlorine Institute Specification 135-3. Also excellent for sea-water, brackish-water, alkaline streams, and HF service.'
            : 'Bronze (typically C46400 naval bronze or C92200 leaded tin bronze) provides galvanic compatibility with copper / brass pipework — preventing the bimetallic corrosion that occurs when stainless contacts copper in moist environments. Also used for instrumentation lines and decorative service.',
    },
    {
      q: 'What size range and pressure rating is available?',
      a: `${g.nominalIdRange}. Working pressure varies with bore — at the smallest bore with ${g.braidConfiguration.toLowerCase()} configuration, the rating reaches ${g.maxWorkingPressureBar} bar; at the largest bore the rating drops to a small fraction of that. Refer to the OEM datasheet for per-size pressure curves. ${g.braidConfiguration === 'Double Braid' ? 'Double-braid is the highest-pressure variant of this alloy family.' : g.braidConfiguration === 'Single Braid' ? 'For higher pressures, specify the double-braid variant of the same alloy core.' : 'Unbraided variants are intended as inner elements of jacketed assemblies or for vibration absorption only — not for pressure containment alone.'}`,
    },
    {
      q: 'What is the operating temperature range?',
      a: `${g.tempMinC}°C to +${g.tempMaxC}°C continuous. ${g.coreMaterial === 'Hastelloy C276' ? 'Hastelloy C276 retains good corrosion resistance throughout this range; above +675°C consider Inconel 625 instead.' : g.coreMaterial === 'Inconel 625' ? 'Inconel 625 is the highest-temperature option in the metallic hose lineup — sustained service to +815°C without significant grain growth.' : g.coreMaterial === 'Monel 400' ? 'Monel 400 maintains corrosion resistance to +540°C; above this consider Hastelloy C276 or Inconel 625.' : 'Bronze is suitable to +250°C continuous; for higher temperatures use stainless or exotic alloy alternatives.'} Pressure de-rates at upper temperatures per OEM curves — typically 30-50% reduction at maximum service temperature.`,
    },
    {
      q: 'Is this suitable for sour-service (H₂S) wells?',
      a: g.naceMr0175
        ? `Yes — ${g.coreMaterial} is fully NACE MR0175 / ISO 15156 compliant for sour-service exposure. Body, trim, and braid (where applicable) meet the NACE hardness and chemistry limits. Provide a partial-pressure data sheet with H₂S, CO₂, and chloride values and we will confirm trim suitability and any service limits.`
        : `${g.coreMaterial === 'Bronze' ? 'No — bronze is NOT recommended for sour-service. The H₂S resistance is poor and bronze is not NACE MR0175 listed.' : 'For sour-service, specify the NACE MR0175 compliant variant on the RFQ — it requires confirmation of the partial-pressure envelope.'}`,
    },
    {
      q: 'What end fittings are recommended?',
      a: `${g.endFittingMaterial}. ${g.coreMaterial === 'Bronze' ? 'For galvanic-compatible installations, use bronze or brass fittings.' : 'Matched-alloy fittings (' + g.coreMaterial + ' for the body / weld zone) are recommended for severe service — they eliminate the alloy mismatch at the joint that is otherwise the most common failure mode. SS fittings are an acceptable cost-reduction where corrosion permits (typically the cooler / lower-stress end of the assembly).'} Common end styles: NPT / BSPP threaded, ANSI 150-1500# RF flanged, DIN PN10-PN40, sanitary tri-clamp, butt-weld.`,
    },
    {
      q: 'What is the lead time?',
      a: `Typical lead time ${g.leadTimeDays} working days ex-works OEM. ${g.coreMaterial === 'Hastelloy C276' || g.coreMaterial === 'Inconel 625' ? 'Hastelloy and Inconel mill stock is generally on minimum-quantity allocation — non-stock sizes typically build to order with 6-12 week lead times depending on the OEM. NACE-certified variants add 2-3 weeks for material certification.' : g.coreMaterial === 'Monel 400' ? 'Monel mill stock is regularly available; NACE / Chlorine-Institute certified variants add 1-2 weeks for material certification.' : 'Bronze is regularly stocked; PSL 3 monogrammed variants add 1-2 weeks.'}`,
    },
    {
      q: 'What standards and certifications are supplied?',
      a: `ISO 10380:2012 ${g.iso10380Class}.${g.pedModule !== 'None' ? ` PED 2014/68/EU ${g.pedModule}.` : ''}${g.asmeCompliance ? ` ${g.asmeCompliance}.` : ''}${g.naceMr0175 ? ' NACE MR0175 / ISO 15156 sour-service compliance certificate.' : ''}${g.cgaUlChlorineCerts && g.cgaUlChlorineCerts !== 'N/A' ? ' Plus: ' + g.cgaUlChlorineCerts + '.' : ''} EN 10204 3.1 / 3.2 mill test reports for body and braid alloy. Pressure-test certificate (1.5× working pressure). API monogram on request for monogrammed mill heats.`,
    },
  ]
}

function makeProduct(g: Input): ProductImportPayload {
  return {
    sku: g.sku,
    title: g.title,
    brandSlug: g.brandSlug,
    categorySlug: 'metallic-exotic-alloy-hoses',
    specTemplateSlug: 'metallic-hose-spec',
    status: 'active',
    unitOfMeasure: 'metre',
    listPriceCurrency: 'AED',
    stockQty: 0,
    leadTimeDays: g.leadTimeDays,
    countryOfOrigin: g.countryOfOrigin,
    descriptionShort: g.oneLiner.slice(0, 500),
    descriptionLong: buildHtml(g),
    specs: {
      hose_family: g.hoseFamily,
      construction_type: g.constructionType,
      oem_part_code: g.oemPartCode,
      braid_configuration: g.braidConfiguration,
      core_material: g.coreMaterial,
      braid_material: g.braidMaterial,
      end_fitting_material: g.endFittingMaterial,
      nominal_id_range: g.nominalIdRange,
      bend_radius_static_mm: g.bendRadiusStaticMm,
      bend_radius_dynamic_mm: g.bendRadiusDynamicMm,
      live_length_for_vibration_mm: g.liveLengthForVibrationMm,
      weight_kg_per_m: g.weightKgPerM,
      max_working_pressure_bar: g.maxWorkingPressureBar,
      min_burst_pressure_bar: g.minBurstPressureBar,
      safety_factor: g.safetyFactor,
      temp_min_c: g.tempMinC,
      temp_max_c: g.tempMaxC,
      iso_10380_class: g.iso10380Class,
      ped_module: g.pedModule,
      asme_compliance: g.asmeCompliance,
      nace_mr0175: g.naceMr0175,
      cga_ul_chlorine_certs: g.cgaUlChlorineCerts,
    },
    faqs: buildFaqs(g),
    seoTitle: `${g.title} | Indus Hydraulics`.slice(0, 200),
    seoDescription: g.oneLiner.slice(0, 500),
    focusKeyword: `${g.coreMaterial.toLowerCase()} metallic hose ${g.maxWorkingPressureBar} bar`.slice(0, 120),
  }
}

const ASME_HASTELLOY = 'ASME B31.3 Class 2 (Hastelloy)'
const ASME_INCONEL = 'ASME B31.3 Class 2 (Inconel) / Section IX welding'
const ASME_MONEL = 'ASME B31.3 (Monel)'
const ASME_BRONZE = 'ASME B31.3 (Bronze)'

const PRODUCTS: Input[] = [
  // ── Hastelloy C276 (7) ──────────────────────────────────────────────────
  {
    sku: 'IH-MH-THORBURN-H95-HASTELLOY',
    title: 'Thorburn H95 — Hastelloy C276 Annular, Unbraided Inner Core',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 unbraided annular inner core',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'H95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.18,
    maxWorkingPressureBar: 12,
    minBurstPressureBar: 48,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 675,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn H95 Hastelloy C276 unbraided annular inner core. Severe corrosion service — hot chloride, oxidising acids, FGD scrubber, sour gas. Premium nickel-molybdenum-chromium alloy.',
    applications: ['Severe sour-gas processing', 'Hot chloride streams (>+150°C)', 'FGD scrubber acidic condensate', 'Pulp & paper bleach plants (chlorine-rich)'],
    leadTimeDays: 56,
  },
  {
    sku: 'IH-MH-THORBURN-H96-HASTELLOY',
    title: 'Thorburn H96 — Hastelloy C276 Annular, Single Hastelloy Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 single-braid annular (matched alloy)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'H96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Inconel',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.32,
    maxWorkingPressureBar: 140,
    minBurstPressureBar: 560,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 675,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn H96 Hastelloy C276 annular hose with matched-alloy single braid. Working pressure to 140 bar. Premium severe-corrosion service with full alloy compatibility.',
    applications: ['Severe sour-gas pressure-controlled lines', 'Acidic process plant transfer', 'High-cycle FGD scrubber service', 'Hot chloride process at pressure'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-THORBURN-H96Z-HASTELLOY',
    title: 'Thorburn H96Z — Hastelloy C276 Annular, Double Hastelloy Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 double-braid annular (matched alloy)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'H96Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Inconel',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.45,
    maxWorkingPressureBar: 200,
    minBurstPressureBar: 800,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 675,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn H96Z Hastelloy C276 annular with double matched-alloy braid. Working pressure to 200 bar. Highest-pressure Hastelloy variant — severe HP corrosion service.',
    applications: ['HP severe sour-gas isolation', 'High-pressure FGD systems', 'HP chlorine-bleach plants', 'HP acidic process plant'],
    leadTimeDays: 84,
  },
  {
    sku: 'IH-MH-THORBURN-HS95-HASTELLOY',
    title: 'Thorburn HS95 — Hastelloy C276 Annular with SS304 Braid (Cost-Effective)',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 unbraided inner with SS304 outer braid',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'HS95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard (Hastelloy fittings on request)',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.16,
    maxWorkingPressureBar: 12,
    minBurstPressureBar: 48,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn HS95 Hastelloy C276 unbraided inner with SS304 outer braid. Cost-effective alloy choice when the corrosion exposure is on the wetted side only.',
    applications: ['Cost-conscious sour-gas service (wetted-side exotic only)', 'Inner element of jacketed Hastelloy assemblies', 'Vibration-absorbing inner core', 'Lower-pressure sour service'],
    leadTimeDays: 49,
  },
  {
    sku: 'IH-MH-THORBURN-HS96-HASTELLOY',
    title: 'Thorburn HS96 — Hastelloy C276 Annular with SS304 Single Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 single SS304 braid (cost-effective braid)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'HS96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.30,
    maxWorkingPressureBar: 130,
    minBurstPressureBar: 520,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn HS96 Hastelloy C276 annular hose with single SS304 braid. Working pressure to 130 bar. Cost-effective for service where the braid stays cooler than the core.',
    applications: ['Process-plant sour gas (cooler external)', 'Insulated Hastelloy lines', 'Lower-temperature severe-corrosion service', 'Cost-managed sour-gas projects'],
    leadTimeDays: 56,
  },
  {
    sku: 'IH-MH-THORBURN-HS96Z-HASTELLOY',
    title: 'Thorburn HS96Z — Hastelloy C276 Annular with SS304 Double Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Hastelloy C276 double SS304 braid (cost-effective braid)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'HS96Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.42,
    maxWorkingPressureBar: 185,
    minBurstPressureBar: 740,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn HS96Z Hastelloy C276 annular with double SS304 braid. Working pressure to 185 bar. Cost-effective HP variant for severe-corrosion service.',
    applications: ['HP sour-gas isolation (cost-managed)', 'Severe-corrosion HP process', 'Acidic plant HP service', 'Insulated HP Hastelloy lines'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-HOSE-MASTER-HASTELLOY',
    title: 'Hose Master Hastelloy C276 Annular Hose (Annuflex Series)',
    brandSlug: 'hose-master',
    countryOfOrigin: 'USA',
    subType: 'Hastelloy C276 single-braid annular (Hose Master Annuflex)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'ANNUFLEX-C276',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Hastelloy C276',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard; Hastelloy fittings on request',
    nominalIdRange: 'DN 13 (1/2") to DN 200 (8")',
    bendRadiusStaticMm: 50,
    bendRadiusDynamicMm: 200,
    liveLengthForVibrationMm: 130,
    weightKgPerM: 0.32,
    maxWorkingPressureBar: 125,
    minBurstPressureBar: 500,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_HASTELLOY,
    naceMr0175: true,
    cgaUlChlorineCerts: '',
    oneLiner: 'Hose Master Hastelloy C276 annular hose (Annuflex series). US-market premium severe-corrosion alternative to Thorburn — same alloy chemistry, North American supply chain.',
    applications: ['North American severe sour-gas projects', 'US chemical / refinery service', 'Acidic process plant', 'Hot chloride streams'],
    leadTimeDays: 56,
  },
  // ── Inconel 625 (6) ──────────────────────────────────────────────────────
  {
    sku: 'IH-MH-THORBURN-I95-INCONEL',
    title: 'Thorburn I95 — Inconel 625 Annular, Unbraided Inner Core',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Inconel 625 unbraided annular inner core',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'I95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.18,
    maxWorkingPressureBar: 13,
    minBurstPressureBar: 52,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 815,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_INCONEL,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn I95 Inconel 625 unbraided annular inner core. Highest-temperature option — sustained service to +815°C. Combustion exhaust, marine, nuclear-rated installations.',
    applications: ['High-temperature combustion exhaust (>+650°C)', 'Marine chloride exposure at temperature', 'Nuclear-rated process lines (CRN approval)', 'Inner element of HT jacketed assemblies'],
    leadTimeDays: 56,
  },
  {
    sku: 'IH-MH-THORBURN-I96-INCONEL',
    title: 'Thorburn I96 — Inconel 625 Annular, Single Inconel Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Inconel 625 single Inconel braid (matched alloy)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'I96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'Inconel',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.34,
    maxWorkingPressureBar: 150,
    minBurstPressureBar: 600,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 815,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: ASME_INCONEL,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn I96 Inconel 625 annular with matched Inconel braid. Working pressure to 150 bar. High-temperature pressure-rated service to +815°C.',
    applications: ['HT combustion exhaust at pressure', 'Sour-gas processing at high temperature', 'Nuclear-rated process plant', 'HT marine systems'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-THORBURN-I96Z-INCONEL',
    title: 'Thorburn I96Z — Inconel 625 Annular, Double Inconel Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Inconel 625 double Inconel braid (matched alloy)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'I96Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'Inconel',
    endFittingMaterial: FITTING_MATERIAL_PREMIUM,
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.48,
    maxWorkingPressureBar: 215,
    minBurstPressureBar: 860,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 815,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: ASME_INCONEL,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn I96Z Inconel 625 annular with double matched Inconel braid. Working pressure to 215 bar. Highest-pressure HT-rated metallic hose available.',
    applications: ['HP HT combustion service', 'HP sour-gas at temperature', 'HP nuclear-rated installations', 'HP severe-service marine'],
    leadTimeDays: 84,
  },
  {
    sku: 'IH-MH-THORBURN-IS95-INCONEL',
    title: 'Thorburn IS95 — Inconel 625 Annular with SS304 Outer Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Inconel 625 unbraided inner with SS304 outer braid',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'IS95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard (Inconel fittings on request)',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.16,
    maxWorkingPressureBar: 13,
    minBurstPressureBar: 52,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_INCONEL,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn IS95 Inconel 625 unbraided inner with SS304 outer braid. Cost-effective when the corrosion / temperature exposure is on the wetted side only.',
    applications: ['Cost-managed HT sour gas (wetted-side Inconel only)', 'Inner element of jacketed HT assemblies', 'HT vibration-absorbing inner core', 'Lower-pressure HT service'],
    leadTimeDays: 49,
  },
  {
    sku: 'IH-MH-THORBURN-IS96-INCONEL',
    title: 'Thorburn IS96 — Inconel 625 Annular with SS304 Single Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Inconel 625 single SS304 braid (cost-effective braid)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'IS96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'Type 304 SS',
    endFittingMaterial: '316L SS standard',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.31,
    maxWorkingPressureBar: 140,
    minBurstPressureBar: 560,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_INCONEL,
    naceMr0175: true,
    cgaUlChlorineCerts: 'CSA B51',
    oneLiner: 'Thorburn IS96 Inconel 625 annular with single SS304 braid. Working pressure to 140 bar. Cost-effective for service where the braid stays cooler.',
    applications: ['HT sour gas (insulated outer)', 'Combustion lines with cool jacket', 'Cost-managed HT projects', 'HT process at moderate pressure'],
    leadTimeDays: 56,
  },
  {
    sku: 'IH-MH-WITZENMANN-INCONEL',
    title: 'Witzenmann Inconel 625 Annular Hose (HYDRA Series)',
    brandSlug: 'witzenmann',
    countryOfOrigin: 'Germany',
    subType: 'Inconel 625 single-braid annular (Witzenmann HYDRA)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'HYDRA-Inconel-625',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Inconel 625',
    braidMaterial: 'Inconel',
    endFittingMaterial: 'DIN 1.4571 / 316Ti SS standard; Inconel fittings on request',
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 35,
    bendRadiusDynamicMm: 175,
    liveLengthForVibrationMm: 120,
    weightKgPerM: 0.34,
    maxWorkingPressureBar: 145,
    minBurstPressureBar: 580,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 815,
    iso10380Class: 'PSL 3',
    pedModule: 'Module H',
    asmeCompliance: 'EN 13480 / ASME B31.3 (Inconel)',
    naceMr0175: true,
    cgaUlChlorineCerts: 'TÜV / CE marking',
    oneLiner: 'Witzenmann HYDRA Inconel 625 annular hose with matched Inconel braid. German-engineered premium for HT chemical and aerospace service. CE-marked.',
    applications: ['European chemical / petrochem HT service', 'Aerospace HT exhaust systems', 'Power generation HT lines', 'Premium nuclear-rated EU installations'],
    leadTimeDays: 84,
  },
  // ── Monel 400 (4) ───────────────────────────────────────────────────────
  {
    sku: 'IH-MH-THORBURN-M95-MONEL',
    title: 'Thorburn M95 — Monel 400 Annular, Unbraided Inner Core',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Monel 400 unbraided annular inner core',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'M95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Monel 400',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Monel 400 fittings standard for Cl₂ service',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.18,
    maxWorkingPressureBar: 10,
    minBurstPressureBar: 40,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 1',
    pedModule: 'Module D',
    asmeCompliance: ASME_MONEL,
    naceMr0175: false,
    cgaUlChlorineCerts: 'Chlorine Institute Pamphlet 6 compliant; CSA B51',
    oneLiner: 'Thorburn M95 Monel 400 unbraided annular inner core. Dry chlorine, sea water, alkaline service. Per Chlorine Institute Pamphlet 6.',
    applications: ['Dry chlorine vapor transfer (Pamphlet 6)', 'Sea-water cooling (corrosion-immune)', 'Sodium hydroxide / KOH transfer', 'HF acid service'],
    leadTimeDays: 49,
  },
  {
    sku: 'IH-MH-THORBURN-M96-MONEL',
    title: 'Thorburn M96 — Monel 400 Annular, Single Monel Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Monel 400 single matched-alloy braid (chlorine-rated)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'M96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Monel 400',
    braidMaterial: 'Monel',
    endFittingMaterial: 'Monel 400 fittings standard',
    nominalIdRange: 'DN 6 (1/4") to DN 250 (10")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.32,
    maxWorkingPressureBar: 100,
    minBurstPressureBar: 400,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 1',
    pedModule: 'Module D',
    asmeCompliance: ASME_MONEL,
    naceMr0175: false,
    cgaUlChlorineCerts: 'Chlorine Institute Pamphlet 6 + Specification 135-3; CSA B51',
    oneLiner: 'Thorburn M96 Monel 400 annular with matched Monel braid. Working pressure to 100 bar. Premium Cl₂-rated transfer hose per Chlorine Institute Spec 135-3.',
    applications: ['Liquid chlorine transfer (Spec 135-3)', 'Sea-water service at pressure', 'Caustic alkaline transfer', 'HF process plant'],
    leadTimeDays: 70,
  },
  {
    sku: 'IH-MH-THORBURN-M96Z-MONEL',
    title: 'Thorburn M96Z — Monel 400 Annular, Double Monel Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Monel 400 double matched-alloy braid (chlorine-rated)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'M96Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Monel 400',
    braidMaterial: 'Monel',
    endFittingMaterial: 'Monel 400 fittings standard',
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 30,
    bendRadiusDynamicMm: 150,
    liveLengthForVibrationMm: 110,
    weightKgPerM: 0.45,
    maxWorkingPressureBar: 145,
    minBurstPressureBar: 580,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 2',
    pedModule: 'Module H',
    asmeCompliance: ASME_MONEL,
    naceMr0175: false,
    cgaUlChlorineCerts: 'Chlorine Institute Pamphlet 6 + Specification 135-3; CSA B51',
    oneLiner: 'Thorburn M96Z Monel 400 annular with double matched Monel braid. Working pressure to 145 bar. HP Cl₂-transfer for severe-service rail-loading and tanker-truck.',
    applications: ['HP liquid chlorine rail / truck loading', 'HP sea-water injection', 'HP sodium hydroxide transfer', 'HP HF acid distribution'],
    leadTimeDays: 84,
  },
  {
    sku: 'IH-MH-HOSE-MASTER-MONEL',
    title: 'Hose Master Monel 400 Annular Hose (Annuflex Series)',
    brandSlug: 'hose-master',
    countryOfOrigin: 'USA',
    subType: 'Monel 400 single matched-alloy braid (Hose Master Annuflex)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'ANNUFLEX-MONEL',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Monel 400',
    braidMaterial: 'Monel',
    endFittingMaterial: 'Monel 400 fittings standard',
    nominalIdRange: 'DN 13 (1/2") to DN 200 (8")',
    bendRadiusStaticMm: 50,
    bendRadiusDynamicMm: 200,
    liveLengthForVibrationMm: 130,
    weightKgPerM: 0.31,
    maxWorkingPressureBar: 95,
    minBurstPressureBar: 380,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 540,
    iso10380Class: 'PSL 1',
    pedModule: 'None',
    asmeCompliance: ASME_MONEL,
    naceMr0175: false,
    cgaUlChlorineCerts: 'Chlorine Institute Pamphlet 6',
    oneLiner: 'Hose Master Monel 400 annular hose with matched Monel braid. US-market Cl₂-rated alternative to Thorburn — same alloy chemistry, North American supply.',
    applications: ['US chlorine plant transfer', 'North American sea-water service', 'US chlor-alkali production', 'North American HF acid service'],
    leadTimeDays: 56,
  },
  // ── Bronze (3) ──────────────────────────────────────────────────────────
  {
    sku: 'IH-MH-THORBURN-B95-BRONZE',
    title: 'Thorburn B95 — Bronze Annular, Unbraided Inner Core',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Bronze unbraided annular inner core (galvanic compatible)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'B95',
    braidConfiguration: 'Unbraided',
    coreMaterial: 'Bronze',
    braidMaterial: 'N/A (Unbraided)',
    endFittingMaterial: 'Bronze or brass fittings (galvanic compatibility)',
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 25,
    bendRadiusDynamicMm: 125,
    liveLengthForVibrationMm: 100,
    weightKgPerM: 0.20,
    maxWorkingPressureBar: 8,
    minBurstPressureBar: 32,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 250,
    iso10380Class: 'PSL 1',
    pedModule: 'None',
    asmeCompliance: ASME_BRONZE,
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn B95 Bronze unbraided annular inner core. Galvanic compatibility with copper / brass pipework. Decorative and instrument-line service.',
    applications: ['Copper / brass pipework retrofits', 'Decorative architectural installations', 'Instrument-line connectors', 'Marine copper-plumbed systems'],
    leadTimeDays: 35,
  },
  {
    sku: 'IH-MH-THORBURN-B96-BRONZE',
    title: 'Thorburn B96 — Bronze Annular, Single Bronze Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Bronze single matched-alloy braid (galvanic compatible)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'B96',
    braidConfiguration: 'Single Braid',
    coreMaterial: 'Bronze',
    braidMaterial: 'Bronze',
    endFittingMaterial: 'Bronze or brass fittings (galvanic compatibility)',
    nominalIdRange: 'DN 6 (1/4") to DN 200 (8")',
    bendRadiusStaticMm: 25,
    bendRadiusDynamicMm: 125,
    liveLengthForVibrationMm: 100,
    weightKgPerM: 0.34,
    maxWorkingPressureBar: 50,
    minBurstPressureBar: 200,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 250,
    iso10380Class: 'PSL 1',
    pedModule: 'None',
    asmeCompliance: ASME_BRONZE,
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn B96 Bronze annular with matched Bronze braid. Working pressure to 50 bar. Galvanic-compatible utility for copper-plumbed installations.',
    applications: ['Copper utility piping connectors', 'Marine copper-system flexibility', 'Decorative bronze installations', 'Instrument-line at pressure'],
    leadTimeDays: 49,
  },
  {
    sku: 'IH-MH-THORBURN-B96Z-BRONZE',
    title: 'Thorburn B96Z — Bronze Annular, Double Bronze Braid',
    brandSlug: 'thorburn-flex',
    countryOfOrigin: 'Canada',
    subType: 'Bronze double matched-alloy braid (galvanic compatible HP)',
    hoseFamily: 'Exotic Alloy Corrugated',
    constructionType: 'Annular Corrugated',
    oemPartCode: 'B96Z',
    braidConfiguration: 'Double Braid',
    coreMaterial: 'Bronze',
    braidMaterial: 'Bronze',
    endFittingMaterial: 'Bronze or brass fittings (galvanic compatibility)',
    nominalIdRange: 'DN 6 (1/4") to DN 150 (6")',
    bendRadiusStaticMm: 25,
    bendRadiusDynamicMm: 125,
    liveLengthForVibrationMm: 100,
    weightKgPerM: 0.46,
    maxWorkingPressureBar: 75,
    minBurstPressureBar: 300,
    safetyFactor: 4,
    tempMinC: -200,
    tempMaxC: 250,
    iso10380Class: 'PSL 1',
    pedModule: 'None',
    asmeCompliance: ASME_BRONZE,
    naceMr0175: false,
    cgaUlChlorineCerts: '',
    oneLiner: 'Thorburn B96Z Bronze annular with double matched Bronze braid. Working pressure to 75 bar. HP galvanic-compatible utility for copper-plumbed HP systems.',
    applications: ['HP copper utility piping', 'HP marine copper-system flexibility', 'HP decorative bronze HP installations', 'HP brass pipework retrofits'],
    leadTimeDays: 63,
  },
]

const batch: ImportBatch = {
  meta: {
    id: '2026-05-08-metallic-hoses-1-exotic-alloys',
    description:
      'Metallic Hoses Batch 1 — 20 exotic-alloy products (Hastelloy C276 7, Inconel 625 6, Monel 400 4, Bronze 3) under metallic-exotic-alloy-hoses category. Brand split: Thorburn 17, Hose Master 2, Witzenmann 1.',
  },

  brands: [],
  categories: [] as CategoryPayload[],
  specTemplates: [],
  products: PRODUCTS.map(makeProduct),
}

export default batch
