/**
 * MSI catalogue gap-fill — 2026-05-11
 *
 * Adds 6 new top-level categories + 51 sub-categories + 52 representative
 * RFQ-style products covering Cementing / Stimulation / Fracturing / Well
 * Testing / Drilling & Workover Systems / Instrumentation & Controls — plus
 * a Restraint Systems sub-category under existing Oilfield Valve Accessories.
 *
 * Skipped — already covered by existing Indus catalogue:
 *   - Treating Iron (Flow Iron & Wellhead, 129 products)
 *   - API 6A Gate Valves, Choke Valves, Butterfly Valves, SSV (Oilfield Valves, 109 products)
 *   - Choke Manifold, Diverter Manifold (Flow Iron → Manifolds)
 *   - Choke & Kill Manifold (BOP)
 *   - Isolation Needle Valves (Oilfield Instrumentation Valves)
 *   - Recertification / Refurbishment services (service_cases — 20 published)
 *
 * All products branded "indus" (house brand), status=active, AED, EA.
 *
 * ── ALREADY APPLIED — DO NOT RE-RUN ────────────────────────────────────────
 *
 * This batch was imported into production on 2026-05-11; the file itself was
 * only merged on 2026-08-14. Verified against prod at merge time: all 58
 * categories and all 52 products present, 6 megamenu columns and 53 leaf
 * links live.
 *
 * Re-running is NOT harmless. Categories and products are idempotent upserts,
 * but the `navigation` block below routes through `replacePlaceholderLeaves`,
 * which only deletes *placeholder* leaves. The live leaves are real category
 * links, so a re-run reports "deleted 0, inserted 51" and DUPLICATES every
 * MSI entry in the megamenu.
 *
 * Kept as the record of what was imported, matching the other files in this
 * directory. If it ever genuinely needs replaying, clear the affected nav
 * leaves first and confirm with --dry-run that deleted/inserted balance.
 *
 * Run (only against a fresh database):
 *   pnpm --filter @indus/db db:import src/imports/2026-05-11-msi-catalogue-expansion.ts --dry-run
 *   pnpm --filter @indus/db db:import src/imports/2026-05-11-msi-catalogue-expansion.ts
 */
import type {
  CategoryPayload,
  ImportBatch,
  NavReplaceLeavesConfig,
  ProductImportPayload,
} from '../import/types'

const COMMON_PRODUCT: Pick<
  ProductImportPayload,
  'brandSlug' | 'status' | 'unitOfMeasure' | 'listPriceCurrency' | 'countryOfOrigin' | 'stockQty'
> = {
  brandSlug: 'indus',
  status: 'active',
  unitOfMeasure: 'each',
  listPriceCurrency: 'AED',
  countryOfOrigin: 'United Arab Emirates',
  // Engineered-to-order packages — quoted, never stocked. Matches the 0 these
  // rows carry in production.
  stockQty: 0,
}

const categories: CategoryPayload[] = [
  { slug: 'cementing-equipment', name: 'Cementing Equipment', position: 12, shortDescription: 'Skid-, trailer- and truck-mounted cementing packages — single & multiplex skid, ATEX/Zone 2, CE & GOST options, automatic density control, data acquisition.', seoTitle: 'Cementing Equipment & Packages — Cementing Units, Batch Mixers, Silos', seoDescription: 'Engineered cementing fleet equipment for onshore & offshore well services: cementing units, batch mixers, on-the-fly mixers, cement silos, cutting bottles, dust collectors, rock catchers.', isPublished: true },
  { slug: 'cementing-units', name: 'Cementing Units', parentSlug: 'cementing-equipment', position: 0, shortDescription: 'Single or twin pump cementing units on skid, trailer or truck. ATEX / Zone 2, automatic density control, data acquisition, HVAC / pre-heating optional.', isPublished: true },
  { slug: 'cementing-batch-mixer', name: 'Batch Mixers (Cement)', parentSlug: 'cementing-equipment', position: 1, shortDescription: 'Twin-tank cement batch mixers, 2×50 BBL to 2×125 BBL, sloped conical bottom + siphon, optional Coriolis density meter, ATEX motors.', isPublished: true },
  { slug: 'cementing-on-the-fly-mixer', name: 'On-The-Fly Mixers', parentSlug: 'cementing-equipment', position: 2, shortDescription: 'On-the-fly cement slurry mixers with 20-BBL surge tank and 2.5 SG max density, manual or automatic density control.', isPublished: true },
  { slug: 'cementing-silos', name: 'Cement Silos', parentSlug: 'cementing-equipment', position: 3, shortDescription: 'Cylindrical cement silos 1,200 / 1,500 / 1,900+ cu.ft. on L-frame for horizontal transport and vertical install. Aeration manifold, load cells, digital display.', isPublished: true },
  { slug: 'cementing-cutting-bottle', name: 'Cutting Bottles', parentSlug: 'cementing-equipment', position: 4, shortDescription: 'Cement big-bag cutting bottles with four-bladed needle, hopper, aeration nozzles, and pneumatic or electric top butterfly valve.', isPublished: true },
  { slug: 'cementing-dust-collector', name: 'Dust Collectors', parentSlug: 'cementing-equipment', position: 5, shortDescription: 'Velocity-drop + gravity dust collectors with synthetic fabric bag and clamps. Adjustable vessel volume.', isPublished: true },
  { slug: 'cementing-rock-catcher', name: 'Rock Catchers', parentSlug: 'cementing-equipment', position: 6, shortDescription: 'Inline bulk-line rock catchers with stainless steel screen + dump line. Selectable mesh size.', isPublished: true },
  { slug: 'stimulation-equipment', name: 'Stimulation Equipment', position: 13, shortDescription: 'Acid / N₂ stimulation packages — nitrogen pumping units, transfer pumps, acid tanks, stimulation batch mixers and pumping units. ATEX, CE, GOST.', seoTitle: 'Stimulation Equipment — Nitrogen Units, Acid Tanks, Pumping Units', seoDescription: 'Engineered stimulation fleet equipment: N₂ pumping units up to 15,000 psi, FRP-lined acid tanks, stimulation batch mixers and triplex pumping units for well services.', isPublished: true },
  { slug: 'stimulation-nitrogen-unit', name: 'Nitrogen (N₂) Pumping Units', parentSlug: 'stimulation-equipment', position: 0, shortDescription: 'Cryogenic N₂ pumping units in 90K to 1000K capacity, up to 15,000 psi. Skid, trailer or truck-mounted modular design.', isPublished: true },
  { slug: 'stimulation-transfer-pump', name: 'Transfer Pumps (Stimulation)', parentSlug: 'stimulation-equipment', position: 1, shortDescription: 'FRP-lined, stainless or Teflon transfer pumps — centrifugal, multistage, membrane, progressive cavity, reciprocating. Acid- and brine-rated.', isPublished: true },
  { slug: 'stimulation-acid-tanks', name: 'Acid Tanks', parentSlug: 'stimulation-equipment', position: 2, shortDescription: 'FRP-lined steel or full FRP acid tanks, ISO frame or trailer, acid-resistant piping, dangerous-goods certification.', isPublished: true },
  { slug: 'stimulation-batch-mixers', name: 'Stimulation Batch Mixers', parentSlug: 'stimulation-equipment', position: 3, shortDescription: 'Acid / brine batch mixers with FRP or SS wetted parts, PTFE-lined butterfly valves, ATEX motors.', isPublished: true },
  { slug: 'stimulation-pumping-units', name: 'Stimulation Pumping Units', parentSlug: 'stimulation-equipment', position: 4, shortDescription: 'Single or twin triplex pumping units for stimulation service (water, acid, mud), 10K–15K psi. Skid / trailer / truck.', isPublished: true },
  { slug: 'fracturing-equipment', name: 'Fracturing Equipment', position: 14, shortDescription: 'Frac fleet equipment — pumpers up to 3,000 HP, transfer pumps, missiles, sand silos, blenders, hydration units, LAS, data vans, and frac tanks.', seoTitle: 'Fracturing Equipment — Frac Pumpers, Blenders, Missiles, Hydration Units', seoDescription: 'Engineered fracturing fleet equipment: frac pumpers up to 3,000 HP, MFR-series blenders, hydration units, frac sand silos (Sand Chief), LAS, missiles, data vans, frac tanks.', isPublished: true },
  { slug: 'frac-pumpers', name: 'Frac Pumpers', parentSlug: 'fracturing-equipment', position: 0, shortDescription: 'Frac pumpers up to 3,000 HP on skid, trailer or truck. Standalone or fleet-networked, DNV-certified offshore modules.', isPublished: true },
  { slug: 'frac-transfer-pumps', name: 'Frac Transfer Pumps', parentSlug: 'fracturing-equipment', position: 1, shortDescription: 'Centrifugal transfer pumps to feed frac pumpers from blender or supply tanks. Skid, trailer or truck-mounted; electric, diesel or hydraulic drive.', isPublished: true },
  { slug: 'frac-manifold', name: 'Frac Manifolds / Missiles', parentSlug: 'fracturing-equipment', position: 2, shortDescription: 'Frac iron missiles accommodating up to 20 pumpers per side. 3" or 4" HP discharge, Fig.1502 / Clamp Hub. 15K STD.', isPublished: true },
  { slug: 'frac-sand-silos', name: 'Frac Sand Silos / Sand Chief', parentSlug: 'fracturing-equipment', position: 3, shortDescription: 'Frac sand storage — round / square, vertical / horizontal, hydraulic tilt or sand-belt conveyor delivery.', isPublished: true },
  { slug: 'frac-blender', name: 'Frac Blenders (MFR Series)', parentSlug: 'fracturing-equipment', position: 4, shortDescription: 'MFR-series frac blenders. MFR-10/15/20 for gravel-pack (10–20 BBL/min) and MFR-50/100 for fracturing (50–100 BBL/min). Auto density / tub-level control.', isPublished: true },
  { slug: 'frac-hydration-unit', name: 'Frac Hydration Units', parentSlug: 'fracturing-equipment', position: 5, shortDescription: 'Gel hydration units — 200 BBL hydration tank, dry + 4 liquid SS316 chemical tanks, 30-120 BBL/min mixing, optional viscosity / pH / density meters.', isPublished: true },
  { slug: 'frac-las', name: 'Frac LAS (Liquid Additive System)', parentSlug: 'fracturing-equipment', position: 6, shortDescription: 'Frac Liquid Additive Systems with up to 12 chemical tote tanks, dosing pumps, optional mass flowmeters, heating, agitators.', isPublished: true },
  { slug: 'frac-data-van', name: 'Frac Data Vans', parentSlug: 'fracturing-equipment', position: 7, shortDescription: 'Fleet-control data vans — HVAC, flooring, desks, multi-screen visualization, wired / wifi fleet I/O.', isPublished: true },
  { slug: 'frac-tanks', name: 'Frac Tanks', parentSlug: 'fracturing-equipment', position: 8, shortDescription: 'Frac fluid storage tanks — engineered to client volume and chemistry, road-registered trailers, ISO frame skids.', isPublished: true },
  { slug: 'well-testing-equipment', name: 'Well Testing Equipment', position: 15, shortDescription: 'Surface well-testing packages — 3-phase separators, MPFM systems, surge tanks, KO drums, flare stacks, test pumps, sand filters, ESD panels, data headers, piping packages.', seoTitle: 'Well Testing Equipment — Separators, MPFM, Flare Stacks, Surge Tanks', seoDescription: 'Engineered well testing & EPF surface packages: 3-phase separators, MPFM systems, surge tanks, KO drums, flare stacks, test pumps, sand filters, ESD panels, data headers, piping packages.', isPublished: true },
  { slug: 'wt-3-phase-separator', name: '3-Phase Separators', parentSlug: 'well-testing-equipment', position: 0, shortDescription: 'Well-testing multiphase separators 250 / 900 / 1,440 / 2,160 psi. ASME U-stamp, NACE MR-0175, Daniel orifice + PSV.', isPublished: true },
  { slug: 'wt-mpfm-system', name: 'MPFM Systems', parentSlug: 'well-testing-equipment', position: 1, shortDescription: 'Complete Multi-Phase Flow Meter systems with upstream / downstream piping & manifolds. Haimo, Agar, Medeng, ABB, Roxar-Emerson.', isPublished: true },
  { slug: 'wt-surge-tank', name: 'Surge Tanks', parentSlug: 'well-testing-equipment', position: 2, shortDescription: 'Dual-compartment well-testing surge tanks. ASME U-certified, hi-lo level sensors, PSV, liquid-level gauges.', isPublished: true },
  { slug: 'wt-knock-out-drum', name: 'Knock Out Drums', parentSlug: 'well-testing-equipment', position: 3, shortDescription: 'Gravity-separation KO drums removing liquid droplets from gas streams en route to flare. ASME U, NACE MR-0175.', isPublished: true },
  { slug: 'wt-flare-stack', name: 'Flare Stacks', parentSlug: 'well-testing-equipment', position: 4, shortDescription: 'Onshore + offshore flare stacks. Skid + concrete anchors or trailer with hydraulic deployment. Piezo ignition. Tri-Heads Green burners optional.', isPublished: true },
  { slug: 'wt-transfer-pump', name: 'Transfer Pumps (Well Testing)', parentSlug: 'well-testing-equipment', position: 5, shortDescription: 'Well-testing transfer pumps for fluid evacuation — centrifugal / multistage / membrane / progressive cavity / reciprocating. Diesel / electric / hydraulic / pneumatic drive.', isPublished: true },
  { slug: 'wt-flush-test-pump', name: 'Backside Flush / Test Pumps', parentSlug: 'well-testing-equipment', position: 6, shortDescription: 'Reciprocating flush / test pumps 100-180 HP for line / casing pressure testing and flushing.', isPublished: true },
  { slug: 'wt-sand-filter', name: 'Sand Filters', parentSlug: 'well-testing-equipment', position: 7, shortDescription: 'Vertical dual-pot sand filters 5K / 10K / 15K psi, ASME U2, SS316 sintered cartridge + DNV frame.', isPublished: true },
  { slug: 'wt-esd-panel', name: 'ESD Panels', parentSlug: 'well-testing-equipment', position: 8, shortDescription: 'Emergency Shutdown panels for one or more SSVs. SS316 enclosure, hi-lo pressure pilots, Haskel / Maximator pumps, 3 remote ESD stations.', isPublished: true },
  { slug: 'wt-data-header', name: 'Data Headers', parentSlug: 'well-testing-equipment', position: 9, shortDescription: 'Well-testing data headers with selectable ports (ACLV / NPT), isolation needle valves, thermowells, pressure gauges, check valves.', isPublished: true },
  { slug: 'wt-piping-packages', name: 'Piping Packages (Well Testing + EPF)', parentSlug: 'well-testing-equipment', position: 10, shortDescription: 'Welded piping packages for well testing and EPF. X-ray + PWHT, third-party witnessed pressure tests, NACE MR-0175, arctic grades on request.', isPublished: true },
  { slug: 'drilling-workover-systems', name: 'Drilling & Workover Systems', position: 16, shortDescription: 'Drilling & workover packaged systems — mud pump packages, mud manifolds, degassers, mud / workover tanks, liquid mud plants, and mobile labs / workshops.', seoTitle: 'Drilling & Workover Systems — Mud Pumps, Mud Plants, Workover Tanks', seoDescription: 'Engineered drilling & workover packaged systems: mud pump packages, mud manifolds, mud degassers, mud + workover tanks, liquid mud plants, mobile labs & workshops.', isPublished: true },
  { slug: 'dw-mud-pump-package', name: 'Mud Pump Packages', parentSlug: 'drilling-workover-systems', position: 0, shortDescription: 'Modular mud pump packages for drilling + workover. Electric / hydraulic / mechanical drive. Pulsation dampener, charging pump, PSV.', isPublished: true },
  { slug: 'dw-mud-manifolds', name: 'Mud Manifolds', parentSlug: 'drilling-workover-systems', position: 1, shortDescription: 'Drilling mud manifolds — Demco, Oteco, customer-selectable valves. X-ray + PWHT welds, BV/DNV/Lloyds witnessed pressure tests.', isPublished: true },
  { slug: 'dw-mud-degasser', name: 'Mud Degassers', parentSlug: 'drilling-workover-systems', position: 2, shortDescription: 'Vertical drilling mud degassers with U-tube vent piping. Sized to project requirement.', isPublished: true },
  { slug: 'dw-mud-tanks', name: 'Mud Tanks', parentSlug: 'drilling-workover-systems', position: 3, shortDescription: 'Drilling mud storage + transport tanks. Skid or axle-mounted, ISO 40-ft container footprint, multi-compartment treatment tanks.', isPublished: true },
  { slug: 'dw-workover-tanks', name: 'Workover Tanks', parentSlug: 'drilling-workover-systems', position: 4, shortDescription: 'Workover tanks for brine and mud service, customized per project. Common sizes 160 BBL, 240 BBL.', isPublished: true },
  { slug: 'dw-liquid-mud-plant', name: 'Liquid Mud Plants (LMP)', parentSlug: 'drilling-workover-systems', position: 5, shortDescription: 'Complete modular Liquid Mud Plants — base oil, brine, OBM preparation, mixing, dry additives, recirculation, and storage.', isPublished: true },
  { slug: 'dw-mobile-labs-workshops', name: 'Mobile Labs & Workshops', parentSlug: 'drilling-workover-systems', position: 6, shortDescription: 'Oilfield mobile / field labs and workshops — drilling mud, cementing, well testing. Customized layouts, lab benches, storage, climate control.', isPublished: true },
  { slug: 'instrumentation-controls', name: 'Instrumentation & Controls', position: 17, shortDescription: 'Oilfield instrumentation & controls — data acquisition, flowmeters (magnetic / turbine / Coriolis), pressure sensors, gauges, thermometers, AC/DC converters, VFD systems, ex-proof electrical panels.', seoTitle: 'Oilfield Instrumentation & Controls — Sensors, Recorders, VFD, ATEX Panels', seoDescription: 'Oilfield instrumentation & controls: DAQ + touchscreens, magnetic + turbine + Coriolis flowmeters, HP pressure sensors, gauges, thermometers, VFDs, ATEX explosion-proof electrical panels.', isPublished: true },
  { slug: 'ic-data-acquisition', name: 'Data Acquisition Systems', parentSlug: 'instrumentation-controls', position: 0, shortDescription: 'Multi-channel oilfield Data Acquisition Systems with 9 / 11 / 15-inch touchscreens. 4-20 mA, 0-5 V, pulse, frequency inputs.', isPublished: true },
  { slug: 'ic-magnetic-flowmeters', name: 'Magnetic Flowmeters', parentSlug: 'instrumentation-controls', position: 1, shortDescription: 'Magnetic flowmeters in a range of sizes and pressure ratings. ATEX / Eex variants.', isPublished: true },
  { slug: 'ic-turbine-flowmeters', name: 'Turbine Flowmeters', parentSlug: 'instrumentation-controls', position: 2, shortDescription: 'LP and HP turbine flowmeters, 2-inch and 3-inch Fig.1502 connections up to 15,000 psi.', isPublished: true },
  { slug: 'ic-coriolis-nrd', name: 'Coriolis Mass Flowmeters (NRD)', parentSlug: 'instrumentation-controls', position: 3, shortDescription: 'Non-radioactive Coriolis mass flow + density + temperature meters for cementing, hydration, LAS systems.', isPublished: true },
  { slug: 'ic-analogic-pressure-sensors', name: 'Analogic Pressure Sensors', parentSlug: 'instrumentation-controls', position: 4, shortDescription: 'Fig.1502 pressure deboosters with 6-inch analogic gauge + adjustable overpressure shutdown proximity switch.', isPublished: true },
  { slug: 'ic-electronic-pressure-sensors', name: 'Electronic Pressure Sensors', parentSlug: 'instrumentation-controls', position: 5, shortDescription: 'Electronic HP pressure sensors 0-15,000 psi with 2-inch Fig.1502M connection. 4-20 mA / digital output.', isPublished: true },
  { slug: 'ic-proximity-sensors', name: 'Proximity Sensors', parentSlug: 'instrumentation-controls', position: 6, shortDescription: 'Magnetic-pickup proximity sensors for pump shaft RPM / bolt-counter feedback into DAQ.', isPublished: true },
  { slug: 'ic-pressure-gauges', name: 'HP Pressure Gauges', parentSlug: 'instrumentation-controls', position: 7, shortDescription: 'High-pressure oilfield pressure gauges 1/2-inch NPT, SS316, glycerine-filled, 100 psi to 15,000 psi.', isPublished: true },
  { slug: 'ic-thermometers-thermowells', name: 'Thermometers & Thermowells', parentSlug: 'instrumentation-controls', position: 8, shortDescription: 'Bimetal thermometers (P+U API 6A range, 1/2-inch NPT male, multiple stem lengths) + matching integral thermowells in SS304 / SS316.', isPublished: true },
  { slug: 'ic-acdc-converters', name: 'AC/DC Converters', parentSlug: 'instrumentation-controls', position: 9, shortDescription: 'AC/DC converter packages to power DC control circuits from 230 / 380 / 400 / 415 / 440 / 460 V AC mains. Enclosure + breakers + power supply.', isPublished: true },
  { slug: 'ic-vfd-systems', name: 'VFD Systems', parentSlug: 'instrumentation-controls', position: 10, shortDescription: 'Variable Frequency Drive packages for AC motor-driven oilfield pumps, onshore and offshore. Replacement for legacy DC converter systems.', isPublished: true },
  { slug: 'ic-electrical-panels', name: 'Explosion-Proof Electrical Panels', parentSlug: 'instrumentation-controls', position: 11, shortDescription: 'Explosion-proof aluminium-cast or weatherproof steel-sheet electrical panels with breakers, contactors, terminals. ATEX / IECEx options.', isPublished: true },
  { slug: 'oilfield-restraint-systems', name: 'Restraint Systems & Safety Clamps', parentSlug: 'oilfield-valve-accessories', position: 6, shortDescription: 'Forged-steel cable anchor restraint systems / safety clamps for treating iron. Tube-OD matched, eye for steel cable, pressure-pumping spec.', isPublished: true },
]

const products: ProductImportPayload[] = [
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CMU-S600-SKD',
    mpn: 'CMU-S600-SKD',
    title: `Single-Pump Cementing Unit, Skid-Mounted, Triplex 600 HP, Auto Density Control`,
    categorySlug: 'cementing-units',
    descriptionShort: `Single-pump triplex cementing unit (600 HP) on transport skid with automatic density control and 15" touchscreen data acquisition. Onshore or offshore (DNV skid optional). CE / GOST available.`,
    descriptionLong: `<p>Indus engineered cementing unit built as a single-pump triplex package on a transport skid sized to standard 40-ft container footprint. Choice of triplex pump (SPM, Gardner Denver, Serva, OFM) sized to 600 HP continuous duty, driven by a CAT / MTU / Cummins diesel through an Allison or CAT transmission. Equipped with automatic density control system, charging centrifugal pump, recirculation manifold, calibrated 50-BBL displacement tank, and a 15" touchscreen data acquisition system with USB export to ASCII / Excel.</p><p>Available in onshore land skid, DNV-certified offshore skid, single-axle / triple-axle trailer, and 4×2 / 6×4 / 8×8 truck-mounted configurations. ATEX Zone 2 and Rigsafe options available. HVAC operator cabin and pre-heating winterization for arctic operations.</p><p>Quoted to client specification — engine brand, transmission, pump make, density control supplier, and electronic interface are all selectable. Built under ISO 9001:2015 with NACE MR0175 material defaults for sour service.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CBM-2X100-CRL',
    mpn: 'CBM-2X100-CRL',
    title: `Cement Batch Mixer, Twin 2×100 BBL, Coriolis Density, Hydraulic Drive`,
    categorySlug: 'cementing-batch-mixer',
    descriptionShort: `2×100 BBL twin-compartment cement batch mixer with sloped conical bottoms, siphon system, optional Coriolis density meter, mixing jets and recording. Hydraulic or electric drive.`,
    descriptionLong: `<p>Twin-compartment cement batch mixer with 2×100 BBL nominal capacity (uneven splits available, e.g. 10 m³ + 20 m³). Each tank features sloped conical bottoms and a siphon system to prevent dead volumes. Cylindrical or square-rounded-corner tank geometry is available.</p><p>Optional non-radioactive Coriolis density meter, mixing jets for slurry homogenization, recording system, and automatic density control loop. Power pack via diesel engine driving hydraulic motors (CAT / Cummins / Volvo Penta / Deutz) or ATEX-certified electric motors with armoured cables and Eex glands.</p><p>Skid, trailer, or truck mounted. CE marked and GOST certified on request. Rigsafe / Zone 2 options for offshore deployment. Built under ISO 9001:2015 with NACE MR0175 wetted-parts defaults.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-OTF-20-ADC',
    mpn: 'OTF-20-ADC',
    title: `On-The-Fly Cement Mixer, 20 BBL Surge Tank, 2.5 SG Max, Auto Density`,
    categorySlug: 'cementing-on-the-fly-mixer',
    descriptionShort: `On-the-fly cement slurry mixing system with 20-BBL surge tank, 2.5 SG max density, dry cement surge feed and optional automatic density control. Onshore / offshore / arctic.`,
    descriptionLong: `<p>On-the-fly cement slurry mixer engineered for continuous mixing during pumping operations. Standard configuration includes a 20-BBL surge tank, dry-cement surge tank for steady delivery, and a mixing tub rated to 2.5 SG maximum slurry density.</p><p>Manual ground-mixing system or automatic density control loop available. Diesel engine or ATEX electric motor drive. Skid (onshore or offshore), trailer or truck-mounted. CE / GOST certifications and pre-heating winterization available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CSL-1500-LC',
    mpn: 'CSL-1500-LC',
    title: `Cement Silo, 1,500 cu.ft., L-Frame, Aerated, Load Cells`,
    categorySlug: 'cementing-silos',
    descriptionShort: `1,500 cu.ft. cylindrical cement silo on L-shaped transport frame. Aeration nozzles + air manifold, load cells with digital display, fill / vent / discharge lines.`,
    descriptionLong: `<p>Cylindrical cement bulk storage silo with 1,500 cu.ft. nominal capacity, mounted on an L-shaped frame for horizontal transport and vertical site installation. Aeration nozzles and air manifold deliver smooth discharge; integrated fill, vent and discharge lines support cluster interconnection with neighboring silos.</p><p>Load-cell weighing system with digital local display, optional remote display, and integration with cementing unit DAQ. Alternative capacities 1,200 cu.ft. and 1,900 cu.ft. available, plus custom sizes. CE / GOST certifications on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CCB-SKD-PNT',
    mpn: 'CCB-SKD-PNT',
    title: `Cement Cutting Bottle, Skid-Mounted, 4-Blade Needle, Pneumatic Top Valve`,
    categorySlug: 'cementing-cutting-bottle',
    descriptionShort: `Cement big-bag cutting bottle with 4-bladed needle, hopper, aeration manifold and pneumatic-actuated top butterfly valve. Onshore / offshore.`,
    descriptionLong: `<p>Skid-mounted cement big-bag cutting bottle for cementing unit charge operations. Equipped with a hopper, 4-bladed needle for cutting the cement bag bottom, aeration nozzles and air manifold to prevent self-weight compaction, and a vent + discharge line.</p><p>Top main butterfly valve is pneumatic-actuated as standard, with manual and electric-actuator variants available. Trailer-mounted version available for in-field redeployment. ATEX Zone 2 and arctic winterization options.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CDC-50-FAB',
    mpn: 'CDC-50-FAB',
    title: `Cement Dust Collector, Velocity-Drop, 50 cu.ft. Vessel, Synthetic Fabric Bag`,
    categorySlug: 'cementing-dust-collector',
    descriptionShort: `Velocity-drop + gravity cement dust collector. 50 cu.ft. vessel, synthetic fabric collection bag with quick-release clamps, dump line. Sizes scale to client requirement.`,
    descriptionLong: `<p>Cement dust collector designed for low capex / OPEX cement handling site applications. Cement dust is captured by velocity-drop on inlet and gravity separation inside a 50 cu.ft. vessel; collected material falls into a synthetic fabric bag attached to the dump line with quick-release clamps.</p><p>Vessel volume is adjustable on a project basis — 25 to 200 cu.ft. envelopes are standard. Optional differential pressure indicator and remote alarm.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CRC-INL-SS',
    mpn: 'CRC-INL-SS',
    title: `Cement Rock Catcher, Inline Vessel, SS Screen, Selectable Mesh`,
    categorySlug: 'cementing-rock-catcher',
    descriptionShort: `Inline rock catcher for bulk cement lines. Stainless-steel screen (selectable mesh), dump line for debris removal, scalable vessel volume.`,
    descriptionLong: `<p>Inline rock catcher installed in bulk cement transfer lines to prevent debris, rocks and aggregated cement chunks from entering silos or the mixing system. Stainless-steel screen with project-selected mesh size; dump line allows scheduled debris evacuation.</p><p>Vessel volume is engineered to client throughput and bulk-line size. Optional pressure differential indicator and high-debris alarm.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-N2-360-10K-TRK',
    mpn: 'N2-360-10K-TRK',
    title: `Nitrogen Pumping Unit, 360K, 10,000 psi, Truck-Mounted, Modular`,
    categorySlug: 'stimulation-nitrogen-unit',
    descriptionShort: `360,000 SCF N₂ pumping unit, 10,000 psi MAWP. Modular truck-mounted design with independent cryogenic tank, control cabin, hydraulic power pack and vaporizer.`,
    descriptionLong: `<p>Truck-mounted nitrogen pumping unit with 360,000 SCF cryogenic liquid nitrogen tank capacity and a 10,000 psi maximum working pressure rating. Modular construction — three independent modules interconnect on a substructure bolted to the truck chassis, enabling rapid chassis swap and independent crane lifts for offshore installation.</p><p>Includes a cryogenic high-pressure reciprocating LN₂ pump, hydraulic power pack, heat-exchange vaporizer, and operator control cabin with manual or electronic interface. Available capacities: 90K, 180K, 360K, 400K, 800K, 1000K. Maximum pressure ratings to 15,000 psi.</p><p>Truck chassis: MAN, Scania, Volvo, DAF, Renault, Iveco, Tatra, MAZ, MAZ-MAN, NZKT, Kamaz, Kenworth, Peterbilt. Diesel engine: CAT, MTU, Detroit Diesel, Cummins, Deutz, Volvo Penta. CE, GOST, ATEX Zone 2, and arctic winterization options.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-STP-FRP-MS-HYD',
    mpn: 'STP-FRP-MS-HYD',
    title: `Stimulation Transfer Pump, FRP-Lined Carbon Steel, Centrifugal Multistage, Hydraulic Drive`,
    categorySlug: 'stimulation-transfer-pump',
    descriptionShort: `FRP-lined carbon steel centrifugal multistage transfer pump for acid / brine stimulation service. Hydraulic motor drive with variable speed control.`,
    descriptionLong: `<p>Multistage centrifugal transfer pump packaged for stimulation service. Wetted parts are FRP-lined carbon steel for acid and brine compatibility; full stainless-steel and PTFE-internals variants are available for highly corrosive media.</p><p>Drive options: diesel engine (water- or air-cooled, manual or pneumatic PTO clutch), AC or DC electric motor with VFD speed control, hydraulic motor, or pneumatic motor. Membrane, progressive cavity, and reciprocating pump variants offered under the same product family for different fluid profiles.</p><p>Skid, trailer or truck mounted. ATEX Zone 2, CE, GOST and arctic winterization available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-ATK-ISO20-FRP-6KG',
    mpn: 'ATK-ISO20-FRP-6KG',
    title: `Acid Tank, FRP-Lined Steel, ISO 20-ft Frame, 6,000 USG, Dangerous-Goods Certified`,
    categorySlug: 'stimulation-acid-tanks',
    descriptionShort: `6,000 USG FRP-lined carbon steel acid tank inside an ISO 20-ft frame. Acid-resistant plastic piping, dangerous-fluids transport certified.`,
    descriptionLong: `<p>Acid storage and transport tank with 6,000 USG nominal capacity inside an ISO 20-ft container frame for global multimodal shipping. Carbon steel shell with thick FRP internal lining; full-FRP shell variant available. All wetted piping in acid-resistant plastic.</p><p>Trailer-mounted variants available — built to road-authority regulations of the country of registration (axles, brakes, lights, gabarit, electrical connections, dangerous-fluids vessel certification). Capacities customized to client demand.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-SBM-2X100-FRP-ATX',
    mpn: 'SBM-2X100-FRP-ATX',
    title: `Stimulation Batch Mixer, 2×100 BBL, FRP-Lined Steel, PTFE Butterfly Valves, ATEX`,
    categorySlug: 'stimulation-batch-mixers',
    descriptionShort: `2×100 BBL twin-tank stimulation batch mixer for HCl / brine service. FRP-lined steel tanks, PTFE-lined butterfly valves, ATEX motors.`,
    descriptionLong: `<p>Twin-compartment stimulation batch mixer engineered for corrosive acid (HCl), brine, and gelled service. 2×100 BBL nominal capacity with sloped conical bottoms and siphon system. Tank wetted parts in FRP-lined carbon steel as standard, with full stainless-steel and PTFE-lined variants available.</p><p>Impeller agitators in stainless steel or FRP-coated. Centrifugal pumps and piping rated to the chemistry profile. All butterfly valves lined with PTFE. Power pack: diesel + hydraulic motors or ATEX-certified electric motors with armoured cabling and Eex glands.</p><p>Skid, trailer, or truck mounted. CE / GOST and Rigsafe / Zone 2 for offshore.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-SPU-T2X1000-15K-TRL',
    mpn: 'SPU-T2X1000-15K-TRL',
    title: `Stimulation Pumping Unit, Twin Triplex 1,000 HP, 15,000 psi, Trailer-Mounted`,
    categorySlug: 'stimulation-pumping-units',
    descriptionShort: `Twin triplex stimulation pumping unit, 1,000 HP per pump, 15,000 psi MAWP, trailer-mounted. Diesel-hydraulic drive, full electronic control.`,
    descriptionLong: `<p>Twin-configuration triplex stimulation pumping unit on a custom-built trailer. Each pump rated 1,000 HP continuous duty at 15,000 psi MAWP, supplied by SPM, Gardner Denver, Serva, OFM or equivalent. Diesel deck engine (CAT / Detroit Diesel / MTU / Mercedes / Volvo Penta / Deutz / Cummins) drives the pumps via Allison, CAT or ZF transmission.</p><p>Fluid handling rated for water, acid, brine and mud injection. Engineered for onshore land, offshore (DNV skid variant), desert and arctic environments. CE, GOST, Rigsafe / Zone 2 options on request.</p><p>Full electronic control system with HVAC operator cabin, pre-heating winterization, and integration with cementing/data-van fleet networks.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FP-2500-TRL-NET',
    mpn: 'FP-2500-TRL-NET',
    title: `Frac Pumper, 2,500 HP, Trailer-Mounted, Fleet-Networked, DNV Optional`,
    categorySlug: 'frac-pumpers',
    descriptionShort: `2,500 HP frac pumper on custom trailer. Pump make selectable (SPM, GD, Serva). Fleet-networked DAQ; offshore DNV-certified modules available.`,
    descriptionLong: `<p>Frac pumper packaged on a custom-built trailer with 2,500 HP nominal continuous duty. Triplex pump selectable (SPM, Gardner Denver, MSI, Serva). Deck engine: CAT, MTU, Deutz, Cummins, Volvo Penta. Transmission: CAT or Allison.</p><p>Fleet-networked DAQ with wired or wifi connection to the frac Data Van for fleet coordination. Standalone-pumper variant for single-well work also available.</p><p>DNV-certified offshore module variant splits the unit across multiple lifts to comply with rig crane load envelopes. CE / GOST certifications optional. Sizes available: 1,500 HP, 2,000 HP, 2,250 HP, 2,500 HP, 3,000 HP.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FTP-CP1212-300-SKD',
    mpn: 'FTP-CP1212-300-SKD',
    title: `Frac Transfer Pump, Centrifugal 12×12, 300 HP, Diesel-Hydraulic Drive, Skid-Mounted`,
    categorySlug: 'frac-transfer-pumps',
    descriptionShort: `12×12 centrifugal frac transfer pump, 300 HP, diesel-hydraulic drive on transport skid. Feeds frac pumpers from blender / supply tanks at high flow rate.`,
    descriptionLong: `<p>High-flow centrifugal frac transfer pump (12-inch suction × 12-inch discharge) packaged on a transport skid with diesel-hydraulic drive. Used to feed frac pumpers from blenders or storage supply at the required suction flow rate.</p><p>C-pump make selectable (Gardner Denver, MCM, NOV, Serva). Drive options: electric motor (ABB, WEG, Valiadis), diesel engine (CAT, Deutz, Cummins, Perkins, Detroit Diesel, Volvo Penta), or hydraulic motor (Denison, Veljan). Trailer-mounted and truck-mounted variants on registration-ready chassis.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FM-16P-4IN-15K-1502',
    mpn: 'FM-16P-4IN-15K-1502',
    title: `Frac Missile (Manifold), 16-Pumper Capacity, 4-inch 1502, 15,000 psi Standard Service`,
    categorySlug: 'frac-manifold',
    descriptionShort: `16-pumper frac missile with 4" HP discharge Fig.1502 connections at 15,000 psi STD service rating. 8/10/12" LP suction manifold, bleed-off / provision outlets.`,
    descriptionLong: `<p>Frac iron missile (manifold) accommodating up to 16 frac pumpers per side. 4-inch HP discharge in Fig.1502 connections (Fig.2002, Fig.2202, Clamp Hub, Grayloc available on request) at 15,000 psi standard service rating. All treating iron integral.</p><p>LP manifold (8/10/12 inch depending on pumper count) provides dual suction connections per pumper, each with 4-inch quarter-turn butterfly valves and 4-inch Fig.206F with Fig.207 blind caps. Additional bleed-off and provision outlets on both HP and LP manifolds.</p><p>Skid, trailer or truck mounted with registration-ready documentation. CE / GOST certifications optional.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FSS-V200-HT-KG',
    mpn: 'FSS-V200-HT-KG',
    title: `Frac Sand Silo (Sand Chief), Vertical Round, Hydraulic Tilt, 200 t Capacity, Knife-Gate Discharge`,
    categorySlug: 'frac-sand-silos',
    descriptionShort: `Vertical round frac sand silo (Sand Chief), 200 t nominal capacity. Hydraulic cylinder tilt for chute delivery, hydraulic knife-gate valve / door control.`,
    descriptionLong: `<p>200-tonne nominal frac sand silo, vertical round design, mounted with hydraulic cylinders to allow controlled tilt for chute delivery and constant sand flow. Hydraulic knife-gate valves and doors regulate discharge into the blender.</p><p>Horizontal, square, and multi-compartment configurations available. Sand-belt-conveyor delivery (in lieu of tilt) for fixed-installation sites. Onshore or offshore configurations on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FB-MFR-50-ADC-CAS',
    mpn: 'FB-MFR-50-ADC-CAS',
    title: `Frac Blender MFR-50, 50 BBL/min, Auto Density Control, Chemical Additive System`,
    categorySlug: 'frac-blender',
    descriptionShort: `50 BBL/min frac blender with calibrated sand auger, inlet/outlet flowmeters, automatic tub-level + slurry-density control, and chemical additive system for liquid + dry dosing.`,
    descriptionLong: `<p>Mixing & Flow Regulated (MFR) blender with 50 BBL/min slurry discharge for fracturing operations. Calibrated progressive-cavity (auger) sand metering or rotating bulk-material metering valve; inlet and outlet flowmeters; automatic tub-level regulation and slurry-density control.</p><p>Integrated Chemical Additive System (CAS) with automatic dosing pumps for liquid and dry additives. Standalone operation or wired / wifi connection to the frac Data Van. Available variants: MFR-10, MFR-15, MFR-20 (gravel pack) and MFR-50, MFR-100 (frac).</p><p>Truck chassis: MAN, Mercedes, Scania, DAF, Volvo, Renault, Tatra, MAZ, MAZ-MAN, Kamaz, NZKT, Kenworth, Peterbilt. Engine: CAT, Mercedes, Deutz, MTU, Detroit Diesel, Volvo Penta.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FHU-200-CP1212-90',
    mpn: 'FHU-200-CP1212-90',
    title: `Frac Hydration Unit, 200 BBL, 12×12 Centrifugal, 90 BBL/min, SS316 Tote Tanks`,
    categorySlug: 'frac-hydration-unit',
    descriptionShort: `200 BBL frac hydration unit, 12×12 centrifugal pump, 90 BBL/min mixing rate. 1 dry (Guar) tank + 4 liquid SS316 tote tanks, optional heating + agitation.`,
    descriptionLong: `<p>Frac hydration unit engineered for gel preparation prior to crosslinking with frac proppant. 200 BBL hydration tank (capacity adjustable per project), 12-inch × 12-inch centrifugal mixing pump, 90 BBL/min mixing rate, and a flow path with chicanes inside the tank to maximize hydration time of particles.</p><p>Includes one dry chemical tank (typically Guar) and up to four liquid chemical tanks — all SS316 tote-type, with optional heating system and agitator. Suction / discharge ports on both sides for versatile rig-up.</p><p>Full electronic control optional: viscosity meter, density meter, pH meter, chemical dosing pumps. Skid, trailer or truck mounted; DNV-certified offshore variant; arctic-winterized variant with pre-heating.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-LAS-8T-SS316-MFM-TRL',
    mpn: 'LAS-8T-SS316-MFM-TRL',
    title: `Frac LAS, 8-Tank, SS316 Tote Tanks, Mass Flowmeters, Trailer-Mounted`,
    categorySlug: 'frac-las',
    descriptionShort: `8-tank frac Liquid Additive System with SS316 tote tanks, per-tank dosing pumps, mass flowmeters per discharge, control cabin with full electronic visualization.`,
    descriptionLong: `<p>Frac LAS (Liquid Additive System) on a custom trailer with eight chemical totes (SS316 tote-type). Each tank includes a dedicated dosing pump, drain port, fill port; pneumatic / hydraulic / electric agitators and heating systems available. Per-tank mass flowmeters on discharge lines for chemical accountability.</p><p>Integrated reels for unit-to-unit hose runs. Control cabin with full visualization of all tanks and discharge lines; operator manual or automatic mode. Diesel-engine + hydraulic power pack or diesel genset. Trailer mounted with country-of-registration documentation; skid and truck variants available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FDV-TRL-MSC',
    mpn: 'FDV-TRL-MSC',
    title: `Frac Data Van, Trailer-Mounted, Multi-Screen Fleet Control, HVAC + Pantry`,
    categorySlug: 'frac-data-van',
    descriptionShort: `Frac fleet data van on a custom trailer. HVAC, flooring, desks, pantry, multi-screen fleet visualization, wired + wifi I/O to blender / LAS / hydration / transfer / pumpers.`,
    descriptionLong: `<p>Frac fleet data van engineered as a custom trailer (also available as a modified seafreight container or truck-mounted box). HVAC, insulated flooring, operator desks, pantry, and storage. Multi-screen visualization wall for entire fleet parameters with recording and playback for post-job analysis.</p><p>Full I/O network connects via wired or wifi to all fleet units: blender(s), LAS, hydration unit, transfer pumps, pumpers. Operator control of the entire fleet from a single station. CE / GOST and arctic / desert environmental envelopes available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FTK-500-INS-TRL',
    mpn: 'FTK-500-INS-TRL',
    title: `Frac Tank, 500 BBL, Insulated, Trailer-Mounted, Road-Registered`,
    categorySlug: 'frac-tanks',
    descriptionShort: `500 BBL frac fluid storage tank on a road-registered trailer. Insulated shell, manholes, baffles, vent + drain lines, optional heating.`,
    descriptionLong: `<p>500 BBL nominal frac fluid storage tank with insulated shell and internal baffling. Custom trailer with country-of-registration documentation; ISO-frame skid variant for global container shipping. Top + side manholes, vent, fill, and drain lines. Optional heating coil and recirculation manifold.</p><p>Volumes 100-1,000 BBL standard; custom volumes on request. Lined or unlined wetted parts depending on fluid chemistry.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-3PS-1440-60X15-DNV',
    mpn: '3PS-1440-60X15-DNV',
    title: `3-Phase Well-Test Separator, 1,440 psi, 60-in OD × 15-ft, ASME U, NACE MR-0175, DNV Skid`,
    categorySlug: 'wt-3-phase-separator',
    descriptionShort: `1,440 psi 3-phase well-test separator, ASME U-stamped, NACE MR-0175. 60-inch OD × 15-ft seam-to-seam, Daniel orifice + PSV, DNV-certified offshore skid.`,
    descriptionLong: `<p>3-phase multiphase well-testing separator with 1,440 psi MAWP, 60-inch outside diameter × 15-ft seam-to-seam, ASME U-stamped pressure vessel and NACE MR-0175 compliant materials. Daniel orifice valve, PSV, and a complete suite of process control valves (level, flow, pressure).</p><p>Mounted on a DNV-certified offshore skid (onshore skid variant available; trailer-mounted variants integrated into full well-test trailers). Pressure-rating variants: 250, 900, 1,440 and 2,160 psi.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MPFM-SKD-RXE-CMPCT',
    mpn: 'MPFM-SKD-RXE-CMPCT',
    title: `MPFM System, Skid-Mounted, Roxar-Emerson Compact, Upstream + Downstream Piping`,
    categorySlug: 'wt-mpfm-system',
    descriptionShort: `MPFM system on transport skid integrating a Roxar-Emerson compact MPFM with upstream / downstream piping and manifolds. Trailer variant available.`,
    descriptionLong: `<p>Multi-Phase Flow Meter (MPFM) system packaged on a transport skid, integrating the client-selected MPFM head (Haimo, Agar, Medeng, ABB, Roxar-Emerson) with upstream and downstream piping and manifolds. Calibration loop and isolation valves included as standard.</p><p>DNV-certified offshore skid variant available for offshore MPFM deployment. Trailer-mounted variant on registration-ready custom trailer for onshore mobile MPFM service. CE / GOST and arctic / desert envelopes optional.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-WTS-DC100-600-DNV',
    mpn: 'WTS-DC100-600-DNV',
    title: `Well-Testing Surge Tank, Dual-Compartment, 100 BBL, 600 psi, ASME U, DNV Skid`,
    categorySlug: 'wt-surge-tank',
    descriptionShort: `Dual-compartment well-testing surge tank, 100 BBL nominal, 600 psi MAWP, ASME U-certified. Hi-lo level alarms, PSV, sight gauges, DNV-certified skid.`,
    descriptionLong: `<p>Well-testing surge tank with dual independent compartments, 100 BBL combined nominal capacity and 600 psi MAWP. ASME U-stamped pressure vessel; NACE MR-0175 materials available. Each compartment has its own hi-lo level sensors + alarms, PSV, and liquid-level gauge.</p><p>Mounted on a DNV-certified offshore skid (onshore skid + integrated-trailer variants available). Capacity and pressure rating variants engineered to client requirement.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-KOD-720-60X12-NACE',
    mpn: 'KOD-720-60X12-NACE',
    title: `Knock Out Drum, 720 psi, 60-in OD × 12-ft, ASME U, NACE MR-0175`,
    categorySlug: 'wt-knock-out-drum',
    descriptionShort: `720 psi knock-out drum sized for gas-stream droplet separation upstream of the flare. ASME U-stamped, NACE MR-0175 compliant.`,
    descriptionLong: `<p>Knock-out drum for separating liquid droplets carried by gas streams en route to the flare stack. Separation is by gravity inside a 60-in OD × 12-ft S/S vessel, with internal geometry that slows inlet flow and allows droplets to fall.</p><p>720 psi MAWP; ASME U-stamped pressure vessel; NACE MR-0175 compliant materials. PSV, hi/lo level sensors, and liquid-level gauge on the vessel. Capacity and rating customized per client demand.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FLS-TRL-HYD-60-TRI',
    mpn: 'FLS-TRL-HYD-60-TRI',
    title: `Flare Stack, Trailer-Mounted, Hydraulic Deployment, Piezo Ignition, 60-ft, Tri-Heads Green`,
    categorySlug: 'wt-flare-stack',
    descriptionShort: `60-ft trailer-mounted flare stack with hydraulic deployment, stabilizing legs, piezo-electric ignition and Tri-Heads Green burner assembly.`,
    descriptionLong: `<p>60-ft trailer-mounted flare stack with hydraulic deployment system and stabilizing legs. Piezo-electric spark generator ignition. Tri-Heads Green burner head for environmentally optimized flaring.</p><p>Onshore skid-mounted variants available with concrete anchor blocks. Offshore flare boom designs to client crane / structural envelope. Custom trailer with country-of-registration documentation. CE / GOST optional.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-WTP-CS100-DSL-SKD',
    mpn: 'WTP-CS100-DSL-SKD',
    title: `Well-Test Transfer Pump, Centrifugal Single-Stage, 100 m³/h, Diesel Drive, Skid-Mounted`,
    categorySlug: 'wt-transfer-pump',
    descriptionShort: `100 m³/h centrifugal single-stage well-test transfer pump with diesel drive and PTO clutch. Wetted parts in FRP-lined CS as standard.`,
    descriptionLong: `<p>Single-stage centrifugal well-testing transfer pump rated 100 m³/h. Wetted parts in FRP-lined carbon steel as standard; full stainless and PTFE-interior variants available. Diesel drive with manual or pneumatic PTO clutch (CAT, Cummins, Deutz, Detroit Diesel, Volvo Penta).</p><p>Membrane, progressive cavity, multistage centrifugal, and reciprocating variants available under the same product family. Electric variants available with AC/DC and VFD speed control. Skid, trailer or truck mounted.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-FTP-R150-10K-CHR',
    mpn: 'FTP-R150-10K-CHR',
    title: `Flush / Test Pump, Reciprocating 150 HP, 10,000 psi, Skid + Chart Recorder`,
    categorySlug: 'wt-flush-test-pump',
    descriptionShort: `150 HP reciprocating flush / test pump with 10,000 psi MAWP, water-on-water plunger lubrication, paper-chart + electronic recorders. Skid-mounted.`,
    descriptionLong: `<p>Reciprocating flush / test pump with 150 HP rating and 10,000 psi MAWP for line / casing flushing and pressure testing. Water-on-water plunger lubrication (water is both pumped fluid and plunger lubricant).</p><p>Electronic and paper-chart recorders integrated for testing documentation. Compact skid envelope; small trailer variant for pickup-truck towing. 100, 130, 150 and 180 HP ratings available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-SFL-DP-10K-SS316-DNV',
    mpn: 'SFL-DP-10K-SS316-DNV',
    title: `Sand Filter, Dual-Pot Vertical, 10,000 psi, ASME U2, SS316 Sintered, DNV Frame`,
    categorySlug: 'wt-sand-filter',
    descriptionShort: `Dual-pot vertical sand filter, 10,000 psi MAWP, ASME U2-stamped. SS316 sintered cartridge, by-pass manifold, deployable gantry crane.`,
    descriptionLong: `<p>Vertical dual-pot sand filter rated 10,000 psi MAWP, ASME U2-stamped, with SS316 sintered cartridge filter element. Internal shields disrupt incoming stream to drop velocity and gravity-settle heavy particles into a drain area; the sintered cartridge then retains fines.</p><p>Inlet / outlet by-pass manifold allows single-pot or parallel operation. Differential-pressure measurement between inlet and outlet drives a clogging alarm. HP water-nozzle backwash for cartridge cleaning. Deployable gantry crane for cartridge removal / replacement without interrupting operations. DNV frame for offshore deployment.</p><p>5K, 10K and 15K psi variants available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-ESD-1SSV-SS316-3R',
    mpn: 'ESD-1SSV-SS316-3R',
    title: `ESD Panel, Single-SSV Control, SS316, Haskel + Maximator, 3 Remote Stations`,
    categorySlug: 'wt-esd-panel',
    descriptionShort: `Single-SSV emergency shutdown panel in SS316 enclosure with adjustable hi-lo pressure pilots, Haskel + Maximator pneumatic-hydraulic pumps, three remote ESD stations.`,
    descriptionLong: `<p>Emergency Shutdown (ESD) panel engineered to control one well-testing Surface Safety Valve (multi-SSV variants available). SS316 enclosure housing the hydraulic oil tank for actuator control. Adjustable hi-lo pressure pilots tune ESD trigger thresholds to the operation.</p><p>Haskel and Maximator pneumatic-hydraulic pumps reset actuators; manual lever-operated backup pump for redundancy. Three remote ESD stations + interconnecting lines as standard (length and quantity customized).</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-DHD-4ACLV-4NPT-FULL',
    mpn: 'DHD-4ACLV-4NPT-FULL',
    title: `Data Header, 4-Port ACLV + 4-Port NPT, Isolation + Thermowells + Gauges`,
    categorySlug: 'wt-data-header',
    descriptionShort: `Well-testing data header with 4 ACLV + 4 NPT instrumentation ports. Isolation needle valves, thermowells, pressure gauges and check valves fitted as standard.`,
    descriptionLong: `<p>Well-testing data header pre-fitted with eight instrumentation ports — four ACLV and four NPT — covering common pressure, temperature and sampling points. Each port includes an isolation needle valve, thermowell (where applicable), pressure gauge, and check valve.</p><p>Length, port count, ACLV/NPT ratio, and pressure rating are fully customizable. End connections in flanged, hammer union, API clamp hub, or Grayloc on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-WTPP-1502-15K-NACE',
    mpn: 'WTPP-1502-15K-NACE',
    title: `Well-Testing Piping Package, 1502 Series, 15,000 psi, NACE MR-0175, X-Ray + PWHT`,
    categorySlug: 'wt-piping-packages',
    descriptionShort: `Engineered well-testing piping package in 1502 series at 15,000 psi WP. NACE MR-0175 materials, X-ray inspected welds, PWHT, full third-party databook.`,
    descriptionLong: `<p>Welded piping package engineered for well testing and Early Production Facility (EPF) operations. 1502 series connections at 15,000 psi working pressure as a typical package; full range 200 psi to 20,000 psi available. NACE MR-0175 wetted materials as standard; arctic-grade carbon steel for cold-climate operations.</p><p>All welds X-ray inspected; Post Weld Heat Treatment performed on welded joints. Full third-party (BV, DNV, Lloyds) certification reports included in the databook. Connections in flange, hammer union, API clamp hub, or Grayloc on client preference.</p><p>Package includes straight joints, 90° elbows, 45° elbows, tees, crossovers and other fittings to project drawing. Loose-delivery or DNV piping baskets / racking systems available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MPP-T1600-EDR-MOD',
    mpn: 'MPP-T1600-EDR-MOD',
    title: `Mud Pump Package, Triplex 1,600 HP, Electric Drive, Modular for Offshore Lift`,
    categorySlug: 'dw-mud-pump-package',
    descriptionShort: `1,600 HP triplex mud pump package, electric drive (GE / Joliet), modular for offshore crane lift. Pulsation dampener, charging pump, PSV.`,
    descriptionLong: `<p>Triplex mud pump package with 1,600 HP nominal rating for drilling and workover operations. Pump make selectable (Gardner Denver, National, Dragon, Bomco, Gaso); electric drive (GE, Joliet), hydraulic drive, or mechanical drive (CAT, MTU, Cummins, Deutz).</p><p>Integrated pulsation dampener, charging centrifugal pump, and pressure safety / reset valves. Modular sub-frame construction enables splitting the package across multiple lifts for offshore deployment, complying with rig crane envelopes.</p><p>750 HP, 1,000 HP, 1,300 HP, 1,600 HP and 2,200 HP variants available. Onshore land skid or DNV offshore skid.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MMF-4IN-5K-DEMCO',
    mpn: 'MMF-4IN-5K-DEMCO',
    title: `Drilling Mud Manifold, 4-inch 5,000 psi, Demco Valves, X-Ray + PWHT`,
    categorySlug: 'dw-mud-manifolds',
    descriptionShort: `Drilling mud manifold, 4-inch ID, 5,000 psi MAWP, Demco valves. X-ray + PWHT welds, third-party witnessed API 6A pressure test.`,
    descriptionLong: `<p>Drilling mud manifold engineered to client P&amp;ID. 4-inch nominal ID at 5,000 psi MAWP; sizes 2 inch to 6 inch and pressures 3,000 to 15,000 psi available. Demco or Oteco gate valves as standard (customer-selectable).</p><p>Welded construction with X-ray inspection of all welds and Post Weld Heat Treatment of welded joints. All pressure tests conducted per API 6A with third-party (BV, DNV, Lloyds) witness; complete databook included.</p><p>Flanged, hammer-union, API clamp hub, or Grayloc end connections on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MDG-V1000-UT-NACE',
    mpn: 'MDG-V1000-UT-NACE',
    title: `Mud Degasser, Vertical, 1,000 GPM, U-Tube Vent, NACE MR-0175`,
    categorySlug: 'dw-mud-degasser',
    descriptionShort: `Vertical drilling mud degasser sized for 1,000 GPM throughput. U-tube vent piping for safe gas evacuation, NACE MR-0175 materials.`,
    descriptionLong: `<p>Vertical drilling mud degasser designed to remove entrained gas from the mud stream before it returns to the active pit. 1,000 GPM nominal throughput; capacities 250 to 2,000 GPM available.</p><p>U-tube vent piping is included as part of the install package, with venturi-style gas evacuation. NACE MR-0175 materials for sour-service applications. Engineered to project P&amp;ID and client interface requirements.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MTK-500-ISO40',
    mpn: 'MTK-500-ISO40',
    title: `Mud Tank, Skid-Mounted, 500 BBL, 40-ft ISO Footprint, Manholes + Sight Gauges`,
    categorySlug: 'dw-mud-tanks',
    descriptionShort: `500 BBL skid-mounted drilling mud tank within the 40-ft ISO container footprint. Top + side manholes for safe inspection, sight gauges, fill / recirc / discharge / drain lines.`,
    descriptionLong: `<p>500 BBL drilling mud storage and transport tank, skid-mounted within the 40-ft ISO seafreight container footprint (eliminates oversize-shipping surcharges). Designed for variable mud density.</p><p>Dual manholes (top + side) allow cross-ventilation for safe inspector entry. Liquid-level sight gauges; fill, recirculation, discharge and drain lines as standard. Open-top multi-compartment treatment-tank variant available for cuttings + recycled mud handling.</p><p>Axle-mounted (road registered) variant available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-WTK-240-BRN-INS',
    mpn: 'WTK-240-BRN-INS',
    title: `Workover Tank, 240 BBL, Brine Service, Insulated, Manholes + Recirc Manifold`,
    categorySlug: 'dw-workover-tanks',
    descriptionShort: `240 BBL workover tank for brine service. Insulated shell, dual manholes, recirculation manifold, fill / discharge / drain lines.`,
    descriptionLong: `<p>240 BBL workover tank engineered for brine and mud service. Insulated shell, dual manholes (top + side), recirculation manifold, and fill / discharge / drain lines.</p><p>Wetted parts and coating selected per project chemistry. Sizes 160 BBL and 240 BBL are most common; custom volumes on request. Skid or axle-mounted variants.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-LMP-MOD-8K-ISO',
    mpn: 'LMP-MOD-8K-ISO',
    title: `Liquid Mud Plant (LMP), Modular 8,000-BBL Total Storage, ISO Container Footprints`,
    categorySlug: 'dw-liquid-mud-plant',
    descriptionShort: `Modular Liquid Mud Plant with 8,000 BBL combined Base Oil + Brine + OBM storage. ISO container footprints, walkways, lighting, and complete recirculation manifold.`,
    descriptionLong: `<p>Modular Liquid Mud Plant for the preparation of brine and oil-based muds. Combined storage 8,000 BBL across Base Oil, Brine, and OBM tanks; per-fluid volumes adjustable to project demand.</p><p>Includes hoppers with Venturi suction mixing jets, base-oil transfer pump, mixing pumps (carbon steel and / or stainless steel) with manifold for Brine and Mud circulation, Mud Mixing Tank, Brine Mixing Tank, and Base Oil + Brine + OBM storage tanks. Walkways, staircases, handrails, and lighting throughout.</p><p>All plant modules built to standard seafreight container footprints to avoid oversize shipping surcharges. Capacity scales up or down by adding / removing modules.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MML-20FT-HVAC',
    mpn: 'MML-20FT-HVAC',
    title: `Mobile Mud Lab, 20-ft Container, Lab Benches + Storage + HVAC`,
    categorySlug: 'dw-mobile-labs-workshops',
    descriptionShort: `Mobile drilling mud laboratory in 20-ft container. Lab benches, sample storage, HVAC, lighting, electrical, freshwater + waste plumbing.`,
    descriptionLong: `<p>Mobile drilling mud laboratory built inside a 20-ft seafreight container. Lab benches, instrument shelving, sample-bottle storage, HVAC, internal lighting, electrical distribution, and freshwater + waste plumbing.</p><p>Cementing-lab and well-testing-lab layouts available (20-ft, 40-ft, and customized footprints). Lab equipment package supplied by Indus on request or by the client.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-DAQ-15IN-MCH-USB',
    mpn: 'DAQ-15IN-MCH-USB',
    title: `Multi-Channel Data Acquisition System, 15-inch Touchscreen, USB Export, Frac-Fleet Ready`,
    categorySlug: 'ic-data-acquisition',
    descriptionShort: `Multi-channel oilfield DAQ with 15-inch touchscreen. 4-20 mA, 0-5 V, pulse and frequency inputs. USB export to ASCII / Excel for job reports.`,
    descriptionLong: `<p>Multi-channel oilfield Data Acquisition System engineered for pumping-unit and frac-fleet integration. Compatible signal types: 4-20 mA, 0-5 V, pulse, frequency. 15-inch touchscreen (9-inch and 11-inch variants available).</p><p>Operator-configurable display modes: data, chart, curves. Local storage and USB export in ASCII / Excel for post-job reports. Network connectivity (wired / wifi) to fleet Data Vans for centralized fleet control.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-MFM-2IN-WF-600-420',
    mpn: 'MFM-2IN-WF-600-420',
    title: `Magnetic Flowmeter, 2-inch Wafer, 600 psi, 4-20 mA Output`,
    categorySlug: 'ic-magnetic-flowmeters',
    descriptionShort: `2-inch wafer magnetic flowmeter, 600 psi MAWP, 4-20 mA output. ATEX Zone 1 variant available.`,
    descriptionLong: `<p>2-inch wafer-style magnetic flowmeter with 600 psi MAWP and 4-20 mA loop output. Designed for water, brine, mud and acid-resistant lining where chemistry requires. Local display optional; remote display via 4-20 mA into DAQ.</p><p>Sizes 1/2 inch to 12 inch available; pressure ratings to ANSI 600. ATEX Zone 1 explosion-proof variant on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-TFM-2IN-1502-15K',
    mpn: 'TFM-2IN-1502-15K',
    title: `Turbine Flowmeter, 2-inch Fig.1502 F×M, 15,000 psi, Frac / Cementing Service`,
    categorySlug: 'ic-turbine-flowmeters',
    descriptionShort: `2-inch turbine flowmeter, Fig.1502 F×M connections, 15,000 psi MAWP for frac and cementing service.`,
    descriptionLong: `<p>2-inch turbine flowmeter for high-pressure frac and cementing service. Fig.1502 F×M connections at 15,000 psi MAWP. Optical or magnetic pickup output with K-factor calibration certificate.</p><p>3-inch and lower-pressure variants available. NACE MR-0175 materials on request for sour-service applications.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-NRD-CRL-2IN-CMT',
    mpn: 'NRD-CRL-2IN-CMT',
    title: `Coriolis Mass Flowmeter (NRD), 2-inch, Cementing Service, Local + Remote Display`,
    categorySlug: 'ic-coriolis-nrd',
    descriptionShort: `2-inch Coriolis mass flowmeter providing flow + density + temperature. Non-radioactive alternative for cementing density control.`,
    descriptionLong: `<p>Coriolis-tube mass flowmeter providing simultaneous mass flow, fluid density, and fluid temperature outputs. Used as a non-radioactive densitometer (NRD) for cementing units, hydration units, and Liquid Additive Systems where radioactive source devices are restricted.</p><p>2-inch process connections as standard; 1-inch and 3-inch available. Local digital display + 4-20 mA remote outputs. ATEX Zone 1 / 2 enclosure variants.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-APS-1502-DEB-6IN-ADJ',
    mpn: 'APS-1502-DEB-6IN-ADJ',
    title: `Analogic Pressure Sensor, 2-inch Fig.1502 Debooster, 6-inch Gauge + Adjustable Shutdown`,
    categorySlug: 'ic-analogic-pressure-sensors',
    descriptionShort: `2-inch Fig.1502 pressure debooster paired with a 6-inch analogic gauge and adjustable overpressure shutdown proximity switch.`,
    descriptionLong: `<p>2-inch Fig.1502 pressure debooster providing safe transfer of HP wellhead pressure to the analogic gauge circuit. 6-inch glycerine-filled gauge for smooth pointer reading. Adjustable overpressure shutdown proximity switch enables interlock with ESD logic and shutdown sequencers.</p><p>Pressure ranges to 15,000 psi available. SS316 wetted connections; NACE MR-0175 on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-EPS-15K-1502M-420',
    mpn: 'EPS-15K-1502M-420',
    title: `Electronic Pressure Sensor, 0-15,000 psi, 2-inch Fig.1502M, 4-20 mA`,
    categorySlug: 'ic-electronic-pressure-sensors',
    descriptionShort: `0-15,000 psi electronic pressure sensor with 2-inch Fig.1502M HP connection. 4-20 mA output for DAQ integration.`,
    descriptionLong: `<p>0-15,000 psi electronic pressure sensor with 2-inch Fig.1502M HP hammer-union connection. 4-20 mA loop output; HART / digital options available. SS316 wetted parts as standard; NACE MR-0175 materials for sour-service.</p><p>Pressure ranges 0-5,000 / 0-10,000 / 0-15,000 / 0-20,000 psi. Temperature compensation calibrated across operating range.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-PSM-MPU-58UNF-M12',
    mpn: 'PSM-MPU-58UNF-M12',
    title: `Magnetic-Pickup Proximity Sensor, 5/8-18 UNF, M12 Connector, Stroke / RPM Counter`,
    categorySlug: 'ic-proximity-sensors',
    descriptionShort: `Magnetic-pickup proximity sensor with 5/8-18 UNF mount and M12 connector. Reads pump shaft bolt counts for RPM + stroke / pump-displacement calculations.`,
    descriptionLong: `<p>Magnetic-pickup proximity sensor used as a bolt-counter on triplex / quintuplex pump crank shafts to feed RPM and calculated displacement back to the unit DAQ. 5/8-18 UNF threaded body with M12 4-pin connector.</p><p>No onboard power required — output is a passive signal proportional to shaft speed. Hazardous-area-rated variants available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-PG-12NPT-BM-6IN-10K',
    mpn: 'PG-12NPT-BM-6IN-10K',
    title: `Pressure Gauge, 1/2-inch NPT Bottom Mount, 6-inch Dial, 10,000 psi, SS316, Glycerine-Filled`,
    categorySlug: 'ic-pressure-gauges',
    descriptionShort: `1/2-inch NPT bottom-mount pressure gauge, 6-inch dial, 0-10,000 psi range. SS316 connection, glycerine-filled for smooth reading.`,
    descriptionLong: `<p>High-pressure oilfield pressure gauge with 1/2-inch NPT bottom-mount connection, 6-inch dial face, and 0-10,000 psi range. SS316 wetted connection. Glycerine-filled for smooth pointer behavior under vibration.</p><p>Full range available: 100, 200, 500, 1,000, 3,000, 5,000, 10,000, 15,000 psi. Panel-mount variant with 1/2-inch NPT rear connection. NACE MR-0175 materials on request.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-TMW-12NPT-PU-SS316',
    mpn: 'TMW-12NPT-PU-SS316',
    title: `Bimetal Thermometer + Thermowell Pair, 1/2-inch NPT M×F, P+U API 6A Range, SS316`,
    categorySlug: 'ic-thermometers-thermowells',
    descriptionShort: `Matched bimetal thermometer (1/2-inch NPT male, multiple stem lengths) and integral thermowell (1/2-inch NPT M×F) in SS316. API 6A P+U temperature range.`,
    descriptionLong: `<p>Matched bimetal thermometer and thermowell pair. The thermometer has a 1/2-inch NPT male connection with selectable stem length (2.5, 4, 6, 9 inch) and an API 6A P+U temperature range (-20 °F to +250 °F).</p><p>The thermowell is integral construction in SS316 with 1/2-inch NPT male-to-female connections, sized to match the thermometer stem. SS304 wetted-parts variant available. Pressure rating to 15,000 psi at process side; bore size selectable.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-ACDC-400-24-NEMA4X-1K',
    mpn: 'ACDC-400-24-NEMA4X-1K',
    title: `AC/DC Converter Package, 400 V AC → 24 V DC, NEMA 4X Enclosure, 1 kW`,
    categorySlug: 'ic-acdc-converters',
    descriptionShort: `400 V AC → 24 V DC converter package, 1 kW output. NEMA 4X enclosure with input breaker, output terminals, status LEDs.`,
    descriptionLong: `<p>AC/DC converter package powering DC control circuits from a high-voltage AC mains supply. 400 V AC input → 24 V DC output, 1 kW continuous duty. NEMA 4X enclosure containing the converter, input breaker, output power-supply connections, status LEDs and surge protection.</p><p>Voltage variants: 230 / 380 / 415 / 440 / 460 V AC input; 12 / 24 V DC output. Output powers 250 W / 500 W / 1 kW / 2 kW. Hazardous-area Ex-d variant available.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-VFD-500-AC-ATX2',
    mpn: 'VFD-500-AC-ATX2',
    title: `VFD Package, AC Motor + Drive, 500 HP, ATEX Zone 2, Frac-Pumper Compatible`,
    categorySlug: 'ic-vfd-systems',
    descriptionShort: `500 HP AC motor + VFD drive package for frac / cementing pumper deployment. ATEX Zone 2 enclosure, regenerative braking, oilfield-environment ratings.`,
    descriptionLong: `<p>VFD (Variable Frequency Drive) package supplying a 500 HP AC motor for oilfield pump duty. Replaces costly DC converter and DC motor systems on legacy units. ATEX Zone 2 enclosure; regenerative braking option for energy recovery on deceleration.</p><p>Motor + drive system rated for offshore environment (saltwater, vibration, temperature). Sizes 100 / 250 / 500 / 750 / 1,000 HP available. Compatible with frac pumper, cementing unit, transfer pump and stimulation unit deployments.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-EXP-AL-ATX1-600X800',
    mpn: 'EXP-AL-ATX1-600X800',
    title: `Explosion-Proof Electrical Panel, Aluminium-Cast, ATEX Zone 1, 600 mm × 800 mm`,
    categorySlug: 'ic-electrical-panels',
    descriptionShort: `Explosion-proof aluminium-cast electrical enclosure for hazardous-area use. ATEX Zone 1 rated, 600 mm × 800 mm internal envelope.`,
    descriptionLong: `<p>Explosion-proof aluminium-cast electrical panel for ATEX Zone 1 hazardous-area deployment. 600 mm × 800 mm internal envelope; multiple sizes available. Internal mounting plate houses breakers, contactors, relays, terminal blocks, and surge protection per project schematic.</p><p>IECEx-certified variants available. Weatherproof steel-sheet enclosure (powder-coated) for non-hazardous deployment as a lower-cost option. IP65 / IP66 sealing as standard.</p>`,
  },
  {
    ...COMMON_PRODUCT,
    sku: 'IH-CAR-4IN-FORGED',
    mpn: 'CAR-4IN-FORGED',
    title: `Cable Anchor Restraint Clamp, Forged Steel, 4-inch Treating Iron OD, Pressure-Pumping Spec`,
    categorySlug: 'oilfield-restraint-systems',
    descriptionShort: `Forged-steel cable anchor restraint clamp matched to 4-inch treating iron OD. Eye-style termination for steel safety cable. Pressure-pumping specification.`,
    descriptionLong: `<p>Forged-steel cable anchor restraint clamp engineered for installation on treating iron elements during high-pressure pumping operations. Tube-OD matched (4-inch treating iron); other OD sizes 2-inch, 3-inch and 5-inch on request. Eye-style termination accepts a steel safety cable in line with API standards for pumping-iron whip-restraint.</p><p>Forged construction with NACE MR-0175 material option on request. Pressure-pumping operations spec — sized for cementing, stimulation, fracturing and well-testing line restraint.</p>`,
  },
]

const navigation: NavReplaceLeavesConfig[] = [
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'cementing-equipment',
    parentSubLabel: `Cementing Equipment`,
    createColumnIfMissing: true,
    newColumnLabel: `Cementing Equipment`,
    newColumnPosition: 11,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `Cementing Units`, categorySlug: 'cementing-units' },
      { label: `Batch Mixers (Cement)`, categorySlug: 'cementing-batch-mixer' },
      { label: `On-The-Fly Mixers`, categorySlug: 'cementing-on-the-fly-mixer' },
      { label: `Cement Silos`, categorySlug: 'cementing-silos' },
      { label: `Cutting Bottles`, categorySlug: 'cementing-cutting-bottle' },
      { label: `Dust Collectors`, categorySlug: 'cementing-dust-collector' },
      { label: `Rock Catchers`, categorySlug: 'cementing-rock-catcher' },
    ],
  },
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'stimulation-equipment',
    parentSubLabel: `Stimulation Equipment`,
    createColumnIfMissing: true,
    newColumnLabel: `Stimulation Equipment`,
    newColumnPosition: 12,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `Nitrogen (N₂) Pumping Units`, categorySlug: 'stimulation-nitrogen-unit' },
      { label: `Transfer Pumps (Stimulation)`, categorySlug: 'stimulation-transfer-pump' },
      { label: `Acid Tanks`, categorySlug: 'stimulation-acid-tanks' },
      { label: `Stimulation Batch Mixers`, categorySlug: 'stimulation-batch-mixers' },
      { label: `Stimulation Pumping Units`, categorySlug: 'stimulation-pumping-units' },
    ],
  },
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'fracturing-equipment',
    parentSubLabel: `Fracturing Equipment`,
    createColumnIfMissing: true,
    newColumnLabel: `Fracturing Equipment`,
    newColumnPosition: 13,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `Frac Pumpers`, categorySlug: 'frac-pumpers' },
      { label: `Frac Transfer Pumps`, categorySlug: 'frac-transfer-pumps' },
      { label: `Frac Manifolds / Missiles`, categorySlug: 'frac-manifold' },
      { label: `Frac Sand Silos / Sand Chief`, categorySlug: 'frac-sand-silos' },
      { label: `Frac Blenders (MFR Series)`, categorySlug: 'frac-blender' },
      { label: `Frac Hydration Units`, categorySlug: 'frac-hydration-unit' },
      { label: `Frac LAS (Liquid Additive System)`, categorySlug: 'frac-las' },
      { label: `Frac Data Vans`, categorySlug: 'frac-data-van' },
      { label: `Frac Tanks`, categorySlug: 'frac-tanks' },
    ],
  },
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'well-testing-equipment',
    parentSubLabel: `Well Testing Equipment`,
    createColumnIfMissing: true,
    newColumnLabel: `Well Testing Equipment`,
    newColumnPosition: 14,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `3-Phase Separators`, categorySlug: 'wt-3-phase-separator' },
      { label: `MPFM Systems`, categorySlug: 'wt-mpfm-system' },
      { label: `Surge Tanks`, categorySlug: 'wt-surge-tank' },
      { label: `Knock Out Drums`, categorySlug: 'wt-knock-out-drum' },
      { label: `Flare Stacks`, categorySlug: 'wt-flare-stack' },
      { label: `Transfer Pumps (Well Testing)`, categorySlug: 'wt-transfer-pump' },
      { label: `Backside Flush / Test Pumps`, categorySlug: 'wt-flush-test-pump' },
      { label: `Sand Filters`, categorySlug: 'wt-sand-filter' },
      { label: `ESD Panels`, categorySlug: 'wt-esd-panel' },
      { label: `Data Headers`, categorySlug: 'wt-data-header' },
      { label: `Piping Packages (Well Testing + EPF)`, categorySlug: 'wt-piping-packages' },
    ],
  },
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'drilling-workover-systems',
    parentSubLabel: `Drilling & Workover Systems`,
    createColumnIfMissing: true,
    newColumnLabel: `Drilling & Workover Systems`,
    newColumnPosition: 15,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `Mud Pump Packages`, categorySlug: 'dw-mud-pump-package' },
      { label: `Mud Manifolds`, categorySlug: 'dw-mud-manifolds' },
      { label: `Mud Degassers`, categorySlug: 'dw-mud-degasser' },
      { label: `Mud Tanks`, categorySlug: 'dw-mud-tanks' },
      { label: `Workover Tanks`, categorySlug: 'dw-workover-tanks' },
      { label: `Liquid Mud Plants (LMP)`, categorySlug: 'dw-liquid-mud-plant' },
      { label: `Mobile Labs & Workshops`, categorySlug: 'dw-mobile-labs-workshops' },
    ],
  },
  {
    menuLocation: 'primary_megamenu',
    parentColumnCategorySlug: 'instrumentation-controls',
    parentSubLabel: `Instrumentation & Controls`,
    createColumnIfMissing: true,
    newColumnLabel: `Instrumentation & Controls`,
    newColumnPosition: 16,
    createSubSectionIfMissing: true,
    newSubSectionPosition: 0,
    replacements: [
      { label: `Data Acquisition Systems`, categorySlug: 'ic-data-acquisition' },
      { label: `Magnetic Flowmeters`, categorySlug: 'ic-magnetic-flowmeters' },
      { label: `Turbine Flowmeters`, categorySlug: 'ic-turbine-flowmeters' },
      { label: `Coriolis Mass Flowmeters (NRD)`, categorySlug: 'ic-coriolis-nrd' },
      { label: `Analogic Pressure Sensors`, categorySlug: 'ic-analogic-pressure-sensors' },
      { label: `Electronic Pressure Sensors`, categorySlug: 'ic-electronic-pressure-sensors' },
      { label: `Proximity Sensors`, categorySlug: 'ic-proximity-sensors' },
      { label: `HP Pressure Gauges`, categorySlug: 'ic-pressure-gauges' },
      { label: `Thermometers & Thermowells`, categorySlug: 'ic-thermometers-thermowells' },
      { label: `AC/DC Converters`, categorySlug: 'ic-acdc-converters' },
      { label: `VFD Systems`, categorySlug: 'ic-vfd-systems' },
      { label: `Explosion-Proof Electrical Panels`, categorySlug: 'ic-electrical-panels' },
    ],
  },
]

export default {
  meta: {
    id: '2026-05-11-msi-catalogue-expansion',
    description: 'Adds 6 new top-level categories + 51 sub-categories + 52 representative RFQ products covering Cementing / Stimulation / Fracturing / Well Testing / Drilling & Workover Systems / Instrumentation & Controls + Restraint Systems sub under Oilfield Valve Accessories. Closes the MSI (msifze.com) taxonomy gap against the Indus live catalogue.',
  },
  // This batch upserts no brands and no spec templates — every product uses
  // the existing house brand 'indus'. Both keys have a Zod default of [], but
  // `satisfies ImportBatch` checks the post-default (output) type, so they
  // must be stated.
  brands: [],
  categories,
  specTemplates: [],
  products,
  navigation,
} satisfies ImportBatch